//! `verum hooks install / uninstall / status` integration tests.

use std::path::PathBuf;
use std::process::Command;

fn binary() -> &'static str {
    env!("CARGO_BIN_EXE_verum")
}

fn make_git_repo(name: &str) -> PathBuf {
    let mut dir = std::env::temp_dir();
    dir.push(format!("verum_hooks_{}_{}", name, std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(dir.join(".git")).expect("create .git");
    std::fs::create_dir_all(dir.join(".git").join("hooks")).expect("create hooks");
    dir
}

fn run(dir: &PathBuf, args: &[&str]) -> std::process::Output {
    Command::new(binary())
        .arg("hooks")
        .args(args)
        .current_dir(dir)
        .output()
        .expect("verum hooks spawn")
}

#[test]
fn install_writes_pre_commit_with_marker() {
    let dir = make_git_repo("install");
    let out = run(&dir, &["install"]);
    assert!(
        out.status.success(),
        "install should succeed in a fresh repo. stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let hook = dir.join(".git").join("hooks").join("pre-commit");
    assert!(hook.exists(), "pre-commit hook should be written");
    let content = std::fs::read_to_string(&hook).expect("read hook");
    assert!(
        content.contains("Generated by `verum hooks install`"),
        "hook must carry our header marker: {content}"
    );
    assert!(content.contains("verum lint"), "hook must run verum lint");
    assert!(content.contains("verum fmt --check"), "hook must run verum fmt --check");
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn install_refuses_to_overwrite_user_hook() {
    let dir = make_git_repo("refuse_clobber");
    let hook = dir.join(".git").join("hooks").join("pre-commit");
    std::fs::write(&hook, "#!/bin/sh\n# my hand-written hook\necho 'hi'\n")
        .expect("seed hook");
    let out = run(&dir, &["install"]);
    assert!(
        !out.status.success(),
        "install must refuse to overwrite a non-verum hook"
    );
    let after = std::fs::read_to_string(&hook).expect("read hook");
    assert!(
        after.contains("hand-written"),
        "user hook must remain intact: {after}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn install_force_overwrites_existing_hook() {
    let dir = make_git_repo("force");
    let hook = dir.join(".git").join("hooks").join("pre-commit");
    std::fs::write(&hook, "#!/bin/sh\necho old\n").expect("seed hook");
    let out = run(&dir, &["install", "--force"]);
    assert!(
        out.status.success(),
        "install --force must overwrite. stderr: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    let after = std::fs::read_to_string(&hook).expect("read hook");
    assert!(
        after.contains("Generated by `verum hooks install`"),
        "force should write our managed hook: {after}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn uninstall_removes_only_managed_hooks() {
    let dir = make_git_repo("uninstall_managed");
    // First install, then uninstall.
    let _ = run(&dir, &["install"]);
    let out = run(&dir, &["uninstall"]);
    assert!(out.status.success(), "uninstall should succeed on managed hook");
    let hook = dir.join(".git").join("hooks").join("pre-commit");
    assert!(!hook.exists(), "managed hook should be removed");
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn uninstall_refuses_to_remove_unmanaged_hook() {
    let dir = make_git_repo("uninstall_unmanaged");
    let hook = dir.join(".git").join("hooks").join("pre-commit");
    std::fs::write(&hook, "#!/bin/sh\necho user\n").expect("seed hook");
    let out = run(&dir, &["uninstall"]);
    assert!(
        !out.status.success(),
        "uninstall must refuse to remove a non-verum hook"
    );
    assert!(hook.exists(), "user hook must remain intact");
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn status_reports_installation_state() {
    let dir = make_git_repo("status");
    let out_not_installed = run(&dir, &["status"]);
    assert!(out_not_installed.status.success());
    // Stdout is colored output; check stderr or stdout contains a sensible word.
    let combined = format!(
        "{}\n{}",
        String::from_utf8_lossy(&out_not_installed.stdout),
        String::from_utf8_lossy(&out_not_installed.stderr)
    );
    assert!(
        combined.contains("not installed"),
        "status should report 'not installed', got: {combined}"
    );

    let _ = run(&dir, &["install"]);
    let out_installed = run(&dir, &["status"]);
    let combined2 = format!(
        "{}\n{}",
        String::from_utf8_lossy(&out_installed.stdout),
        String::from_utf8_lossy(&out_installed.stderr)
    );
    assert!(
        combined2.contains("installed"),
        "status should report installed, got: {combined2}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}
