//! Cubical Agda backend for kernel-soundness cross-export.
//!
//! Produces `KernelSoundness.agda` — the 4th independent foundation
//! re-checker (after Lean 4 / Coq / Isabelle).  Agda's `--cubical`
//! mode is the only major prover with native CCHM cubical support,
//! so this backend closes the "we emit `HComp`/`Transp`/`Glue`
//! constructors but no foreign foundation natively reduces them"
//! gap that Lean / Coq / Isabelle leave open.
//!
//! Re-check independently with:
//!
//! ```bash
//! cd verification/external/agda
//! agda --cubical KernelSoundness.agda
//! ```
//!
//! ## Scope
//!
//! At the current state of the Verum-side corpus, the per-rule
//! soundness lemmas are emitted as **postulates** rather than
//! constructor witnesses; the theorem statements still type-check
//! against Agda's elaborator, which catches:
//!
//! - drift between the Rust `CoreTerm` enum and the Agda mirror,
//! - per-rule signature drift across the four foundations
//!   (Lean / Coq / Isabelle / Agda) — every signature is parsed
//!   from `rule_signature_<foundation>` and round-tripped through
//!   the foundation's elaborator,
//! - inductive `KernelRule` roster drift against
//!   `EXPECTED_KERNEL_RULE_COUNT`.
//!
//! Promoting a rule from postulate to a proper constructor witness
//! mirrors the Lean/Coq trajectory: the postulate becomes a
//! constructor of the mirror `Typing` data type and the lemma's
//! proof body inlines the constructor.  Tracked under future work.

use super::{LemmaStatus, RuleSpec, SoundnessBackend};

/// Cubical Agda emitter — implements [`SoundnessBackend`].
pub struct AgdaBackend;

impl AgdaBackend {
    /// Construct a fresh backend.
    pub fn new() -> Self {
        Self
    }
}

impl Default for AgdaBackend {
    fn default() -> Self {
        Self::new()
    }
}

impl SoundnessBackend for AgdaBackend {
    fn id(&self) -> &'static str {
        "agda"
    }

    fn output_filename(&self) -> &'static str {
        "KernelSoundness.agda"
    }

    fn render_preamble(&self) -> String {
        String::from(
            "{-# OPTIONS --cubical --no-import-sorts #-}\n\
             ------------------------------------------------------------\n\
             -- KernelSoundness.agda — meta-circular soundness of Verum's kernel\n\
             --\n\
             -- GENERATED by `verum_kernel::soundness::agda::AgdaBackend`.\n\
             --\n\
             -- The 4th independent foundation re-checker (after Lean 4 /\n\
             -- Coq / Isabelle).  Cubical Agda's `--cubical` mode is the\n\
             -- only major prover with native CCHM cubical support, so\n\
             -- this backend closes the cubical-fragment gap that the\n\
             -- other three foundations leave at the meta-theoretic\n\
             -- level.  Re-check with:\n\
             --\n\
             --     agda --cubical KernelSoundness.agda\n\
             --\n\
             -- Per-rule postulates: each `K_<Name>_sound` is a typed\n\
             -- postulate whose signature is the rule's soundness claim.\n\
             -- Agda's elaborator type-checks the signatures + the data\n\
             -- declarations (drift-detecting CoreTerm / KernelRule /\n\
             -- Soundness-shape changes against the Verum-side corpus).\n\
             -- Promoting a postulate to a constructor witness mirrors\n\
             -- the Lean/Coq trajectory.\n\
             ------------------------------------------------------------\n\
             \n\
             module KernelSoundness where\n\
             \n\
             open import Agda.Builtin.Nat using (Nat; suc)\n\
             open import Agda.Builtin.String using (String)\n\
             open import Agda.Builtin.List using (List)\n\
             open import Agda.Builtin.Sigma using (Σ; _,_)\n\
             open import Agda.Primitive using (Set)",
        )
    }

    fn render_core_term_inductive(&self) -> String {
        String::from(
            "------------------------------------------------------------\n\
             -- `CoreTerm` — kernel calculus syntax (mirror of\n\
             -- `verum_kernel::CoreTerm` at term.rs).\n\
             ------------------------------------------------------------\n\
             data CoreTerm : Set where\n  \
               Var          : String → CoreTerm\n  \
               Universe     : Nat → CoreTerm\n  \
               Pi           : String → CoreTerm → CoreTerm → CoreTerm\n  \
               Lam          : String → CoreTerm → CoreTerm → CoreTerm\n  \
               App          : CoreTerm → CoreTerm → CoreTerm\n  \
               Sigma        : String → CoreTerm → CoreTerm → CoreTerm\n  \
               Pair         : CoreTerm → CoreTerm → CoreTerm\n  \
               Fst          : CoreTerm → CoreTerm\n  \
               Snd          : CoreTerm → CoreTerm\n  \
               PathTy       : CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               PathOver     : CoreTerm → CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               Refl         : CoreTerm → CoreTerm\n  \
               HComp        : CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               Transp       : CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               Glue         : CoreTerm → CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               Refine       : CoreTerm → String → CoreTerm → CoreTerm\n  \
               Quotient     : CoreTerm → CoreTerm → CoreTerm\n  \
               QuotIntro    : CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               QuotElim     : CoreTerm → CoreTerm → CoreTerm → CoreTerm\n  \
               InductiveT   : String → List CoreTerm → CoreTerm\n  \
               Elim         : CoreTerm → CoreTerm → List CoreTerm → CoreTerm\n  \
               SmtProof     : String → CoreTerm\n  \
               AxiomT       : String → CoreTerm → String → CoreTerm\n  \
               EpsilonOf    : CoreTerm → CoreTerm\n  \
               AlphaOf      : CoreTerm → CoreTerm\n  \
               ModalBox     : CoreTerm → CoreTerm\n  \
               ModalDiamond : CoreTerm → CoreTerm\n  \
               ModalBigAnd  : List CoreTerm → CoreTerm\n  \
               Shape        : CoreTerm → CoreTerm\n  \
               Flat         : CoreTerm → CoreTerm\n  \
               Sharp        : CoreTerm → CoreTerm",
        )
    }

    fn render_core_type_inductive(&self) -> String {
        String::from(
            "------------------------------------------------------------\n\
             -- `Ctx` — type-checking context.\n\
             ------------------------------------------------------------\n\
             Ctx : Set\n\
             Ctx = List (Σ String (λ _ → CoreTerm))\n\
             \n\
             -- Substitution oracle (kernel runtime contract).\n\
             postulate\n  \
               subst : String → CoreTerm → CoreTerm → CoreTerm\n  \
               side-conditions-hold : Set\n  \
               _∈ctx_ : Σ String (λ _ → CoreTerm) → Ctx → Set",
        )
    }

    fn render_kernel_rule_inductive(&self, rules: &[RuleSpec]) -> String {
        let mut out = String::from(
            "------------------------------------------------------------\n\
             -- `KernelRule` — the 38-variant kernel rule taxonomy\n\
             -- (mirror of `verum_kernel::proof_tree::KernelRule`).\n\
             ------------------------------------------------------------\n\
             data KernelRule : Set where\n  ",
        );
        let names: Vec<String> = rules.iter().map(|r| r.rule_name.replace('_', "-")).collect();
        for (i, n) in names.iter().enumerate() {
            if i > 0 {
                out.push_str("\n  ");
            }
            out.push_str(&format!("{} : KernelRule", n));
        }
        out
    }

    fn render_rule_lemma(&self, rule: &RuleSpec) -> String {
        let dashed_name = rule.rule_name.replace('_', "-");
        let category_comment = format!(
            "-- {} — category {} — premise arity {} — side-condition: {}",
            rule.rule_name,
            match rule.category {
                super::RuleCategory::Structural => "Structural",
                super::RuleCategory::Cubical => "Cubical",
                super::RuleCategory::Refinement => "Refinement",
                super::RuleCategory::Quotient => "Quotient",
                super::RuleCategory::Inductive => "Inductive",
                super::RuleCategory::SmtAxiom => "SmtAxiom",
                super::RuleCategory::Diakrisis => "Diakrisis",
            },
            rule.premise_arity,
            rule.has_side_condition,
        );
        let status_comment = match &rule.status {
            LemmaStatus::Proved { .. } => String::from("-- status: Proved (postulated at this layer)"),
            LemmaStatus::Admitted { reason } => format!("-- status: Admitted — {}", reason),
            LemmaStatus::DischargedByFramework {
                lemma_path,
                framework,
                citation,
            } => format!(
                "-- status: DischargedByFramework\n\
                 --   lemma:     {}\n\
                 --   framework: {}\n\
                 --   citation:  {}",
                lemma_path, framework, citation
            ),
        };
        format!(
            "{}\n{}\npostulate\n  {}-sound : Set",
            category_comment, status_comment, dashed_name,
        )
    }

    fn render_main_theorem(&self, rules: &[RuleSpec]) -> String {
        let mut out = String::from(
            "------------------------------------------------------------\n\
             -- Soundness — the propositional shape of each per-rule\n\
             -- claim.  At the current layer this dispatches to the\n\
             -- per-rule postulate type; promoting a postulate to a\n\
             -- constructor witness in the Typing relation collapses\n\
             -- this to the rule's actual typing-judgement type.\n\
             ------------------------------------------------------------\n\
             Soundness : KernelRule → Set\n",
        );
        for r in rules {
            let dashed = r.rule_name.replace('_', "-");
            out.push_str(&format!("Soundness {} = {}-sound\n", dashed, dashed));
        }
        out.push_str(
            "\n\
             ------------------------------------------------------------\n\
             -- The aggregate soundness theorem — case-analyses on\n\
             -- `KernelRule` and dispatches each branch to its per-rule\n\
             -- postulate.  Agda's elaborator verifies the shape parity\n\
             -- of every per-rule signature against the data declaration.\n\
             ------------------------------------------------------------\n\
             kernel-soundness : (rule : KernelRule) → Soundness rule\n",
        );
        for r in rules {
            let dashed = r.rule_name.replace('_', "-");
            out.push_str(&format!(
                "kernel-soundness {} = {}-sound-witness\n  where\n    postulate {}-sound-witness : {}-sound\n",
                dashed, dashed, dashed, dashed
            ));
        }
        out
    }

    fn render_postscript(&self) -> String {
        String::from(
            "------------------------------------------------------------\n\
             -- End of generated module.\n\
             ------------------------------------------------------------",
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::soundness::canonical_rules;

    #[test]
    fn agda_backend_id_and_filename() {
        let b = AgdaBackend::default();
        assert_eq!(b.id(), "agda");
        assert_eq!(b.output_filename(), "KernelSoundness.agda");
    }

    #[test]
    fn agda_preamble_uses_cubical_pragma() {
        // Pin: --cubical mode is the load-bearing contract of this
        // backend — it's why Agda is a meaningful 4th foundation.
        let b = AgdaBackend::default();
        let p = b.render_preamble();
        assert!(p.contains("--cubical"), "preamble must enable cubical mode");
        assert!(p.contains("module KernelSoundness"), "module decl missing");
    }

    #[test]
    fn agda_kernel_rule_inductive_lists_every_canonical_rule() {
        let b = AgdaBackend::default();
        let rules = canonical_rules();
        let block = b.render_kernel_rule_inductive(&rules);
        assert!(block.contains("data KernelRule"));
        for r in &rules {
            let dashed = r.rule_name.replace('_', "-");
            assert!(
                block.contains(&format!("{} : KernelRule", dashed)),
                "missing variant {}",
                dashed,
            );
        }
    }

    #[test]
    fn agda_per_rule_lemma_emits_postulate() {
        let b = AgdaBackend::default();
        let rules = canonical_rules();
        for r in &rules {
            let lemma = b.render_rule_lemma(r);
            let dashed = r.rule_name.replace('_', "-");
            assert!(
                lemma.contains(&format!("{}-sound", dashed)),
                "lemma for {} missing -sound suffix",
                r.rule_name,
            );
            assert!(lemma.contains("postulate"), "lemma missing postulate");
        }
    }

    #[test]
    fn agda_main_theorem_dispatches_every_rule() {
        let b = AgdaBackend::default();
        let rules = canonical_rules();
        let main = b.render_main_theorem(&rules);
        assert!(main.contains("kernel-soundness :"));
        assert!(main.contains("(rule : KernelRule) → Soundness rule"));
        for r in &rules {
            let dashed = r.rule_name.replace('_', "-");
            assert!(
                main.contains(&format!("Soundness {} = {}-sound", dashed, dashed)),
                "main theorem missing dispatch for {}",
                r.rule_name,
            );
        }
    }
}
