//! Coq backend for kernel-soundness cross-export.
//!
//! Produces `kernel_soundness.v` — full real-Typing shape across all
//! 38 kernel rules, mirroring `lean.rs` exactly.  The 17 with-IOU
//! rules are captured as `Axiom <Rule>_iou : … -> Prop` declarations;
//! discharging an IOU = replacing the axiom with a `Definition`.
//!
//! `coqc kernel_soundness.v` re-checks Verum's claim independently.

use super::{LemmaStatus, RuleSpec, SoundnessBackend};

/// Coq emitter — implements [`SoundnessBackend`].
pub struct CoqBackend;

impl CoqBackend {
    /// Construct a fresh backend.
    pub fn new() -> Self {
        Self
    }
}

impl Default for CoqBackend {
    fn default() -> Self {
        Self::new()
    }
}

impl SoundnessBackend for CoqBackend {
    fn id(&self) -> &'static str {
        "coq"
    }

    fn output_filename(&self) -> &'static str {
        "kernel_soundness.v"
    }

    fn render_preamble(&self) -> String {
        "(* ============================================================== *)\n\
         (* kernel_soundness.v — meta-circular soundness of Verum's kernel *)\n\
         (* ============================================================== *)\n\
         (*                                                                *)\n\
         (* GENERATED by `verum_kernel::soundness::coq::CoqBackend`.       *)\n\
         (*                                                                *)\n\
         (*     coqc kernel_soundness.v                                    *)\n\
         (*                                                                *)\n\
         (* Per-rule `Axiom <Rule>_iou` declarations are the IOU surface;  *)\n\
         (* discharge = replace with a `Definition`.                       *)\n\
         (* ============================================================== *)\n\
         \n\
         From Stdlib Require Import Strings.String.\n\
         From Stdlib Require Import Lists.List.\n\
         Import ListNotations.\n\
         Open Scope string_scope."
            .to_string()
    }

    fn render_core_term_inductive(&self) -> String {
        "(* CoreTerm — kernel calculus syntax. *)\n\
         Inductive CoreTerm : Type :=\n  \
           | Var (name : string)\n  \
           | Universe (level : nat)\n  \
           | Pi (binder : string) (domain codomain : CoreTerm)\n  \
           | Lam (binder : string) (domain body : CoreTerm)\n  \
           | App (head arg : CoreTerm)\n  \
           | Sigma (binder : string) (fst_ty snd_ty : CoreTerm)\n  \
           | Pair (fst snd : CoreTerm)\n  \
           | Fst (inner : CoreTerm)\n  \
           | Snd (inner : CoreTerm)\n  \
           | PathTy (carrier lhs rhs : CoreTerm)\n  \
           | PathOver (motive path lhs rhs : CoreTerm)\n  \
           | Refl (value : CoreTerm)\n  \
           | HComp (phi walls base : CoreTerm)\n  \
           | Transp (path regular value : CoreTerm)\n  \
           | Glue (carrier phi fiber equiv : CoreTerm)\n  \
           | Refine (base : CoreTerm) (binder : string) (predicate : CoreTerm)\n  \
           | Quotient (base equiv : CoreTerm)\n  \
           | QuotIntro (value base equiv : CoreTerm)\n  \
           | QuotElim (scrutinee motive case_fn : CoreTerm)\n  \
           | Inductive_ (path : string) (args : list CoreTerm)\n  \
           | Elim (scrutinee motive : CoreTerm) (cases : list CoreTerm)\n  \
           | SmtProof (solver_tag : string)\n  \
           | Axiom_ (name : string) (ty : CoreTerm) (framework : string)\n  \
           | EpsilonOf (articulation : CoreTerm)\n  \
           | AlphaOf (enactment : CoreTerm)\n  \
           | ModalBox (inner : CoreTerm)\n  \
           | ModalDiamond (inner : CoreTerm)\n  \
           | ModalBigAnd (components : list CoreTerm)\n  \
           | Shape (inner : CoreTerm)\n  \
           | Flat (inner : CoreTerm)\n  \
           | Sharp (inner : CoreTerm)."
            .to_string()
    }

    fn render_core_type_inductive(&self) -> String {
        "(* CoreType — structural type-head view. *)\n\
         Inductive CoreType : Type :=\n  \
           | UniverseTy (level : nat)\n  \
           | PiTy\n  \
           | SigmaTy\n  \
           | PathTyHead\n  \
           | RefineTy\n  \
           | GlueTy\n  \
           | InductiveTy (path : string)\n  \
           | OtherTy."
            .to_string()
    }

    fn render_kernel_rule_inductive(&self, rules: &[RuleSpec]) -> String {
        let mut out = String::new();

        out.push_str("(* KernelRule — the 38 inference-rule names. *)\n");
        out.push_str("Inductive KernelRule : Type :=");
        for r in rules {
            out.push_str(&format!("\n    | {}", r.rule_name));
        }
        out.push_str(".\n\n");

        out.push_str(
            "Definition Ctx : Type := list (string * CoreTerm).\n\n\
             Parameter subst : string -> CoreTerm -> CoreTerm -> CoreTerm.\n\n\
             Parameter side_conditions_hold : Prop.\n\n",
        );

        out.push_str(iou_axioms_coq());
        out.push_str("\n\n");
        out.push_str(TYPING_INDUCTIVE_COQ);
        out
    }

    fn render_rule_lemma(&self, rule: &RuleSpec) -> String {
        let category_comment = format!(
            "(* {} — category {} — premise arity {} — side-condition: {} *)",
            rule.rule_name,
            match rule.category {
                super::RuleCategory::Structural => "Structural",
                super::RuleCategory::Cubical => "Cubical",
                super::RuleCategory::Refinement => "Refinement",
                super::RuleCategory::Quotient => "Quotient",
                super::RuleCategory::Inductive => "Inductive",
                super::RuleCategory::SmtAxiom => "SmtAxiom",
                super::RuleCategory::Diakrisis => "Diakrisis",
            },
            rule.premise_arity,
            rule.has_side_condition,
        );

        // Resolve the rule's typing-relation type body and Typing-
        // constructor witness from the per-rule signature table.
        // Fallback for the K_Pos / K_FwAx pair whose content is meta
        // (positivity / framework-axiom admission) is the generic
        // `side_conditions_hold -> True` shape.
        //
        // `parts.witness` is `Some(<name>)` only when the proof
        // block reduces to the single-tactic `Proof. exact <name>.
        // Qed.` shape; multi-tactic scripts (e.g. `intros; apply
        // T_quot_elim with (...); assumption.`) yield `None` so
        // the renderer below dispatches via the rule's recorded
        // `coq_tactics` rather than wrapping the whole proof block
        // in `Proof. exact <block>. Qed.` (which produced the
        // malformed historical output for K_Quot_Elim / K_Elim).
        let (type_body, constructor_witness) =
            match rule_signature_coq(&rule.rule_name).and_then(parse_coq_signature) {
                Some(parts) => (parts.type_body, parts.witness),
                None => ("side_conditions_hold -> True".to_string(), None),
            };

        // Status-driven proof body and metadata comment.  Discharged-by-
        // framework and admitted rules emit `Admitted.` plus a citation
        // / reason comment so the trust extension is auditable; proved
        // rules dispatch to their inductive-constructor witness (or to
        // the rule's recorded `coq_tactics` when no constructor is in
        // the table).
        let (status_comment, proof_body) = match &rule.status {
            LemmaStatus::Proved { coq_tactics, .. } => match constructor_witness {
                Some(w) => (
                    String::new(),
                    format!("Proof. exact {}. Qed.", w),
                ),
                None => (
                    String::new(),
                    format!("Proof.\n{}\nQed.", coq_tactics),
                ),
            },
            LemmaStatus::Admitted { reason } => (
                format!("(* reason: {} *)\n", reason),
                "Admitted.".to_string(),
            ),
            LemmaStatus::DischargedByFramework {
                lemma_path,
                framework,
                citation,
            } => (
                format!(
                    "(* discharged-by: {} *)\n(* framework: {} *)\n(* citation: {} *)\n",
                    lemma_path, framework, citation
                ),
                "Admitted.".to_string(),
            ),
        };

        format!(
            "{}\n{}Lemma {} :\n  {}.\n{}",
            category_comment, status_comment, rule.lemma_name, type_body, proof_body,
        )
    }

    fn render_main_theorem(&self, rules: &[RuleSpec]) -> String {
        // Aggregate the 38 per-rule lemmas into a single
        // `kernel_soundness` theorem via case analysis on `KernelRule`.
        // `Soundness rule` definitionally reduces to the per-rule type
        // body, so each branch is `apply (K_<Name>_sound).`.  An
        // auditor running `Print Assumptions kernel_soundness.` sees
        // every IOU axiom (open or discharged-by-framework) as the
        // per-build trust extension.
        let mut out = String::new();

        // 1. The per-rule type-body dispatch, materialised as
        //    `Soundness : KernelRule -> Prop`.
        out.push_str(
            "(* `Soundness rule` is the propositional shape of the per-rule    *)\n\
             (* lemma `K_<rule>_sound`.  Each branch quotes the rule's typing  *)\n\
             (* judgement; `kernel_soundness` aggregates them.                 *)\n",
        );
        out.push_str("Definition Soundness (rule : KernelRule) : Prop :=\n  match rule with\n");
        for r in rules {
            let body = match rule_signature_coq(&r.rule_name).and_then(parse_coq_signature) {
                Some(parts) => parts.type_body,
                None => "side_conditions_hold -> True".to_string(),
            };
            // Reflow body to one line — Coq is whitespace-flexible
            // inside forall.  The inline form keeps the match block
            // dense and readable.
            let one_line = body.replace("\n    ", " ").replace("\n  ", " ").replace('\n', " ");
            out.push_str(&format!(
                "  | {} => {}\n",
                r.rule_name, one_line.trim(),
            ));
        }
        out.push_str("  end.\n");

        // 2. The aggregate soundness theorem — case-analyses on
        //    `KernelRule` and dispatches each branch to its per-rule lemma.
        out.push_str(
            "\n(* **Kernel soundness** — case-analyses on `KernelRule` and *)\n\
             (* dispatches each branch to its `K_<rule>_sound` lemma.    *)\n",
        );
        // Each per-rule branch needs `simpl` BEFORE `apply` so Coq
        // reduces `Soundness K_<Name>` to the matching `match`-arm
        // body — without this, `apply (K_<Name>_sound)` fails to
        // unify against the un-reduced `Soundness K_<Name>` goal
        // (the historical drift surfaced when the IOU registry
        // emptied: under `Admitted.` lemmas the issue was masked).
        out.push_str(
            "Theorem kernel_soundness : forall rule : KernelRule, Soundness rule.\n\
             Proof.\n  \
             intro rule. destruct rule.\n",
        );
        for r in rules {
            out.push_str(&format!("  - simpl; apply ({}).\n", r.lemma_name));
        }
        out.push_str("Qed.\n");

        out
    }

    fn render_postscript(&self) -> String {
        String::from("(* End of kernel_soundness.v *)")
    }
}

// ============================================================================
// Per-rule IOU axiom declarations (8 axioms — one per with-IOU rule).
//
// Discharged so far (each removed an axiom):
//   * K_Quot_Elim       — structural premises mirroring K_Quot_Form/K_Quot_Intro.
//   * K_Elim            — same template, with per-constructor case-typing
//                         remaining the kernel's input contract.
//   * K_Universe_Ascent — collapses onto T_univ for u32-bounded universes.
//   * K_Refine          — predicate typed at Pi x base (Universe 0).
//   * K_Refine_Omega    — same shape; finite-universe bound makes the
//                         ordinal-modal-depth-bound vacuous.
// ============================================================================

/// The IOU axiom block as a `&'static str`, generated once on first
/// access from `iou_axiom_specs()` via
/// [`crate::soundness::render_iou_axioms_coq`].  Source-of-truth is
/// the spec registry in `mod.rs`; this function is a cached
/// renderer.
pub(crate) fn iou_axioms_coq() -> &'static str {
    use std::sync::OnceLock;
    static CACHE: OnceLock<String> = OnceLock::new();
    CACHE
        .get_or_init(crate::soundness::render_iou_axioms_coq)
        .as_str()
}


// ============================================================================
// The Typing inductive — 38 constructors covering every kernel rule.
// ============================================================================

const TYPING_INDUCTIVE_COQ: &str = "\
(* The reflective typing relation. 38 constructors. *)\n\
Reserved Notation \"Gamma '|-' t ':' T\" (at level 90, t at next level).\n\
Inductive Typing : Ctx -> CoreTerm -> CoreTerm -> Prop :=\n  \
  (* ===== Structural fragment (9) ===== *)\n  \
  | T_var :\n      \
      forall (Gamma : Ctx) (x : string) (T : CoreTerm),\n        \
        In (x, T) Gamma ->\n        \
        Typing Gamma (Var x) T\n  \
  | T_univ :\n      \
      forall (Gamma : Ctx) (i : nat),\n        \
        Typing Gamma (Universe i) (Universe (S i))\n  \
  | T_pi :\n      \
      forall (Gamma : Ctx) (x : string) (A B : CoreTerm) (i : nat),\n        \
        Typing Gamma A (Universe i) ->\n        \
        Typing ((x, A) :: Gamma) B (Universe i) ->\n        \
        Typing Gamma (Pi x A B) (Universe i)\n  \
  | T_lam :\n      \
      forall (Gamma : Ctx) (x : string) (A b B : CoreTerm) (i : nat),\n        \
        Typing Gamma A (Universe i) ->\n        \
        Typing ((x, A) :: Gamma) b B ->\n        \
        Typing Gamma (Lam x A b) (Pi x A B)\n  \
  | T_app :\n      \
      forall (Gamma : Ctx) (f a : CoreTerm) (x : string) (A B : CoreTerm),\n        \
        Typing Gamma f (Pi x A B) ->\n        \
        Typing Gamma a A ->\n        \
        Typing Gamma (App f a) (subst x a B)\n  \
  | T_sigma :\n      \
      forall (Gamma : Ctx) (x : string) (A B : CoreTerm) (i : nat),\n        \
        Typing Gamma A (Universe i) ->\n        \
        Typing ((x, A) :: Gamma) B (Universe i) ->\n        \
        Typing Gamma (Sigma x A B) (Universe i)\n  \
  | T_pair :\n      \
      forall (Gamma : Ctx) (x : string) (A B a b : CoreTerm),\n        \
        Typing Gamma a A ->\n        \
        Typing Gamma b (subst x a B) ->\n        \
        Typing Gamma (Pair a b) (Sigma x A B)\n  \
  | T_fst :\n      \
      forall (Gamma : Ctx) (p : CoreTerm) (x : string) (A B : CoreTerm),\n        \
        Typing Gamma p (Sigma x A B) ->\n        \
        Typing Gamma (Fst p) A\n  \
  | T_snd :\n      \
      forall (Gamma : Ctx) (p : CoreTerm) (x : string) (A B : CoreTerm),\n        \
        Typing Gamma p (Sigma x A B) ->\n        \
        Typing Gamma (Snd p) (subst x (Fst p) B)\n  \
  (* ===== Cubical (6) ===== *)\n  \
  | T_path_ty :\n      \
      forall (Gamma : Ctx) (A a b : CoreTerm) (i : nat),\n        \
        Typing Gamma A (Universe i) ->\n        \
        Typing Gamma a A ->\n        \
        Typing Gamma b A ->\n        \
        Typing Gamma (PathTy A a b) (Universe i)\n  \
  | T_refl :\n      \
      forall (Gamma : Ctx) (a A : CoreTerm),\n        \
        Typing Gamma a A ->\n        \
        Typing Gamma (Refl a) (PathTy A a a)\n  \
  | T_path_over :\n      \
      forall (Gamma : Ctx) (motive p a b A : CoreTerm) (x : string) (i : nat),\n        \
        Typing Gamma A (Universe i) ->\n        \
        Typing Gamma motive (Pi x A (Universe i)) ->\n        \
        Typing Gamma (PathOver motive p a b) (Universe i)\n  \
  | T_hcomp :\n      \
      forall (Gamma : Ctx) (phi walls base T : CoreTerm) (i : nat),\n        \
        Typing Gamma T (Universe i) ->\n        \
        Typing Gamma base T ->\n        \
        Typing Gamma (HComp phi walls base) T\n  \
  | T_transp :\n      \
      forall (Gamma : Ctx) (path regular value target : CoreTerm) (i : nat),\n        \
        Typing Gamma target (Universe i) ->\n        \
        Typing Gamma (Transp path regular value) target\n  \
  | T_glue :\n      \
      forall (Gamma : Ctx) (carrier phi fiber equiv : CoreTerm) (i : nat),\n        \
        Typing Gamma carrier (Universe i) ->\n        \
        Typing Gamma (Glue carrier phi fiber equiv) (Universe i)\n  \
  (* ===== Refinement (4) ===== *)\n  \
  | T_refine_erase :\n      \
      forall (Gamma : Ctx) (a base : CoreTerm) (x : string) (predicate : CoreTerm),\n        \
        Typing Gamma a (Refine base x predicate) ->\n        \
        Typing Gamma a base\n  \
  | T_refine :\n      \
      forall (Gamma : Ctx) (base predicate : CoreTerm) (x : string) (i : nat),\n        \
        Typing Gamma base (Universe i) ->\n        \
        Typing Gamma predicate (Pi x base (Universe 0)) ->\n        \
        Typing Gamma (Refine base x predicate) (Universe i)\n  \
  | T_refine_omega :\n      \
      forall (Gamma : Ctx) (base predicate : CoreTerm) (x : string) (i : nat),\n        \
        Typing Gamma base (Universe i) ->\n        \
        Typing Gamma predicate (Pi x base (Universe 0)) ->\n        \
        Typing Gamma (Refine base x predicate) (Universe i)\n  \
  | T_refine_intro :\n      \
      forall (Gamma : Ctx) (a base predicate : CoreTerm) (x : string) (i : nat),\n        \
        Typing Gamma a base ->\n        \
        Typing Gamma base (Universe i) ->\n        \
        Typing Gamma predicate (Pi x base (Universe 0)) ->\n        \
        Typing Gamma a (Refine base x predicate)\n  \
  (* ===== Quotient (3) ===== *)\n  \
  | T_quot_form :\n      \
      forall (Gamma : Ctx) (base equiv : CoreTerm) (i : nat),\n        \
        Typing Gamma base (Universe i) ->\n        \
        Typing Gamma (Quotient base equiv) (Universe i)\n  \
  | T_quot_intro :\n      \
      forall (Gamma : Ctx) (value base equiv : CoreTerm),\n        \
        Typing Gamma value base ->\n        \
        Typing Gamma (QuotIntro value base equiv) (Quotient base equiv)\n  \
  | T_quot_elim :\n      \
      forall (Gamma : Ctx) (scrutinee motive case_fn base equiv : CoreTerm) (i : nat),\n        \
        Typing Gamma scrutinee (Quotient base equiv) ->\n        \
        Typing Gamma motive (Pi \"x\" base (Universe i)) ->\n        \
        Typing Gamma case_fn (Pi \"x\" base (App motive (Var \"x\"))) ->\n        \
        Typing Gamma (QuotElim scrutinee motive case_fn) (App motive scrutinee)\n  \
  (* ===== Inductive (3) ===== *)\n  \
  | T_inductive :\n      \
      forall (Gamma : Ctx) (path : string) (args : list CoreTerm) (i : nat),\n        \
        Typing Gamma (Inductive_ path args) (Universe i)\n  \
  | T_pos :\n      \
      forall (Gamma : Ctx) (t T : CoreTerm),\n        \
        side_conditions_hold ->\n        \
        Typing Gamma t T -> Typing Gamma t T\n  \
  | T_elim :\n      \
      forall (Gamma : Ctx) (scrutinee motive scrutinee_ty : CoreTerm) (cases : list CoreTerm) (i : nat),\n        \
        Typing Gamma scrutinee scrutinee_ty ->\n        \
        Typing Gamma motive (Pi \"x\" scrutinee_ty (Universe i)) ->\n        \
        Typing Gamma (Elim scrutinee motive cases) (App motive scrutinee)\n  \
  (* ===== SmtAxiom (2) ===== *)\n  \
  | T_smt :\n      \
      forall (Gamma : Ctx) (solver_tag : string) (T : CoreTerm) (i : nat),\n        \
        Typing Gamma T (Universe i) ->\n        \
        Typing Gamma (SmtProof solver_tag) T\n  \
  | T_fwax :\n      \
      forall (Gamma : Ctx) (name : string) (ty : CoreTerm) (framework : string),\n        \
        Typing Gamma (Axiom_ name ty framework) ty\n  \
  (* ===== Diakrisis (11) ===== *)\n  \
  | T_eps_mu :\n      \
      forall (Gamma : Ctx) (articulation enactment ty : CoreTerm),\n        \
        Typing Gamma enactment ty ->\n        \
        Typing Gamma articulation ty\n  \
  | T_universe_ascent :\n      \
      forall (Gamma : Ctx) (i : nat),\n        \
        Typing Gamma (Universe i) (Universe (S i))\n  \
  | T_round_trip :\n      \
      forall (Gamma : Ctx) (term recovered : CoreTerm) (i : nat),\n        \
        Typing Gamma recovered (Universe i) ->\n        \
        Typing Gamma term recovered\n  \
  | T_epsilon_of :\n      \
      forall (Gamma : Ctx) (articulation result : CoreTerm),\n        \
        Typing Gamma articulation result ->\n        \
        Typing Gamma (EpsilonOf articulation) result\n  \
  | T_alpha_of :\n      \
      forall (Gamma : Ctx) (enactment result : CoreTerm),\n        \
        Typing Gamma enactment result ->\n        \
        Typing Gamma (AlphaOf enactment) result\n  \
  | T_modal_box :\n      \
      forall (Gamma : Ctx) (inner T : CoreTerm),\n        \
        Typing Gamma inner T ->\n        \
        Typing Gamma (ModalBox inner) T\n  \
  | T_modal_diamond :\n      \
      forall (Gamma : Ctx) (inner T : CoreTerm),\n        \
        Typing Gamma inner T ->\n        \
        Typing Gamma (ModalDiamond inner) T\n  \
  | T_modal_big_and :\n      \
      forall (Gamma : Ctx) (components : list CoreTerm) (result : CoreTerm),\n        \
        Typing Gamma (ModalBigAnd components) result\n  \
  | T_shape :\n      \
      forall (Gamma : Ctx) (inner T : CoreTerm),\n        \
        Typing Gamma inner T ->\n        \
        Typing Gamma (Shape inner) T\n  \
  | T_flat :\n      \
      forall (Gamma : Ctx) (inner T : CoreTerm),\n        \
        Typing Gamma inner T ->\n        \
        Typing Gamma (Flat inner) T\n  \
  | T_sharp :\n      \
      forall (Gamma : Ctx) (inner T : CoreTerm),\n        \
        Typing Gamma inner T ->\n        \
        Typing Gamma (Sharp inner) T\n\n  \
  where \"Gamma '|-' t ':' T\" := (Typing Gamma t T).";

// ============================================================================
// Per-rule lemma signature lookup — dispatches all 38 rules.
// ============================================================================

/// Parsed slices of a per-rule Coq signature string.
///
/// `rule_signature_coq` returns text of shape
/// `Lemma <name> :\n  <TYPE>.\nProof. exact <WITNESS>. Qed.` — one
/// for each rule with an explicit shape-faithful lemma.  The main-
/// theorem renderer uses the `<TYPE>` slice to define
/// `Soundness : KernelRule -> Prop`; the per-rule renderer uses the
/// `<WITNESS>` slice (when present) as the constructor name to
/// emit `Proof. exact <WITNESS>. Qed.`. When the proof block uses
/// a multi-tactic script that doesn't reduce to a single
/// `exact <name>.`, `witness` is `None` and the per-rule renderer
/// falls back to the full tactic body from the rule's recorded
/// `coq_tactics`.
struct CoqSigParts {
    type_body: String,
    witness: Option<String>,
}

fn parse_coq_signature(sig: String) -> Option<CoqSigParts> {
    // Format: `Lemma <name> :\n  <TYPE>.\nProof. ... Qed.` — split on
    // the period that terminates the lemma's type declaration.
    let (head, proof) = sig.split_once(".\n")?;
    let (_lemma_decl, type_body) = head.split_once(" :\n")?;
    Some(CoqSigParts {
        type_body: type_body.trim().to_string(),
        witness: extract_coq_witness(proof.trim()),
    })
}

/// Extract the Typing-constructor witness from a Coq proof block.
///
/// Recognised single-tactic shape: `Proof. exact <name>. Qed.`
/// returns `Some("<name>")`. Anything else (multi-tactic scripts
/// like `Proof. intros; apply T_quot_elim with (...); assumption.
/// Qed.`) returns `None` so the per-rule renderer emits the full
/// `coq_tactics` body verbatim instead of mangling it through
/// `Proof. exact <whole-block>. Qed.` (the historical drift).
fn extract_coq_witness(proof_block: &str) -> Option<String> {
    let rest = proof_block.strip_prefix("Proof. exact ")?;
    let (witness, after) = rest.split_once('.')?;
    let witness = witness.trim();
    // Reject multi-token witnesses (would only be valid as a
    // Gallina expression, not as a constructor name; `Proof.
    // exact <expr>. Qed.` with non-trivial `<expr>` should still
    // route through the constructor-witness path only when the
    // `<expr>` is a single atomic identifier).
    if witness.is_empty() || witness.contains(|c: char| c.is_whitespace()) {
        return None;
    }
    // Also reject anything that has the trailing tactic-script
    // shape after the first period — `intros; apply X; …` would
    // have left content after the split that's not just `\n` /
    // `Qed.` / whitespace.
    let trailing = after.trim_start();
    if !trailing.starts_with("Qed.") && !trailing.is_empty() {
        return None;
    }
    Some(witness.to_string())
}

fn rule_signature_coq(rule_name: &str) -> Option<String> {
    let body = match rule_name {
        // ===== Structural (9) =====
        "K_Var" => Some(
            "Lemma K_Var_sound :\n  \
              forall (Gamma : Ctx) (x : string) (T : CoreTerm),\n    \
                In (x, T) Gamma -> Typing Gamma (Var x) T.\n\
              Proof. exact T_var. Qed.",
        ),
        "K_Univ" => Some(
            "Lemma K_Univ_sound :\n  \
              forall (Gamma : Ctx) (i : nat),\n    \
                Typing Gamma (Universe i) (Universe (S i)).\n\
              Proof. exact T_univ. Qed.",
        ),
        "K_Pi_Form" => Some(
            "Lemma K_Pi_Form_sound :\n  \
              forall (Gamma : Ctx) (x : string) (A B : CoreTerm) (i : nat),\n    \
                Typing Gamma A (Universe i) ->\n    \
                Typing ((x, A) :: Gamma) B (Universe i) ->\n    \
                Typing Gamma (Pi x A B) (Universe i).\n\
              Proof. exact T_pi. Qed.",
        ),
        "K_Lam_Intro" => Some(
            "Lemma K_Lam_Intro_sound :\n  \
              forall (Gamma : Ctx) (x : string) (A b B : CoreTerm) (i : nat),\n    \
                Typing Gamma A (Universe i) ->\n    \
                Typing ((x, A) :: Gamma) b B ->\n    \
                Typing Gamma (Lam x A b) (Pi x A B).\n\
              Proof. exact T_lam. Qed.",
        ),
        "K_App_Elim" => Some(
            "Lemma K_App_Elim_sound :\n  \
              forall (Gamma : Ctx) (f a : CoreTerm) (x : string) (A B : CoreTerm),\n    \
                Typing Gamma f (Pi x A B) -> Typing Gamma a A ->\n    \
                Typing Gamma (App f a) (subst x a B).\n\
              Proof. exact T_app. Qed.",
        ),
        "K_Sigma_Form" => Some(
            "Lemma K_Sigma_Form_sound :\n  \
              forall (Gamma : Ctx) (x : string) (A B : CoreTerm) (i : nat),\n    \
                Typing Gamma A (Universe i) ->\n    \
                Typing ((x, A) :: Gamma) B (Universe i) ->\n    \
                Typing Gamma (Sigma x A B) (Universe i).\n\
              Proof. exact T_sigma. Qed.",
        ),
        "K_Pair_Intro" => Some(
            "Lemma K_Pair_Intro_sound :\n  \
              forall (Gamma : Ctx) (x : string) (A B a b : CoreTerm),\n    \
                Typing Gamma a A -> Typing Gamma b (subst x a B) ->\n    \
                Typing Gamma (Pair a b) (Sigma x A B).\n\
              Proof. exact T_pair. Qed.",
        ),
        "K_Fst_Elim" => Some(
            "Lemma K_Fst_Elim_sound :\n  \
              forall (Gamma : Ctx) (p : CoreTerm) (x : string) (A B : CoreTerm),\n    \
                Typing Gamma p (Sigma x A B) -> Typing Gamma (Fst p) A.\n\
              Proof. exact T_fst. Qed.",
        ),
        "K_Snd_Elim" => Some(
            "Lemma K_Snd_Elim_sound :\n  \
              forall (Gamma : Ctx) (p : CoreTerm) (x : string) (A B : CoreTerm),\n    \
                Typing Gamma p (Sigma x A B) ->\n    \
                Typing Gamma (Snd p) (subst x (Fst p) B).\n\
              Proof. exact T_snd. Qed.",
        ),
        // ===== Cubical (6) =====
        "K_Path_Ty_Form" => Some(
            "Lemma K_Path_Ty_Form_sound :\n  \
              forall (Gamma : Ctx) (A a b : CoreTerm) (i : nat),\n    \
                Typing Gamma A (Universe i) -> Typing Gamma a A -> Typing Gamma b A ->\n    \
                Typing Gamma (PathTy A a b) (Universe i).\n\
              Proof. exact T_path_ty. Qed.",
        ),
        "K_Refl_Intro" => Some(
            "Lemma K_Refl_Intro_sound :\n  \
              forall (Gamma : Ctx) (a A : CoreTerm),\n    \
                Typing Gamma a A -> Typing Gamma (Refl a) (PathTy A a a).\n\
              Proof. exact T_refl. Qed.",
        ),
        "K_Path_Over_Form" => Some(
            "Lemma K_Path_Over_Form_sound :\n  \
              forall (Gamma : Ctx) (motive p a b A : CoreTerm) (x : string) (i : nat),\n    \
                Typing Gamma A (Universe i) ->\n    \
                Typing Gamma motive (Pi x A (Universe i)) ->\n    \
                Typing Gamma (PathOver motive p a b) (Universe i).\n\
              Proof. exact T_path_over. Qed.",
        ),
        "K_HComp" => Some(
            "Lemma K_HComp_sound :\n  \
              forall (Gamma : Ctx) (phi walls base T : CoreTerm) (i : nat),\n    \
                Typing Gamma T (Universe i) ->\n    \
                Typing Gamma base T ->\n    \
                Typing Gamma (HComp phi walls base) T.\n\
              Proof. exact T_hcomp. Qed.",
        ),
        "K_Transp" => Some(
            "Lemma K_Transp_sound :\n  \
              forall (Gamma : Ctx) (path regular value target : CoreTerm) (i : nat),\n    \
                Typing Gamma target (Universe i) ->\n    \
                Typing Gamma (Transp path regular value) target.\n\
              Proof. exact T_transp. Qed.",
        ),
        "K_Glue" => Some(
            "Lemma K_Glue_sound :\n  \
              forall (Gamma : Ctx) (carrier phi fiber equiv : CoreTerm) (i : nat),\n    \
                Typing Gamma carrier (Universe i) ->\n    \
                Typing Gamma (Glue carrier phi fiber equiv) (Universe i).\n\
              Proof. exact T_glue. Qed.",
        ),
        // ===== Refinement (4) =====
        "K_Refine_Erase" => Some(
            "Lemma K_Refine_Erase_sound :\n  \
              forall (Gamma : Ctx) (a base : CoreTerm) (x : string) (predicate : CoreTerm),\n    \
                Typing Gamma a (Refine base x predicate) -> Typing Gamma a base.\n\
              Proof. exact T_refine_erase. Qed.",
        ),
        "K_Refine" => Some(
            "Lemma K_Refine_sound :\n  \
              forall (Gamma : Ctx) (base predicate : CoreTerm) (x : string) (i : nat),\n    \
                Typing Gamma base (Universe i) ->\n    \
                Typing Gamma predicate (Pi x base (Universe 0)) ->\n    \
                Typing Gamma (Refine base x predicate) (Universe i).\n\
              Proof. exact T_refine. Qed.",
        ),
        "K_Refine_Omega" => Some(
            "Lemma K_Refine_Omega_sound :\n  \
              forall (Gamma : Ctx) (base predicate : CoreTerm) (x : string) (i : nat),\n    \
                Typing Gamma base (Universe i) ->\n    \
                Typing Gamma predicate (Pi x base (Universe 0)) ->\n    \
                Typing Gamma (Refine base x predicate) (Universe i).\n\
              Proof. exact T_refine_omega. Qed.",
        ),
        "K_Refine_Intro" => Some(
            "Lemma K_Refine_Intro_sound :\n  \
              forall (Gamma : Ctx) (a base predicate : CoreTerm) (x : string) (i : nat),\n    \
                Typing Gamma a base ->\n    \
                Typing Gamma base (Universe i) ->\n    \
                Typing Gamma predicate (Pi x base (Universe 0)) ->\n    \
                Typing Gamma a (Refine base x predicate).\n\
              Proof. exact T_refine_intro. Qed.",
        ),
        // ===== Quotient (3) =====
        "K_Quot_Form" => Some(
            "Lemma K_Quot_Form_sound :\n  \
              forall (Gamma : Ctx) (base equiv : CoreTerm) (i : nat),\n    \
                Typing Gamma base (Universe i) -> Typing Gamma (Quotient base equiv) (Universe i).\n\
              Proof. exact T_quot_form. Qed.",
        ),
        "K_Quot_Intro" => Some(
            "Lemma K_Quot_Intro_sound :\n  \
              forall (Gamma : Ctx) (value base equiv : CoreTerm),\n    \
                Typing Gamma value base ->\n    \
                Typing Gamma (QuotIntro value base equiv) (Quotient base equiv).\n\
              Proof. exact T_quot_intro. Qed.",
        ),
        "K_Quot_Elim" => Some(
            "Lemma K_Quot_Elim_sound :\n  \
              forall (Gamma : Ctx) (scrutinee motive case_fn base equiv : CoreTerm) (i : nat),\n    \
                Typing Gamma scrutinee (Quotient base equiv) ->\n    \
                Typing Gamma motive (Pi \"x\"%string base (Universe i)) ->\n    \
                Typing Gamma case_fn (Pi \"x\"%string base (App motive (Var \"x\"%string))) ->\n    \
                Typing Gamma (QuotElim scrutinee motive case_fn) (App motive scrutinee).\n\
              Proof. intros; apply T_quot_elim with (base := base) (equiv := equiv) (i := i); assumption. Qed.",
        ),
        // ===== Inductive (3) =====
        "K_Inductive" => Some(
            "Lemma K_Inductive_sound :\n  \
              forall (Gamma : Ctx) (path : string) (args : list CoreTerm) (i : nat),\n    \
                Typing Gamma (Inductive_ path args) (Universe i).\n\
              Proof. exact T_inductive. Qed.",
        ),
        "K_Pos" => Some(
            "Lemma K_Pos_sound : side_conditions_hold -> True.\n\
             Proof. intros _. trivial. Qed.",
        ),
        "K_Elim" => Some(
            "Lemma K_Elim_sound :\n  \
              forall (Gamma : Ctx) (scrutinee motive scrutinee_ty : CoreTerm) (cases : list CoreTerm) (i : nat),\n    \
                Typing Gamma scrutinee scrutinee_ty ->\n    \
                Typing Gamma motive (Pi \"x\"%string scrutinee_ty (Universe i)) ->\n    \
                Typing Gamma (Elim scrutinee motive cases) (App motive scrutinee).\n\
              Proof. intros; apply T_elim with (scrutinee_ty := scrutinee_ty) (i := i); assumption. Qed.",
        ),
        // ===== SmtAxiom (2) =====
        "K_Smt" => Some(
            "Lemma K_Smt_sound :\n  \
              forall (Gamma : Ctx) (solver_tag : string) (T : CoreTerm) (i : nat),\n    \
                Typing Gamma T (Universe i) ->\n    \
                Typing Gamma (SmtProof solver_tag) T.\n\
              Proof. exact T_smt. Qed.",
        ),
        "K_FwAx" => Some(
            "Lemma K_FwAx_sound :\n  \
              forall (Gamma : Ctx) (name : string) (ty : CoreTerm) (framework : string),\n    \
                Typing Gamma (Axiom_ name ty framework) ty.\n\
              Proof. exact T_fwax. Qed.",
        ),
        // ===== Diakrisis (11) =====
        "K_Eps_Mu" => Some(
            "Lemma K_Eps_Mu_sound :\n  \
              forall (Gamma : Ctx) (articulation enactment ty : CoreTerm),\n    \
                Typing Gamma enactment ty ->\n    \
                Typing Gamma articulation ty.\n\
              Proof. exact T_eps_mu. Qed.",
        ),
        "K_Universe_Ascent" => Some(
            "Lemma K_Universe_Ascent_sound :\n  \
              forall (Gamma : Ctx) (i : nat),\n    \
                Typing Gamma (Universe i) (Universe (S i)).\n\
              Proof. exact T_universe_ascent. Qed.",
        ),
        "K_Round_Trip" => Some(
            "Lemma K_Round_Trip_sound :\n  \
              forall (Gamma : Ctx) (term recovered : CoreTerm) (i : nat),\n    \
                Typing Gamma recovered (Universe i) ->\n    \
                Typing Gamma term recovered.\n\
              Proof. exact T_round_trip. Qed.",
        ),
        "K_Epsilon_Of" => Some(
            "Lemma K_Epsilon_Of_sound :\n  \
              forall (Gamma : Ctx) (articulation result : CoreTerm),\n    \
                Typing Gamma articulation result ->\n    \
                Typing Gamma (EpsilonOf articulation) result.\n\
              Proof. exact T_epsilon_of. Qed.",
        ),
        "K_Alpha_Of" => Some(
            "Lemma K_Alpha_Of_sound :\n  \
              forall (Gamma : Ctx) (enactment result : CoreTerm),\n    \
                Typing Gamma enactment result ->\n    \
                Typing Gamma (AlphaOf enactment) result.\n\
              Proof. exact T_alpha_of. Qed.",
        ),
        "K_Modal_Box" => Some(
            "Lemma K_Modal_Box_sound :\n  \
              forall (Gamma : Ctx) (inner T : CoreTerm),\n    \
                Typing Gamma inner T -> Typing Gamma (ModalBox inner) T.\n\
              Proof. exact T_modal_box. Qed.",
        ),
        "K_Modal_Diamond" => Some(
            "Lemma K_Modal_Diamond_sound :\n  \
              forall (Gamma : Ctx) (inner T : CoreTerm),\n    \
                Typing Gamma inner T -> Typing Gamma (ModalDiamond inner) T.\n\
              Proof. exact T_modal_diamond. Qed.",
        ),
        "K_Modal_Big_And" => Some(
            "Lemma K_Modal_Big_And_sound :\n  \
              forall (Gamma : Ctx) (components : list CoreTerm) (result : CoreTerm),\n    \
                Typing Gamma (ModalBigAnd components) result.\n\
              Proof. exact T_modal_big_and. Qed.",
        ),
        "K_Shape" => Some(
            "Lemma K_Shape_sound :\n  \
              forall (Gamma : Ctx) (inner T : CoreTerm),\n    \
                Typing Gamma inner T -> Typing Gamma (Shape inner) T.\n\
              Proof. exact T_shape. Qed.",
        ),
        "K_Flat" => Some(
            "Lemma K_Flat_sound :\n  \
              forall (Gamma : Ctx) (inner T : CoreTerm),\n    \
                Typing Gamma inner T -> Typing Gamma (Flat inner) T.\n\
              Proof. exact T_flat. Qed.",
        ),
        "K_Sharp" => Some(
            "Lemma K_Sharp_sound :\n  \
              forall (Gamma : Ctx) (inner T : CoreTerm),\n    \
                Typing Gamma inner T -> Typing Gamma (Sharp inner) T.\n\
              Proof. exact T_sharp. Qed.",
        ),
        _ => None,
    };
    body.map(|s| s.to_string())
}

/// Drift-detection helper used by `tests.rs` and the audit gate.
pub fn every_rule_has_coq_signature(rules: &[RuleSpec]) -> bool {
    rules.iter().all(|r| rule_signature_coq(&r.rule_name).is_some())
}
