//! Tests for the kernel-soundness cross-export pipeline.
//!
//! Pin coverage:
//!   - The canonical rule list has exactly 35 entries.
//!   - The 4 structurally-proved lemmas (K-Var, K-Univ, K-FwAx, K-Pos)
//!     are marked `Proved`; everything else is `Admitted` with a
//!     non-empty reason.
//!   - Coq + Lean backends emit non-empty output for every section
//!     and every rule; Admitted lemmas carry their reason in a
//!     comment alongside the `Admitted.` / `sorry`.
//!   - The drift check fires when the rule list differs from
//!     `EXPECTED_KERNEL_RULE_COUNT`.

use super::coq::CoqBackend;
use super::lean::LeanBackend;
use super::{
    EXPECTED_KERNEL_RULE_COUNT, LemmaStatus, RuleSpec,
    SoundnessBackend, SoundnessExporter, canonical_rules,
};

#[test]
fn canonical_rules_has_expected_count() {
    let rules = canonical_rules();
    assert_eq!(
        rules.len(),
        EXPECTED_KERNEL_RULE_COUNT,
        "canonical_rules() should produce exactly {} entries",
        EXPECTED_KERNEL_RULE_COUNT,
    );
}

#[test]
fn proved_lemma_set_is_exactly_four() {
    let rules = canonical_rules();
    let proved: Vec<&str> = rules
        .iter()
        .filter(|r| r.status.is_proved())
        .map(|r| r.rule_name.as_str())
        .collect();

    assert_eq!(
        proved.len(),
        4,
        "expected 4 structurally-proved lemmas, got {}: {:?}",
        proved.len(),
        proved,
    );

    assert!(proved.contains(&"K_Var"), "K_Var must be proved");
    assert!(proved.contains(&"K_Univ"), "K_Univ must be proved");
    assert!(proved.contains(&"K_FwAx"), "K_FwAx must be proved");
    assert!(proved.contains(&"K_Pos"), "K_Pos must be proved");
}

#[test]
fn every_admitted_lemma_has_non_empty_reason() {
    let rules = canonical_rules();
    for r in &rules {
        if let LemmaStatus::Admitted { reason } = &r.status {
            assert!(
                !reason.trim().is_empty(),
                "rule {} is admitted but reason is empty — admits must be \
                 audit-able IOUs, not silent placeholders",
                r.rule_name,
            );
        }
    }
}

#[test]
fn every_discharged_lemma_has_non_empty_citation() {
    let rules = canonical_rules();
    for r in &rules {
        if let LemmaStatus::DischargedByFramework { lemma_path, framework, citation } = &r.status {
            assert!(
                !lemma_path.trim().is_empty(),
                "rule {} discharged-by-framework but lemma_path is empty",
                r.rule_name,
            );
            assert!(
                !framework.trim().is_empty(),
                "rule {} discharged-by-framework but framework is empty",
                r.rule_name,
            );
            assert!(
                !citation.trim().is_empty(),
                "rule {} discharged-by-framework but citation is empty — \
                 the audit gate's trust-extension report needs the upstream path",
                r.rule_name,
            );
        }
    }
}

#[test]
fn discharged_count_reflects_phase_1a() {
    let rules = canonical_rules();
    let exporter = SoundnessExporter::new();
    let _ = rules.len();
    // Post-#155 Phase-1A: at least 7 rules discharged by framework
    // citation (K_Pi_Form, K_Lam_Intro, K_App_Elim, K_Sigma_Form,
    // K_Pair_Intro, K_Fst_Elim, K_Snd_Elim).  This count is a floor;
    // future Phase-1A advances will increase it.
    assert!(
        exporter.discharged_by_framework_count() >= 7,
        "expected at least 7 framework-discharged rules post-#155 Phase-1A, got {}",
        exporter.discharged_by_framework_count(),
    );
}

#[test]
fn rule_names_are_unique() {
    let rules = canonical_rules();
    let mut seen = std::collections::HashSet::new();
    for r in &rules {
        assert!(
            seen.insert(r.rule_name.clone()),
            "duplicate rule name: {}",
            r.rule_name,
        );
    }
}

#[test]
fn lemma_names_match_rule_names_with_sound_suffix() {
    for r in &canonical_rules() {
        assert_eq!(
            r.lemma_name,
            format!("{}_sound", r.rule_name),
            "lemma_name should be `{}_sound`",
            r.rule_name,
        );
    }
}

#[test]
fn coq_backend_emits_full_file() {
    let exporter = SoundnessExporter::new();
    let coq = CoqBackend::new();
    let output = exporter.emit(&coq);

    // Preamble
    assert!(output.contains("kernel_soundness.v"));
    assert!(output.contains("GENERATED by"));
    // Inductives
    assert!(output.contains("Inductive CoreTerm"));
    assert!(output.contains("Inductive CoreType"));
    assert!(output.contains("Inductive KernelRule"));
    // All 35 rules appear as constructors of KernelRule and as lemmas
    for r in exporter.rules() {
        assert!(
            output.contains(&r.rule_name),
            "Coq output missing rule {}",
            r.rule_name,
        );
        assert!(
            output.contains(&r.lemma_name),
            "Coq output missing lemma {}",
            r.lemma_name,
        );
    }
    // Top theorem
    assert!(output.contains("Theorem kernel_soundness"));
    // Postscript
    assert!(output.contains("End of kernel_soundness.v"));
    // Filename matches
    assert_eq!(coq.output_filename(), "kernel_soundness.v");
}

#[test]
fn coq_backend_renders_admitted_with_reason_comment() {
    let exporter = SoundnessExporter::new();
    let coq = CoqBackend::new();
    let output = exporter.emit(&coq);

    // Pick a discharged lemma and confirm `Admitted.` plus the
    // citation appear.  K_Pi_Form is now discharged-by-framework
    // citing the substitution-lemma in mathlib4.
    assert!(output.contains("Admitted."));
    assert!(
        output.contains("substitution-lemma") || output.contains("Substitution"),
        "Coq emission must carry the K_Pi_Form discharge citation",
    );
}

#[test]
fn coq_backend_renders_proved_lemmas_with_qed() {
    let exporter = SoundnessExporter::new();
    let coq = CoqBackend::new();
    let output = exporter.emit(&coq);

    // Proved lemmas end in Qed., not Admitted.
    let var_lemma_pos = output
        .find("Lemma K_Var_sound")
        .expect("K_Var_sound lemma must be present");
    let next_qed = output[var_lemma_pos..]
        .find("Qed.")
        .expect("K_Var_sound's proof must end in Qed.");
    let next_admitted = output[var_lemma_pos..].find("Admitted.");
    if let Some(adm) = next_admitted {
        assert!(
            next_qed < adm,
            "K_Var_sound must end in Qed. before any later Admitted.",
        );
    }
}

#[test]
fn lean_backend_emits_full_file() {
    let exporter = SoundnessExporter::new();
    let lean = LeanBackend::new();
    let output = exporter.emit(&lean);

    assert!(output.contains("KernelSoundness.lean"));
    assert!(output.contains("namespace KernelSoundness"));
    assert!(output.contains("inductive CoreTerm"));
    assert!(output.contains("inductive CoreType"));
    assert!(output.contains("inductive KernelRule"));
    for r in exporter.rules() {
        assert!(
            output.contains(&r.rule_name),
            "Lean output missing rule {}",
            r.rule_name,
        );
        assert!(
            output.contains(&r.lemma_name),
            "Lean output missing lemma {}",
            r.lemma_name,
        );
    }
    assert!(output.contains("theorem kernel_soundness"));
    assert!(output.contains("end KernelSoundness"));
    assert_eq!(lean.output_filename(), "KernelSoundness.lean");
}

#[test]
fn lean_backend_renders_admitted_with_reason_comment() {
    let exporter = SoundnessExporter::new();
    let lean = LeanBackend::new();
    let output = exporter.emit(&lean);

    assert!(
        output.contains("sorry"),
        "Lean emission must use `sorry` for admitted/discharged lemmas",
    );
    assert!(
        output.contains("substitution-lemma") || output.contains("Substitution"),
        "Lean emission must carry the K_Pi_Form discharge citation",
    );
}

#[test]
fn drift_check_passes_for_canonical_rules() {
    let exporter = SoundnessExporter::new();
    assert!(
        exporter.drift_check().is_ok(),
        "canonical rule list must pass the drift check",
    );
}

#[test]
fn drift_check_rejects_short_list() {
    let short_rules: Vec<RuleSpec> = canonical_rules().into_iter().take(10).collect();
    let exporter = SoundnessExporter::with_rules(short_rules);
    let err = exporter.drift_check().expect_err("short list must fail drift check");
    assert!(err.contains("10 rules"));
    assert!(err.contains(&format!("expected {}", EXPECTED_KERNEL_RULE_COUNT)));
}

#[test]
fn proved_count_plus_admitted_count_matches_total() {
    let exporter = SoundnessExporter::new();
    let proved = exporter.proved_count();
    let admitted = exporter.admitted_count();
    let discharged = exporter.discharged_by_framework_count();
    assert_eq!(
        proved + admitted + discharged,
        EXPECTED_KERNEL_RULE_COUNT,
        "every rule must be either proved, admitted, or discharged-by-framework",
    );
    assert_eq!(proved, 4, "expected 4 proved lemmas");
    assert!(
        discharged >= 7,
        "expected at least 7 framework-discharged lemmas post-#155 Phase-1A, got {}",
        discharged,
    );
    assert_eq!(
        proved + admitted + discharged,
        EXPECTED_KERNEL_RULE_COUNT,
        "proved + admitted + discharged must total all rules",
    );
}

#[test]
fn admitted_iou_list_enumerates_every_admit() {
    let exporter = SoundnessExporter::new();
    let ious = exporter.admitted_iou_list();
    // Includes both `Admitted` (open IOU) and `DischargedByFramework`
    // (closed IOU with citation) — both contribute to the trust-
    // extension surface that the audit gate enumerates.
    assert_eq!(
        ious.len(),
        exporter.admitted_count() + exporter.discharged_by_framework_count(),
        "the IOU list must enumerate every admitted + discharged-by-framework lemma",
    );
    for (rule_name, reason) in ious {
        assert!(!reason.is_empty(), "IOU for {} has empty reason/citation", rule_name);
    }
}

#[test]
fn coq_main_theorem_dispatches_to_each_lemma() {
    let exporter = SoundnessExporter::new();
    let coq = CoqBackend::new();
    let output = exporter.emit(&coq);

    // The main theorem case-analyses on KernelRule and apply each
    // K_<Name>_sound lemma per branch.
    for r in exporter.rules() {
        let dispatch = format!("apply ({}", r.lemma_name);
        assert!(
            output.contains(&dispatch),
            "Coq main theorem must dispatch to {}",
            r.lemma_name,
        );
    }
}

#[test]
fn lean_main_theorem_dispatches_to_each_lemma() {
    let exporter = SoundnessExporter::new();
    let lean = LeanBackend::new();
    let output = exporter.emit(&lean);

    for r in exporter.rules() {
        // Lean dispatch shape: `case <RuleName> => exact <LemmaName> ...`
        let dispatch = format!("case {} => exact {}", r.rule_name, r.lemma_name);
        assert!(
            output.contains(&dispatch),
            "Lean main theorem must dispatch to {}",
            r.lemma_name,
        );
    }
}

#[test]
fn rule_categories_partition_the_corpus() {
    let exporter = SoundnessExporter::new();
    let mut counts = std::collections::HashMap::<&'static str, usize>::new();
    for r in exporter.rules() {
        *counts.entry(r.category.tag()).or_insert(0) += 1;
    }
    // The category counts must match the documented architecture in
    // model.vr / judgment.vr: Structural 9, Cubical 6, Refinement 4,
    // Quotient 3, Inductive 3, SmtAxiom 2, Diakrisis 11.
    assert_eq!(counts.get("Structural"), Some(&9));
    assert_eq!(counts.get("Cubical"), Some(&6));
    assert_eq!(counts.get("Refinement"), Some(&4));
    assert_eq!(counts.get("Quotient"), Some(&3));
    assert_eq!(counts.get("Inductive"), Some(&3));
    assert_eq!(counts.get("SmtAxiom"), Some(&2));
    assert_eq!(counts.get("Diakrisis"), Some(&11));
    let total: usize = counts.values().sum();
    assert_eq!(total, EXPECTED_KERNEL_RULE_COUNT);
}
