//! Per-script lockfile (P2.2).
//!
//! A `<script>.lock` sidecar pins the resolved-dependency graph for a
//! single `.vr` script so subsequent runs (a) skip dependency resolution
//! when the source + compiler are unchanged, and (b) reproduce identical
//! VBC builds across machines. The full-workspace `verum.lock` (handled
//! by [`crate::registry::lockfile`]) is structurally similar but lives at
//! the cog root and tracks a multi-cog graph; this module is its single-
//! file analogue.
//!
//! # On-disk layout
//!
//! ```text
//! version           = 1
//! source_path       = "/abs/path/to/script.vr"
//! source_hash       = "<blake3 hex>"
//! compiler_version = "0.1.0"
//! created_at        = 1714161000
//! updated_at        = 1714161000
//!
//! [[deps]]
//! name      = "json"
//! version   = "1.4.0"
//! source    = "registry+https://cogs.verum-lang.org"
//! integrity = "<blake3 hex>"
//! ```
//!
//! # Verification
//!
//! [`ScriptLockfile::verify_against`] returns a [`VerifyOutcome`] that
//! tells the caller whether the lockfile is fresh or must be regenerated.
//! Schema-skew is silent (treated as "regenerate"), matching the
//! script-cache convention.
//!
//! # Atomicity
//!
//! [`ScriptLockfile::write_to`] uses a tempfile + rename so a crash never
//! leaves a partially-written lockfile.

use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

/// Lockfile schema version. Bump on any incompatible layout change so
/// older lockfiles are silently regenerated by [`verify_against`].
pub const SCHEMA_VERSION: u32 = 1;

/// One resolved dependency, pinned by version + integrity hash.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedDep {
    /// Cog name (e.g. `"json"`).
    pub name: String,
    /// Resolved exact version (e.g. `"1.4.0"`).
    pub version: String,
    /// Source descriptor:
    ///   - `registry+<url>` for the public registry
    ///   - `git+<url>#<sha>` for git-pinned cogs
    ///   - `path+<dir>` for filesystem-local cogs
    pub source: String,
    /// blake3 hex digest of the resolved cog tarball / source tree.
    /// Mismatch at install time = supply-chain integrity failure.
    pub integrity: String,
}

/// Per-script lockfile.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ScriptLockfile {
    /// Schema version. See [`SCHEMA_VERSION`].
    pub version: u32,
    /// Absolute path to the script that produced this lockfile (diagnostic
    /// only — verification keys on `source_hash`, not path).
    pub source_path: PathBuf,
    /// blake3 hex digest of the script source bytes.
    pub source_hash: String,
    /// Toolchain version that produced the dep resolution.
    pub compiler_version: String,
    /// Wall-clock seconds since UNIX epoch when first created.
    pub created_at: u64,
    /// Wall-clock seconds since UNIX epoch when last refreshed.
    pub updated_at: u64,
    /// Resolved dependency set. Order is canonicalised: sorted by
    /// (name, version) so byte-identical inputs produce byte-identical
    /// lockfiles regardless of resolution traversal order.
    #[serde(default)]
    pub deps: Vec<LockedDep>,
}

impl ScriptLockfile {
    /// Construct a fresh lockfile from raw inputs. Dependencies are
    /// sorted into canonical order before storage.
    pub fn new(
        source_path: impl Into<PathBuf>,
        source_hash: impl Into<String>,
        compiler_version: impl Into<String>,
        deps: Vec<LockedDep>,
    ) -> Self {
        let now = now_secs();
        let mut deps = deps;
        deps.sort_by(|a, b| (&a.name, &a.version).cmp(&(&b.name, &b.version)));
        Self {
            version: SCHEMA_VERSION,
            source_path: source_path.into(),
            source_hash: source_hash.into(),
            compiler_version: compiler_version.into(),
            created_at: now,
            updated_at: now,
            deps,
        }
    }

    /// Hash a source byte slice into the canonical hex string used by
    /// `source_hash`. Helper so callers don't have to depend on `blake3`
    /// directly.
    pub fn hash_source(source: &[u8]) -> String {
        blake3::hash(source).to_hex().to_string()
    }

    /// Conventional sidecar path: `<script>.lock`.
    ///
    /// Note: when `script` is a relative path, the result is too — the
    /// caller is responsible for canonicalisation if reproducibility
    /// across CWDs matters.
    pub fn sidecar_path(script: &Path) -> PathBuf {
        let mut name = script.file_name().map(|s| s.to_owned()).unwrap_or_default();
        name.push(".lock");
        match script.parent() {
            Some(p) if !p.as_os_str().is_empty() => p.join(name),
            _ => PathBuf::from(name),
        }
    }

    /// Read a lockfile from disk. Returns `Ok(None)` if the file does
    /// not exist. Returns `Err` only on I/O failure or unparseable TOML
    /// (callers are expected to silently regenerate on parse error,
    /// since that's indistinguishable from schema corruption).
    pub fn read_from(path: &Path) -> io::Result<Option<Self>> {
        let text = match fs::read_to_string(path) {
            Ok(t) => t,
            Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(None),
            Err(e) => return Err(e),
        };
        match toml::from_str::<Self>(&text) {
            Ok(lf) => Ok(Some(lf)),
            Err(e) => Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("failed to parse lockfile {}: {e}", path.display()),
            )),
        }
    }

    /// Atomically write the lockfile to disk. Uses a tempfile +
    /// rename so a crash mid-write never leaves a partial file.
    ///
    /// Refreshes `updated_at` to "now" before serialising.
    pub fn write_to(&mut self, path: &Path) -> io::Result<()> {
        self.updated_at = now_secs();
        let body =
            toml::to_string(self).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?;
        if let Some(parent) = path.parent() {
            if !parent.as_os_str().is_empty() {
                fs::create_dir_all(parent)?;
            }
        }
        let tmp = path.with_extension(format!(
            "lock.tmp.{}.{}",
            std::process::id(),
            now_secs()
        ));
        {
            use std::io::Write;
            let mut f = fs::File::create(&tmp)?;
            f.write_all(body.as_bytes())?;
            f.sync_all().ok();
        }
        fs::rename(&tmp, path).map_err(|e| {
            let _ = fs::remove_file(&tmp);
            e
        })?;
        Ok(())
    }

    /// Compare this lockfile against a candidate `(source_bytes,
    /// compiler_version)` and decide whether it is still fresh.
    ///
    /// The check is intentionally conservative: any mismatch — schema,
    /// source-hash, or compiler — yields a regenerate verdict. Callers
    /// downstream don't need to inspect the discriminant unless they
    /// want a diagnostic; the boolean [`VerifyOutcome::is_fresh`] is
    /// sufficient for the fast-path.
    pub fn verify_against(&self, source_bytes: &[u8], compiler_version: &str) -> VerifyOutcome {
        if self.version != SCHEMA_VERSION {
            return VerifyOutcome::SchemaSkew {
                lockfile_version: self.version,
                expected: SCHEMA_VERSION,
            };
        }
        if self.compiler_version != compiler_version {
            return VerifyOutcome::CompilerChanged {
                lockfile: self.compiler_version.clone(),
                current: compiler_version.to_string(),
            };
        }
        let actual = Self::hash_source(source_bytes);
        if actual != self.source_hash {
            return VerifyOutcome::SourceChanged {
                lockfile: self.source_hash.clone(),
                current: actual,
            };
        }
        VerifyOutcome::Fresh
    }
}

/// Outcome of [`ScriptLockfile::verify_against`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VerifyOutcome {
    /// Lockfile is current; resolved deps can be reused as-is.
    Fresh,
    /// Source bytes differ — regenerate.
    SourceChanged { lockfile: String, current: String },
    /// Toolchain version differs — regenerate.
    CompilerChanged { lockfile: String, current: String },
    /// Schema-version skew — regenerate.
    SchemaSkew { lockfile_version: u32, expected: u32 },
}

impl VerifyOutcome {
    /// `true` only for [`VerifyOutcome::Fresh`].
    pub fn is_fresh(&self) -> bool {
        matches!(self, Self::Fresh)
    }

    /// Human-readable reason for non-`Fresh` outcomes. `None` when
    /// `is_fresh()`.
    pub fn reason(&self) -> Option<String> {
        match self {
            Self::Fresh => None,
            Self::SourceChanged { .. } => Some("script source changed".to_string()),
            Self::CompilerChanged { lockfile, current } => Some(format!(
                "compiler changed: lockfile={lockfile}, current={current}"
            )),
            Self::SchemaSkew {
                lockfile_version,
                expected,
            } => Some(format!(
                "lockfile schema v{lockfile_version} → expected v{expected}"
            )),
        }
    }
}

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn dep(name: &str, version: &str) -> LockedDep {
        LockedDep {
            name: name.to_string(),
            version: version.to_string(),
            source: "registry+https://cogs.verum-lang.org".to_string(),
            integrity: "0".repeat(64),
        }
    }

    #[test]
    fn sidecar_path_appends_lock_extension() {
        assert_eq!(
            ScriptLockfile::sidecar_path(Path::new("/tmp/script.vr")),
            PathBuf::from("/tmp/script.vr.lock")
        );
        assert_eq!(
            ScriptLockfile::sidecar_path(Path::new("script.vr")),
            PathBuf::from("script.vr.lock")
        );
        assert_eq!(
            ScriptLockfile::sidecar_path(Path::new("./nested/dir/x.vr")),
            PathBuf::from("./nested/dir/x.vr.lock")
        );
    }

    #[test]
    fn hash_source_is_deterministic_and_sensitive() {
        let a = ScriptLockfile::hash_source(b"hello");
        let b = ScriptLockfile::hash_source(b"hello");
        let c = ScriptLockfile::hash_source(b"hello!");
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(a.len(), 64); // 32-byte digest, hex encoded
    }

    #[test]
    fn new_canonicalises_dep_order() {
        let lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(b""),
            "0.1.0",
            vec![
                dep("zebra", "1.0.0"),
                dep("apple", "2.0.0"),
                dep("apple", "1.0.0"),
            ],
        );
        let names: Vec<_> = lf.deps.iter().map(|d| (&d.name, &d.version)).collect();
        assert_eq!(
            names,
            vec![
                (&"apple".to_string(), &"1.0.0".to_string()),
                (&"apple".to_string(), &"2.0.0".to_string()),
                (&"zebra".to_string(), &"1.0.0".to_string()),
            ]
        );
    }

    #[test]
    fn write_then_read_round_trip() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("script.vr.lock");
        let mut lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(b"src"),
            "0.1.0",
            vec![dep("json", "1.0.0")],
        );
        lf.write_to(&path).unwrap();
        let read = ScriptLockfile::read_from(&path).unwrap().unwrap();
        assert_eq!(read.version, lf.version);
        assert_eq!(read.source_hash, lf.source_hash);
        assert_eq!(read.compiler_version, lf.compiler_version);
        assert_eq!(read.deps, lf.deps);
    }

    #[test]
    fn read_returns_none_for_missing_file() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("absent.lock");
        assert!(ScriptLockfile::read_from(&path).unwrap().is_none());
    }

    #[test]
    fn read_errors_on_garbage_toml() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("corrupt.lock");
        fs::write(&path, b"this :: is = not = toml //").unwrap();
        let err = ScriptLockfile::read_from(&path).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::InvalidData);
    }

    #[test]
    fn write_is_atomic_no_partial_file_on_clean_path() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("nested").join("script.vr.lock");
        let mut lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(b""),
            "0.1.0",
            vec![],
        );
        lf.write_to(&path).unwrap();
        assert!(path.is_file());
        // No tempfile residue.
        let parent = path.parent().unwrap();
        for entry in fs::read_dir(parent).unwrap() {
            let entry = entry.unwrap();
            let name = entry.file_name();
            let s = name.to_string_lossy();
            assert!(
                !s.contains(".lock.tmp."),
                "leftover tempfile: {s}"
            );
        }
    }

    #[test]
    fn verify_against_fresh_when_unchanged() {
        let src = b"fn main() {}";
        let lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(src),
            "0.1.0",
            vec![],
        );
        assert!(lf.verify_against(src, "0.1.0").is_fresh());
    }

    #[test]
    fn verify_against_detects_source_change() {
        let lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(b"old"),
            "0.1.0",
            vec![],
        );
        let outcome = lf.verify_against(b"new", "0.1.0");
        assert!(!outcome.is_fresh());
        assert!(matches!(outcome, VerifyOutcome::SourceChanged { .. }));
        assert!(outcome.reason().unwrap().contains("source changed"));
    }

    #[test]
    fn verify_against_detects_compiler_change() {
        let src = b"x";
        let lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(src),
            "0.1.0",
            vec![],
        );
        let outcome = lf.verify_against(src, "0.2.0");
        assert!(matches!(outcome, VerifyOutcome::CompilerChanged { .. }));
        let reason = outcome.reason().unwrap();
        assert!(reason.contains("0.1.0") && reason.contains("0.2.0"));
    }

    #[test]
    fn verify_against_detects_schema_skew() {
        let src = b"x";
        let mut lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(src),
            "0.1.0",
            vec![],
        );
        lf.version = SCHEMA_VERSION + 99;
        let outcome = lf.verify_against(src, "0.1.0");
        assert!(matches!(outcome, VerifyOutcome::SchemaSkew { .. }));
    }

    #[test]
    fn write_refreshes_updated_at() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("x.lock");
        let mut lf = ScriptLockfile::new(
            "/tmp/x.vr",
            ScriptLockfile::hash_source(b""),
            "0.1.0",
            vec![],
        );
        let before = lf.updated_at;
        // Sleep is unreliable in tests; clamp to manual reset of `created_at`
        // ten seconds in the past so the refresh is observable without sleep.
        lf.created_at = before.saturating_sub(10);
        lf.updated_at = before.saturating_sub(10);
        lf.write_to(&path).unwrap();
        let read = ScriptLockfile::read_from(&path).unwrap().unwrap();
        assert!(read.updated_at >= before);
        assert!(read.created_at <= read.updated_at);
    }

    #[test]
    fn canonical_dep_order_yields_byte_identical_serialisation() {
        let make = |deps| {
            ScriptLockfile::new(
                "/tmp/x.vr",
                ScriptLockfile::hash_source(b""),
                "0.1.0",
                deps,
            )
        };
        let a = make(vec![
            dep("apple", "1.0.0"),
            dep("zebra", "1.0.0"),
        ]);
        let b = make(vec![
            dep("zebra", "1.0.0"),
            dep("apple", "1.0.0"),
        ]);
        assert_eq!(a.deps, b.deps, "dep order must canonicalise");
    }
}
