//! # Proof Obligations — Model-Theoretic Discharge of Protocol Axioms
//!
//! Implements T1-R phase 2: when an `implement P for T { ... }` block is
//! compiled, every axiom declared in `P`'s body becomes a proof obligation
//! for `T`. This module collects those obligations by substituting
//! `Self` and `Self.X` references with the concrete items provided by the
//! `implement` block.
//!
//! See `docs/architecture/model-theoretic-semantics.md` for the full design.

use smallvec::{smallvec, SmallVec};
use verum_ast::decl::{ImplDecl, ImplItem, ImplItemKind, ProtocolItemKind, TypeDecl, TypeDeclBody};
use verum_ast::expr::{Expr, ExprKind};
use verum_ast::span::Span;
use verum_ast::ty::{Path, PathSegment, Type, TypeKind};
use verum_ast::Ident;
use verum_common::{Heap, Text};

/// A proof obligation generated by an `implement P for T` block.
#[derive(Debug, Clone)]
pub struct ProofObligation {
    /// The axiom's declared name, for matching against explicit `proof X by tactic;`
    /// clauses in the implement block.
    pub axiom_name: Ident,

    /// The proposition that must be proved, with `Self` and `Self.X` substituted.
    pub proposition: Expr,

    /// Span of the axiom declaration in the protocol.
    pub origin_span: Span,

    /// Span of the `implement` block.
    pub impl_span: Span,

    /// The protocol this axiom belongs to, for diagnostics.
    pub protocol_name: Text,
}

/// Look-up table from protocol item name to the concrete replacement path.
#[derive(Debug, Clone, Default)]
pub struct ImplBindings {
    /// Associated-type replacements.
    pub types: std::collections::HashMap<Text, Type>,
    /// Method-name replacements: name → qualified path into the implementing type.
    pub methods: std::collections::HashMap<Text, Path>,
    /// Associated-const replacements.
    pub consts: std::collections::HashMap<Text, Path>,
}

impl ImplBindings {
    /// Build the binding table from the `implement` block's items and the
    /// receiver type.
    pub fn from_impl_items(for_type: &Type, items: &[ImplItem]) -> Self {
        let for_type_name = extract_type_name(for_type);
        let mut bindings = ImplBindings::default();

        for item in items {
            match &item.kind {
                ImplItemKind::Function(func) => {
                    let name = Text::from(func.name.name.as_str());
                    let segments: SmallVec<[PathSegment; 4]> = smallvec![
                        PathSegment::Name(Ident::new(for_type_name.clone(), func.name.span)),
                        PathSegment::Name(Ident::new(name.clone(), func.name.span)),
                    ];
                    bindings.methods.insert(
                        name,
                        Path {
                            segments,
                            span: func.name.span,
                        },
                    );
                }
                ImplItemKind::Type { name, ty, .. } => {
                    let key = Text::from(name.name.as_str());
                    bindings.types.insert(key, ty.clone());
                }
                ImplItemKind::Const { name, .. } => {
                    let key = Text::from(name.name.as_str());
                    let segments: SmallVec<[PathSegment; 4]> = smallvec![
                        PathSegment::Name(Ident::new(for_type_name.clone(), name.span)),
                        PathSegment::Name(Ident::new(key.clone(), name.span)),
                    ];
                    bindings.consts.insert(
                        key,
                        Path {
                            segments,
                            span: name.span,
                        },
                    );
                }
                ImplItemKind::Proof { .. } => {
                    // Proof clauses do not contribute to the binding table.
                }
            }
        }

        bindings
    }

    /// Look up a value binding (method or const).
    pub fn lookup_value(&self, name: &str) -> Option<Path> {
        let key = Text::from(name);
        self.methods
            .get(&key)
            .cloned()
            .or_else(|| self.consts.get(&key).cloned())
    }

    /// Look up a type binding.
    pub fn lookup_type(&self, name: &str) -> Option<Type> {
        self.types.get(&Text::from(name)).cloned()
    }
}

/// Extract a short textual name from a type for use as a Path prefix.
fn extract_type_name(ty: &Type) -> Text {
    match &ty.kind {
        TypeKind::Path(p) => p
            .segments
            .last()
            .and_then(|seg| match seg {
                PathSegment::Name(ident) => Some(Text::from(ident.name.as_str())),
                _ => None,
            })
            .unwrap_or_else(|| Text::from("Self")),
        TypeKind::Generic { base, .. } => extract_type_name(base),
        TypeKind::Int => Text::from("Int"),
        TypeKind::Float => Text::from("Float"),
        TypeKind::Bool => Text::from("Bool"),
        TypeKind::Char => Text::from("Char"),
        TypeKind::Text => Text::from("Text"),
        TypeKind::Unit => Text::from("Unit"),
        _ => Text::from("Self"),
    }
}

// ============================================================================
// Self-substitution in expressions
// ============================================================================

/// Replace every `Self` / `Self.X` occurrence in `expr` with the corresponding
/// concrete item from `bindings`.
pub fn substitute_self_in_expr(expr: &Expr, for_type: &Type, bindings: &ImplBindings) -> Expr {
    Expr::new(
        substitute_self_in_expr_kind(&expr.kind, for_type, bindings),
        expr.span,
    )
}

fn substitute_self_in_expr_kind(
    kind: &ExprKind,
    for_type: &Type,
    bindings: &ImplBindings,
) -> ExprKind {
    match kind {
        ExprKind::Path(path) => ExprKind::Path(substitute_self_in_path(path, for_type, bindings)),

        ExprKind::Binary { op, left, right } => ExprKind::Binary {
            op: *op,
            left: Heap::new(substitute_self_in_expr(left, for_type, bindings)),
            right: Heap::new(substitute_self_in_expr(right, for_type, bindings)),
        },

        ExprKind::Unary { op, expr } => ExprKind::Unary {
            op: *op,
            expr: Heap::new(substitute_self_in_expr(expr, for_type, bindings)),
        },

        // All other kinds are passed through unchanged. The top-level Path
        // handling covers the common cases of Self / Self.X references inside
        // axiom bodies (assoc, left_unit, etc.). Deeper recursion into Call /
        // Field / MethodCall etc. can be added as the axiom surface grows —
        // for now the parser produces Binary / Unary / Path trees for typical
        // algebraic axioms.
        other => other.clone(),
    }
}

/// Walk a `Path` and replace `Self` / `Self.X` segments.
fn substitute_self_in_path(path: &Path, for_type: &Type, bindings: &ImplBindings) -> Path {
    if path.segments.is_empty() {
        return path.clone();
    }

    let first_is_self = matches!(path.segments[0], PathSegment::SelfValue)
        || matches!(
            &path.segments[0],
            PathSegment::Name(ident) if ident.name.as_str() == "Self"
        );

    if !first_is_self {
        return path.clone();
    }

    // Case A: Just `Self` → replace with for_type's path head.
    if path.segments.len() == 1 {
        let type_name = extract_type_name(for_type);
        return Path::single(Ident::new(type_name, path.span));
    }

    // Case B: `Self.X` → look up X in bindings.
    if let PathSegment::Name(second_ident) = &path.segments[1] {
        let name = second_ident.name.as_str();

        // Value-level lookup (methods / consts).
        if let Some(concrete_path) = bindings.lookup_value(name) {
            let mut result: SmallVec<[PathSegment; 4]> = concrete_path.segments.clone();
            for seg in path.segments.iter().skip(2) {
                result.push(seg.clone());
            }
            return Path {
                segments: result,
                span: path.span,
            };
        }

        // Type-level lookup — replace with for_type head, keep remaining segments.
        if bindings.lookup_type(name).is_some() {
            let type_name = extract_type_name(for_type);
            let mut result: SmallVec<[PathSegment; 4]> =
                smallvec![PathSegment::Name(Ident::new(type_name, path.span))];
            for seg in path.segments.iter().skip(1) {
                result.push(seg.clone());
            }
            return Path {
                segments: result,
                span: path.span,
            };
        }
    }

    // Unknown member of Self — replace prefix with for_type, leave the rest.
    let type_name = extract_type_name(for_type);
    let mut result: SmallVec<[PathSegment; 4]> =
        smallvec![PathSegment::Name(Ident::new(type_name, path.span))];
    for seg in path.segments.iter().skip(1) {
        result.push(seg.clone());
    }
    Path {
        segments: result,
        span: path.span,
    }
}

// ============================================================================
// Obligation collection
// ============================================================================

/// Walk a protocol declaration and collect all axioms as proof obligations
/// against a specific `implement` block.
pub fn collect_impl_obligations(
    impl_decl: &ImplDecl,
    protocol_decl: &TypeDecl,
) -> Vec<ProofObligation> {
    let mut obligations = Vec::new();

    let for_type = match &impl_decl.kind {
        verum_ast::decl::ImplKind::Protocol { for_type, .. } => for_type,
        _ => return obligations,
    };

    let items_vec: Vec<ImplItem> = impl_decl.items.iter().cloned().collect();
    let bindings = ImplBindings::from_impl_items(for_type, &items_vec);

    let protocol_items = match &protocol_decl.body {
        TypeDeclBody::Protocol(body) => &body.items,
        _ => return obligations,
    };

    let protocol_name = Text::from(protocol_decl.name.name.as_str());

    for item in protocol_items.iter() {
        if let ProtocolItemKind::Axiom(axiom_decl) = &item.kind {
            let substituted =
                substitute_self_in_expr(axiom_decl.proposition.as_ref(), for_type, &bindings);
            obligations.push(ProofObligation {
                axiom_name: axiom_decl.name.clone(),
                proposition: substituted,
                origin_span: axiom_decl.span,
                impl_span: impl_decl.span,
                protocol_name: protocol_name.clone(),
            });
        }
    }

    obligations
}

/// Locate the explicit `proof X by tactic;` clause for `axiom_name` in an
/// impl block, if any.
pub fn find_proof_clause_for<'a>(
    impl_decl: &'a ImplDecl,
    axiom_name: &str,
) -> Option<&'a verum_ast::decl::TacticExpr> {
    for item in impl_decl.items.iter() {
        if let ImplItemKind::Proof {
            axiom_name: name,
            tactic,
        } = &item.kind
        {
            if name.name.as_str() == axiom_name {
                return Some(tactic);
            }
        }
    }
    None
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_type_name_handles_primitives() {
        let int = Type::new(TypeKind::Int, Span::default());
        assert_eq!(extract_type_name(&int).as_str(), "Int");

        let bool_ty = Type::new(TypeKind::Bool, Span::default());
        assert_eq!(extract_type_name(&bool_ty).as_str(), "Bool");
    }

    #[test]
    fn impl_bindings_empty_by_default() {
        let for_type = Type::new(TypeKind::Int, Span::default());
        let bindings = ImplBindings::from_impl_items(&for_type, &[]);
        assert!(bindings.types.is_empty());
        assert!(bindings.methods.is_empty());
        assert!(bindings.consts.is_empty());
    }

    #[test]
    fn lookup_value_returns_none_for_unknown() {
        let bindings = ImplBindings::default();
        assert!(bindings.lookup_value("nonexistent").is_none());
    }

    #[test]
    fn substitute_self_path_alone_becomes_for_type() {
        let for_type = Type::new(TypeKind::Int, Span::default());
        let bindings = ImplBindings::default();
        let path = Path::single(Ident::new(Text::from("Self"), Span::default()));
        let result = substitute_self_in_path(&path, &for_type, &bindings);
        assert_eq!(result.segments.len(), 1);
        match &result.segments[0] {
            PathSegment::Name(ident) => assert_eq!(ident.name.as_str(), "Int"),
            _ => panic!("expected Name segment"),
        }
    }

    #[test]
    fn substitute_self_dot_member_no_binding_uses_for_type_head() {
        let for_type = Type::new(TypeKind::Int, Span::default());
        let bindings = ImplBindings::default();
        let path = Path {
            segments: smallvec![
                PathSegment::Name(Ident::new(Text::from("Self"), Span::default())),
                PathSegment::Name(Ident::new(Text::from("Elem"), Span::default())),
            ],
            span: Span::default(),
        };
        let result = substitute_self_in_path(&path, &for_type, &bindings);
        assert_eq!(result.segments.len(), 2);
        match &result.segments[0] {
            PathSegment::Name(ident) => assert_eq!(ident.name.as_str(), "Int"),
            _ => panic!("expected Name segment"),
        }
        match &result.segments[1] {
            PathSegment::Name(ident) => assert_eq!(ident.name.as_str(), "Elem"),
            _ => panic!("expected Name segment"),
        }
    }
}
