//! Build Assets Intrinsics (Tier 1 - Requires BuildAssets)
//!
//! Provides compile-time file system access with security restrictions.
//! All functions in this module require the `BuildAssets` context since they
//! access the file system.
//!
//! ## File Loading
//!
//! | Function | Signature | Description |
//! |----------|-----------|-------------|
//! | `load_text(path)` | `(Text) -> Text` | Load file as text |
//! | `include_bytes(path)` | `(Text) -> Bytes` | Load file as bytes |
//! | `include_str(path)` | `(Text) -> Text` | Alias for load_text |
//!
//! ## File System Operations
//!
//! | Function | Signature | Description |
//! |----------|-----------|-------------|
//! | `asset_exists(path)` | `(Text) -> Bool` | Check if file exists |
//! | `asset_list_dir(path)` | `(Text) -> List<Text>` | List directory contents |
//! | `asset_metadata(path)` | `(Text) -> AssetMetadata` | Get file metadata |
//!
//! ## Security
//!
//! All paths are restricted to the project root and configured asset directories.
//! Path traversal (e.g., `..`) and absolute paths are not allowed.
//!
//! ## Context Requirements
//!
//! **Tier 1**: All functions require `using [BuildAssets]` context.
//!
//! Verum unified meta-system: all compile-time computation uses `meta` (meta fn,
//! @tagged_literal, @derive, @interpolation_handler). Multi-pass architecture:
//! Pass 1 parses and registers meta handlers, Pass 2 expands using complete
//! registry, Pass 3+ performs semantic analysis. Sandboxed execution (no I/O).
//! Meta context unification: all compile-time features desugar to meta-system
//! operations, providing one coherent model with convenient syntax sugar.

use verum_common::{List, Text};

use super::context_requirements::{BuiltinInfo, BuiltinRegistry};
use super::{ConstValue, MetaContext, MetaError};

/// Register build assets builtins with context requirements
///
/// All file system functions require BuildAssets context since they
/// access files from the project directory.
pub fn register_builtins(map: &mut BuiltinRegistry) {
    // ========================================================================
    // File Loading (Tier 1 - BuildAssets)
    // ========================================================================

    map.insert(
        Text::from("load_text"),
        BuiltinInfo::build_assets(
            meta_load_text,
            "Load file content as text",
            "(Text) -> Text",
        ),
    );
    map.insert(
        Text::from("include_str"),
        BuiltinInfo::build_assets(
            meta_load_text,
            "Load file content as text (alias for load_text)",
            "(Text) -> Text",
        ),
    );
    map.insert(
        Text::from("include_bytes"),
        BuiltinInfo::build_assets(
            meta_include_bytes,
            "Load file content as bytes",
            "(Text) -> Bytes",
        ),
    );
    // P7 (#20) — `@embed(path)` is the attribute-form alias for
    // `include_bytes(path)`. Both surface the same `meta_include_bytes`
    // dispatcher; the only difference is the @ macro-call syntax
    // accepted at expression positions outside a `meta fn`. Registered
    // under the bare name `embed` so the macro expander resolves
    // `@embed("…")` through the standard builtin lookup path.
    map.insert(
        Text::from("embed"),
        BuiltinInfo::build_assets(
            meta_include_bytes,
            "Embed a file's bytes at compile time (alias for include_bytes; \
             usable as an `@embed(\"path\")` macro call)",
            "(Text) -> Bytes",
        ),
    );

    // P7 (#20) — `@embed_glob(pattern)` returns the matched files
    // as `(Text, Bytes)` pairs (relative path, file bytes).
    // Single-level glob today (`*` / `?` in the basename
    // component); recursive `**` is reserved for follow-up.
    map.insert(
        Text::from("embed_glob"),
        BuiltinInfo::build_assets(
            meta_embed_glob,
            "Embed every file matching a glob pattern at compile time. \
             Supports `*`/`?` within a single path component and `**` \
             for recursive descent (must be a standalone path component, \
             e.g. `assets/**/*.png`). Returns List<(Text, Bytes)> \
             sorted lexicographically by path so generated bytecode is \
             deterministic across platforms. Walk depth capped at 64 \
             to prevent symlink-cycle stack exhaustion.",
            "(Text) -> List<(Text, Bytes)>",
        ),
    );

    // P7 (#20) — `@codegen("path/to/spec.toml")` MVP slice. Parses
    // a TOML document at compile time and returns it as a
    // `ConstValue::Map` keyed by Text. Use cases: declarative
    // schema → record-type derivations, build-time config tables,
    // structured asset manifests. The full attribute-form
    // `@codegen` (user meta-fn invocation over the parsed spec) is
    // a follow-up; this primitive is the foundation. Registered
    // under both `load_toml` (function-call form) and `codegen`
    // (macro-call attribute form) so either spelling resolves to
    // the same dispatcher.
    map.insert(
        Text::from("load_toml"),
        BuiltinInfo::build_assets(
            meta_load_toml,
            "Parse a TOML file at compile time. Returns a Map<Text, ConstValue>; \
             nested tables become nested Maps, arrays become Arrays, datetimes \
             collapse to RFC 3339 text. Sandbox-restricted to project root.",
            "(Text) -> Map<Text, Any>",
        ),
    );
    map.insert(
        Text::from("codegen"),
        BuiltinInfo::build_assets(
            meta_codegen,
            "@codegen(\"spec.toml\") — load a TOML codegen spec at compile \
             time, returning Map<Text, Any>.  Two-arg form \
             `codegen(\"spec.toml\", \"build_fn\")` additionally invokes \
             the user-defined meta fn `build_fn` with the parsed map and \
             returns whatever it produces (typically a List<Item> spliced \
             into the surrounding module).  Sandbox-restricted to project \
             root.",
            "(Text [, Text]) -> Any",
        ),
    );

    // ========================================================================
    // File System Operations (Tier 1 - BuildAssets)
    // ========================================================================

    map.insert(
        Text::from("asset_exists"),
        BuiltinInfo::build_assets(
            meta_asset_exists,
            "Check if asset file exists",
            "(Text) -> Bool",
        ),
    );
    map.insert(
        Text::from("asset_list_dir"),
        BuiltinInfo::build_assets(
            meta_asset_list_dir,
            "List directory contents",
            "(Text) -> List<Text>",
        ),
    );
    map.insert(
        Text::from("asset_metadata"),
        BuiltinInfo::build_assets(
            meta_asset_metadata,
            "Get file metadata (size, modified, type)",
            "(Text) -> (UInt, UInt, Bool, Bool, Bool)",
        ),
    );
}

// ============================================================================
// File Loading
// ============================================================================

/// Load file content as text
fn meta_load_text(ctx: &mut MetaContext, args: List<ConstValue>) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }

    match &args[0] {
        ConstValue::Text(path) => {
            let content = ctx.build_assets.load_text(path.as_str())?;
            Ok(ConstValue::Text(content))
        }
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

/// Load file content as bytes
fn meta_include_bytes(ctx: &mut MetaContext, args: List<ConstValue>) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }

    match &args[0] {
        ConstValue::Text(path) => {
            let content = ctx.build_assets.load(path.as_str())?;
            Ok(ConstValue::Bytes(content))
        }
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

/// `@embed_glob(pattern)` — return every file matching the
/// pattern as a deterministic-ordered list of (path, bytes)
/// tuples. Sandbox + caching are inherited from the underlying
/// `BuildAssetsInfo::load_glob` and `load` paths.
fn meta_embed_glob(
    ctx: &mut MetaContext,
    args: List<ConstValue>,
) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }
    match &args[0] {
        ConstValue::Text(pattern) => {
            let matches = ctx.build_assets.load_glob(pattern.as_str())?;
            let pairs: List<ConstValue> = matches
                .into_iter()
                .map(|(rel_path, bytes)| {
                    ConstValue::Tuple(List::from(vec![
                        ConstValue::Text(rel_path),
                        ConstValue::Bytes(bytes),
                    ]))
                })
                .collect();
            Ok(ConstValue::Array(pairs))
        }
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

/// `@codegen(path)` / `load_toml(path)` — parse a TOML
/// document at compile time and return it as a
/// `ConstValue::Map<Text, ConstValue>`. The MVP foundation for
/// the full attribute-form `@codegen` (user meta-fn over the
/// parsed spec) — once user meta-fns can take a Map argument
/// they can build whatever AST they want from this surface.
fn meta_load_toml(
    ctx: &mut MetaContext,
    args: List<ConstValue>,
) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }
    match &args[0] {
        ConstValue::Text(path) => ctx.build_assets.load_toml(path.as_str()),
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

/// `@codegen(path)` — single-arg form delegates to
/// `load_toml`, returning the parsed Map<Text, MetaValue>
/// for further composition by user code.
///
/// `@codegen(path, fn_name)` — two-arg form is the
/// architectural completion of #20 P7 / @codegen:
/// after loading the spec, invokes the user-defined meta
/// fn `fn_name` with the parsed map as its single
/// argument and returns whatever the meta fn produces.
/// The typical user pattern is for the meta fn to return
/// a `MetaValue::Items(...)` that the surrounding macro
/// expansion splices into the module:
///
/// ```verum
/// public meta fn build_users(spec: Map<Text, Any>) -> List<Item>
///     using [BuildAssets, AstAccess]
/// {
///     // Construct AST items from the parsed spec...
/// }
///
/// // Module-level invocation:
/// @codegen("schemas/users.toml", "build_users");
/// ```
///
/// Sandbox + cycle protection: file load goes through the
/// same `BuildAssetsInfo::load_toml` path (project-root
/// canonicalize precheck); the user meta-fn invocation
/// goes through `execute_user_meta_fn` which enforces the
/// recursion limit.
fn meta_codegen(
    ctx: &mut MetaContext,
    args: List<ConstValue>,
) -> Result<ConstValue, MetaError> {
    if args.len() != 1 && args.len() != 2 {
        return Err(MetaError::ArityMismatch {
            expected: 1,
            got: args.len(),
        });
    }
    let path_text = match &args[0] {
        ConstValue::Text(t) => t.clone(),
        _ => {
            return Err(MetaError::TypeMismatch {
                expected: Text::from("Text"),
                found: args[0].type_name(),
            });
        }
    };
    // Load the TOML spec — same path the single-arg form uses.
    let spec = ctx.build_assets.load_toml(path_text.as_str())?;

    if args.len() == 1 {
        return Ok(spec);
    }

    // Two-arg form: invoke the named user meta fn.
    let fn_name = match &args[1] {
        ConstValue::Text(t) => t.clone(),
        _ => {
            return Err(MetaError::TypeMismatch {
                expected: Text::from("Text"),
                found: args[1].type_name(),
            });
        }
    };

    // Look up the user-defined meta fn in the registry.
    // The lookup uses the current module as the search
    // origin so users can reference fns defined in their
    // own module without a qualified path.
    let registry_arc = ctx.registry.as_ref().cloned().ok_or_else(|| {
        MetaError::Other(Text::from(
            "@codegen: meta registry not wired into context — \
             this build path doesn't support user meta fn dispatch",
        ))
    })?;
    let user_fn = match registry_arc.get_user_meta_fn(&ctx.current_module, &fn_name) {
        verum_common::Maybe::Some(f) => f,
        verum_common::Maybe::None => {
            return Err(MetaError::Other(Text::from(format!(
                "@codegen({}, {}): user meta fn `{}` not found in registry",
                path_text, fn_name, fn_name
            ))));
        }
    };

    // Validate arity — the user meta fn must accept exactly
    // one argument (the parsed spec map).  This is a clear
    // diagnostic instead of letting `execute_user_meta_fn`
    // surface a generic ArityMismatch with no context.
    if user_fn.params.len() != 1 {
        return Err(MetaError::Other(Text::from(format!(
            "@codegen({}, {}): user meta fn `{}` must accept exactly 1 argument \
             (the parsed spec Map<Text, Any>); got {} parameters",
            path_text,
            fn_name,
            fn_name,
            user_fn.params.len()
        ))));
    }

    // Invoke the user meta fn with the parsed spec.  The
    // result is whatever the fn returns — typically
    // MetaValue::Items for code-generation patterns, but
    // could be any ConstValue (e.g. derived constants).
    ctx.execute_user_meta_fn(&user_fn, vec![spec])
}

// ============================================================================
// File System Operations
// ============================================================================

/// Check if file exists
fn meta_asset_exists(ctx: &mut MetaContext, args: List<ConstValue>) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }

    match &args[0] {
        ConstValue::Text(path) => {
            let exists = ctx.build_assets.exists(path.as_str());
            Ok(ConstValue::Bool(exists))
        }
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

/// List directory contents
fn meta_asset_list_dir(ctx: &mut MetaContext, args: List<ConstValue>) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }

    match &args[0] {
        ConstValue::Text(path) => {
            let entries = ctx.build_assets.list_dir(path.as_str())?;
            let result: List<ConstValue> = entries
                .iter()
                .map(|e| ConstValue::Text(e.clone()))
                .collect();
            Ok(ConstValue::Array(result))
        }
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

/// Get file metadata
fn meta_asset_metadata(ctx: &mut MetaContext, args: List<ConstValue>) -> Result<ConstValue, MetaError> {
    if args.len() != 1 {
        return Err(MetaError::ArityMismatch { expected: 1, got: args.len() });
    }

    match &args[0] {
        ConstValue::Text(path) => {
            let metadata = ctx.build_assets.metadata(path.as_str())?;
            // Return as tuple: (size, modified_ns, is_directory, is_file, is_symlink)
            Ok(ConstValue::Tuple(List::from(vec![
                ConstValue::UInt(metadata.size.into()),
                ConstValue::UInt(metadata.modified_ns.into()),
                ConstValue::Bool(metadata.is_directory),
                ConstValue::Bool(metadata.is_file),
                ConstValue::Bool(metadata.is_symlink),
            ])))
        }
        _ => Err(MetaError::TypeMismatch {
            expected: Text::from("Text"),
            found: args[0].type_name(),
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::meta::subsystems::build_assets::BuildAssetsInfo;
    use std::io::Write;
    use tempfile::TempDir;

    fn create_test_context() -> (MetaContext, TempDir) {
        let temp_dir = TempDir::new().unwrap();
        let temp_path = temp_dir.path().to_string_lossy().to_string();

        let mut ctx = MetaContext::new();
        ctx.build_assets = BuildAssetsInfo::new()
            .with_project_root(temp_path);

        (ctx, temp_dir)
    }

    #[test]
    fn test_load_text() {
        let (mut ctx, temp_dir) = create_test_context();

        // Create a test file
        let file_path = temp_dir.path().join("test.txt");
        let mut file = std::fs::File::create(&file_path).unwrap();
        writeln!(file, "Hello, World!").unwrap();

        let args = List::from(vec![ConstValue::Text(Text::from("test.txt"))]);
        let result = meta_load_text(&mut ctx, args).unwrap();

        if let ConstValue::Text(content) = result {
            assert!(content.contains("Hello, World!"));
        } else {
            panic!("Expected Text");
        }
    }

    #[test]
    fn test_include_bytes() {
        let (mut ctx, temp_dir) = create_test_context();

        // Create a test file
        let file_path = temp_dir.path().join("test.bin");
        std::fs::write(&file_path, &[0x00, 0x01, 0x02, 0xFF]).unwrap();

        let args = List::from(vec![ConstValue::Text(Text::from("test.bin"))]);
        let result = meta_include_bytes(&mut ctx, args).unwrap();

        if let ConstValue::Bytes(bytes) = result {
            assert_eq!(bytes, vec![0x00, 0x01, 0x02, 0xFF]);
        } else {
            panic!("Expected Bytes");
        }
    }

    #[test]
    fn test_asset_exists() {
        let (mut ctx, temp_dir) = create_test_context();

        // Create a test file
        let file_path = temp_dir.path().join("exists.txt");
        std::fs::write(&file_path, "test").unwrap();

        // Test existing file
        let args = List::from(vec![ConstValue::Text(Text::from("exists.txt"))]);
        let result = meta_asset_exists(&mut ctx, args).unwrap();
        assert_eq!(result, ConstValue::Bool(true));

        // Test non-existing file
        let args = List::from(vec![ConstValue::Text(Text::from("nonexistent.txt"))]);
        let result = meta_asset_exists(&mut ctx, args).unwrap();
        assert_eq!(result, ConstValue::Bool(false));
    }

    #[test]
    fn test_asset_list_dir() {
        let (mut ctx, temp_dir) = create_test_context();

        // Create test files
        std::fs::write(temp_dir.path().join("file1.txt"), "").unwrap();
        std::fs::write(temp_dir.path().join("file2.txt"), "").unwrap();
        std::fs::create_dir(temp_dir.path().join("subdir")).unwrap();

        let args = List::from(vec![ConstValue::Text(Text::from("."))]);
        let result = meta_asset_list_dir(&mut ctx, args).unwrap();

        if let ConstValue::Array(entries) = result {
            assert!(entries.len() >= 2); // At least file1.txt and file2.txt
        } else {
            panic!("Expected Array");
        }
    }

    #[test]
    fn test_asset_metadata() {
        let (mut ctx, temp_dir) = create_test_context();

        // Create a test file with known content
        let file_path = temp_dir.path().join("meta.txt");
        std::fs::write(&file_path, "Hello").unwrap();

        let args = List::from(vec![ConstValue::Text(Text::from("meta.txt"))]);
        let result = meta_asset_metadata(&mut ctx, args).unwrap();

        if let ConstValue::Tuple(fields) = result {
            assert_eq!(fields.len(), 5);
            // size should be 5 bytes
            if let ConstValue::UInt(size) = &fields[0] {
                assert_eq!(*size, 5);
            } else {
                panic!("Expected UInt for size");
            }
            // is_file should be true
            if let ConstValue::Bool(is_file) = &fields[3] {
                assert!(*is_file);
            } else {
                panic!("Expected Bool for is_file");
            }
        } else {
            panic!("Expected Tuple");
        }
    }

    #[test]
    fn test_path_traversal_blocked() {
        let (mut ctx, _temp_dir) = create_test_context();

        // Attempt path traversal
        let args = List::from(vec![ConstValue::Text(Text::from("../etc/passwd"))]);
        let result = meta_load_text(&mut ctx, args);

        assert!(result.is_err());
        if let Err(MetaError::Other(msg)) = result {
            assert!(msg.contains("Path traversal"));
        }
    }

    #[test]
    fn test_absolute_path_blocked() {
        let (mut ctx, _temp_dir) = create_test_context();

        // Attempt absolute path
        let args = List::from(vec![ConstValue::Text(Text::from("/etc/passwd"))]);
        let result = meta_load_text(&mut ctx, args);

        assert!(result.is_err());
        if let Err(MetaError::Other(msg)) = result {
            assert!(msg.contains("Absolute paths"));
        }
    }

    /// #20 / P7 — `@embed("path")` registers as a builtin alias for
    /// `include_bytes`, dispatching through the same
    /// `meta_include_bytes` function. Verifies the registry wiring
    /// and that the same path-traversal sandbox applies. The macro-
    /// expansion side that translates the `@`-prefixed form into a
    /// builtin call uses the registry's name lookup, so registering
    /// the alias is sufficient at this layer; the parser-side
    /// recognition rides the existing `@<ident>(args)` macro-call
    /// grammar that `include_bytes` already exercises in
    /// `vcs/specs/meta-system/success/builtins/build_assets/file_loading.vr`.
    #[test]
    fn test_embed_alias_registered_for_include_bytes() {
        let mut map = BuiltinRegistry::new();
        register_builtins(&mut map);
        // Both the original name and the alias resolve to a builtin.
        assert!(
            map.get(&Text::from("include_bytes")).is_some(),
            "include_bytes must remain registered"
        );
        let embed = map
            .get(&Text::from("embed"))
            .expect("embed alias must be registered for the @embed macro form");
        // Signature mirrors include_bytes.
        assert_eq!(embed.signature, "(Text) -> Bytes");
    }

    #[test]
    fn test_embed_loads_bytes_like_include_bytes() {
        let (mut ctx, temp_dir) = create_test_context();
        let file_path = temp_dir.path().join("asset.bin");
        std::fs::write(&file_path, &[0xDE, 0xAD, 0xBE, 0xEF]).unwrap();

        // Resolve the embed alias from the registry and dispatch.
        let mut map = BuiltinRegistry::new();
        register_builtins(&mut map);
        let info = map.get(&Text::from("embed")).expect("embed registered").clone();
        let args = List::from(vec![ConstValue::Text(Text::from("asset.bin"))]);
        let result = (info.function)(&mut ctx, args).unwrap();

        match result {
            ConstValue::Bytes(bytes) => assert_eq!(bytes, vec![0xDE, 0xAD, 0xBE, 0xEF]),
            other => panic!("expected Bytes, got {:?}", other),
        }
    }

    #[test]
    fn test_embed_blocks_path_traversal() {
        // The alias inherits the same sandbox as include_bytes.
        let (mut ctx, _temp_dir) = create_test_context();

        let mut map = BuiltinRegistry::new();
        register_builtins(&mut map);
        let info = map.get(&Text::from("embed")).expect("embed registered").clone();
        let args = List::from(vec![ConstValue::Text(Text::from("../etc/passwd"))]);
        let result = (info.function)(&mut ctx, args);
        assert!(
            result.is_err(),
            "@embed must reject `..` traversal — same sandbox as include_bytes"
        );
    }

    // =====================================================================
    // #20 / P7 — @embed_glob
    // =====================================================================

    #[test]
    fn test_embed_glob_registered() {
        let mut map = BuiltinRegistry::new();
        register_builtins(&mut map);
        let info = map
            .get(&Text::from("embed_glob"))
            .expect("embed_glob must be registered");
        assert_eq!(info.signature, "(Text) -> List<(Text, Bytes)>");
    }

    #[test]
    fn test_embed_glob_matches_basenames_in_subdir() {
        let (mut ctx, temp_dir) = create_test_context();
        // Create assets/icon.png, assets/logo.png, assets/notes.txt.
        let assets = temp_dir.path().join("assets");
        std::fs::create_dir(&assets).unwrap();
        std::fs::write(assets.join("icon.png"), &[0xDE, 0xAD]).unwrap();
        std::fs::write(assets.join("logo.png"), &[0xBE, 0xEF]).unwrap();
        std::fs::write(assets.join("notes.txt"), b"prose").unwrap();

        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("assets/*.png"))]),
        )
        .expect("embed_glob should succeed");

        match result {
            ConstValue::Array(pairs) => {
                assert_eq!(pairs.len(), 2, "expected 2 PNG matches, got {}", pairs.len());
                // Deterministic alphabetical order.
                let icon = match &pairs[0] {
                    ConstValue::Tuple(t) => t,
                    _ => panic!("expected tuple"),
                };
                match &icon[0] {
                    ConstValue::Text(p) => assert_eq!(p.as_str(), "assets/icon.png"),
                    other => panic!("expected Text path, got {:?}", other),
                }
                match &icon[1] {
                    ConstValue::Bytes(b) => assert_eq!(*b, vec![0xDE, 0xAD]),
                    other => panic!("expected Bytes, got {:?}", other),
                }
                let logo = match &pairs[1] {
                    ConstValue::Tuple(t) => t,
                    _ => panic!("expected tuple"),
                };
                match &logo[0] {
                    ConstValue::Text(p) => assert_eq!(p.as_str(), "assets/logo.png"),
                    other => panic!("expected Text path, got {:?}", other),
                }
            }
            other => panic!("expected Array, got {:?}", other),
        }
    }

    #[test]
    fn test_embed_glob_no_matches_returns_empty_list() {
        let (mut ctx, temp_dir) = create_test_context();
        let assets = temp_dir.path().join("assets");
        std::fs::create_dir(&assets).unwrap();
        std::fs::write(assets.join("notes.txt"), b"prose").unwrap();

        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("assets/*.png"))]),
        )
        .expect("embed_glob should succeed even with no matches");
        match result {
            ConstValue::Array(pairs) => assert_eq!(pairs.len(), 0),
            other => panic!("expected empty Array, got {:?}", other),
        }
    }

    #[test]
    fn test_embed_glob_recursive_pattern_walks_subtree() {
        let (mut ctx, temp_dir) = create_test_context();
        // assets/icons/error.png
        // assets/icons/info.png
        // assets/themes/dark/wallpaper.png
        // assets/themes/light/wallpaper.png
        // assets/notes.txt   (must NOT match *.png)
        let icons = temp_dir.path().join("assets").join("icons");
        let dark = temp_dir.path().join("assets").join("themes").join("dark");
        let light = temp_dir.path().join("assets").join("themes").join("light");
        std::fs::create_dir_all(&icons).unwrap();
        std::fs::create_dir_all(&dark).unwrap();
        std::fs::create_dir_all(&light).unwrap();
        std::fs::write(icons.join("error.png"), &[1u8]).unwrap();
        std::fs::write(icons.join("info.png"), &[2u8]).unwrap();
        std::fs::write(dark.join("wallpaper.png"), &[3u8]).unwrap();
        std::fs::write(light.join("wallpaper.png"), &[4u8]).unwrap();
        std::fs::write(temp_dir.path().join("assets").join("notes.txt"), b"prose").unwrap();

        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("assets/**/*.png"))]),
        )
        .expect("recursive embed_glob must succeed");

        match result {
            ConstValue::Array(pairs) => {
                assert_eq!(
                    pairs.len(),
                    4,
                    "expected 4 PNG matches across the tree, got {}",
                    pairs.len()
                );
                // Lexicographic ordering — matches must be
                // deterministic across platforms.
                let paths: Vec<&str> = pairs
                    .iter()
                    .map(|p| match p {
                        ConstValue::Tuple(t) => match &t[0] {
                            ConstValue::Text(s) => s.as_str(),
                            _ => panic!("expected Text"),
                        },
                        _ => panic!("expected Tuple"),
                    })
                    .collect();
                assert_eq!(paths[0], "assets/icons/error.png");
                assert_eq!(paths[1], "assets/icons/info.png");
                assert_eq!(paths[2], "assets/themes/dark/wallpaper.png");
                assert_eq!(paths[3], "assets/themes/light/wallpaper.png");
            }
            other => panic!("expected Array, got {:?}", other),
        }
    }

    #[test]
    fn test_embed_glob_double_star_only_zero_components() {
        // `**` must match zero or more components — `assets/**`
        // should match every file directly OR transitively under
        // `assets/`, including `assets/notes.txt` at depth 1.
        let (mut ctx, temp_dir) = create_test_context();
        let assets = temp_dir.path().join("assets");
        let nested = assets.join("nested");
        std::fs::create_dir_all(&nested).unwrap();
        std::fs::write(assets.join("notes.txt"), b"top").unwrap();
        std::fs::write(nested.join("inner.txt"), b"inner").unwrap();

        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("assets/**"))]),
        )
        .expect("`**` should match zero or more components");
        match result {
            ConstValue::Array(pairs) => {
                assert!(
                    pairs.len() >= 2,
                    "expected at least 2 files, got {}",
                    pairs.len()
                );
            }
            other => panic!("expected Array, got {:?}", other),
        }
    }

    #[test]
    fn test_embed_glob_rejects_double_star_inside_segment() {
        let (mut ctx, _temp_dir) = create_test_context();
        // `**` inside a segment (not standalone) is rejected —
        // `a**b` is ambiguous w.r.t. the recursive grammar.
        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("a**b/file.png"))]),
        );
        assert!(
            result.is_err(),
            "`**` inside a segment must be rejected (only standalone components)"
        );
    }

    #[test]
    fn test_embed_glob_wildcard_directory_component() {
        // Single-level wildcards in directory components are
        // now supported (no longer require `**`).
        let (mut ctx, temp_dir) = create_test_context();
        let dir_a = temp_dir.path().join("a1");
        let dir_b = temp_dir.path().join("a2");
        std::fs::create_dir_all(&dir_a).unwrap();
        std::fs::create_dir_all(&dir_b).unwrap();
        std::fs::write(dir_a.join("file.png"), &[1u8]).unwrap();
        std::fs::write(dir_b.join("file.png"), &[2u8]).unwrap();

        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("a*/file.png"))]),
        )
        .expect("single-level wildcard in directory component should work");
        match result {
            ConstValue::Array(pairs) => {
                assert_eq!(pairs.len(), 2);
            }
            other => panic!("expected Array, got {:?}", other),
        }
    }

    #[test]
    fn test_embed_glob_blocks_path_traversal() {
        let (mut ctx, _temp_dir) = create_test_context();
        let result = meta_embed_glob(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("../etc/*.conf"))]),
        );
        assert!(
            result.is_err(),
            "@embed_glob must reject `..` traversal — same sandbox as @embed"
        );
    }

    #[test]
    fn test_embed_glob_arity_check() {
        let (mut ctx, _temp_dir) = create_test_context();
        let result = meta_embed_glob(&mut ctx, List::new());
        assert!(matches!(result, Err(MetaError::ArityMismatch { .. })));
    }

    // =====================================================================
    // #20 / P7 — @codegen / load_toml
    // =====================================================================

    #[test]
    fn test_load_toml_registered_under_both_names() {
        let mut map = BuiltinRegistry::new();
        register_builtins(&mut map);
        let load = map
            .get(&Text::from("load_toml"))
            .expect("load_toml must be registered");
        assert_eq!(load.signature, "(Text) -> Map<Text, Any>");
        // `codegen` carries the two-arg overload signature so call-site
        // diagnostics surface both forms; `load_toml` keeps the bare
        // single-arg signature because it is purely a TOML loader.
        let codegen = map
            .get(&Text::from("codegen"))
            .expect("@codegen alias must be registered for the macro form");
        assert_eq!(codegen.signature, "(Text [, Text]) -> Any");
    }

    #[test]
    fn test_load_toml_basic_table() {
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("spec.toml");
        std::fs::write(
            &path,
            "name = \"verum\"\nversion = 1\nstable = true\nratio = 0.75\n",
        )
        .unwrap();
        let result = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("spec.toml"))]),
        )
        .expect("load_toml should parse a flat table");
        let map = match result {
            ConstValue::Map(m) => m,
            other => panic!("expected Map, got {:?}", other),
        };
        match map.get(&Text::from("name")) {
            Some(ConstValue::Text(t)) => assert_eq!(t.as_str(), "verum"),
            other => panic!("expected Text for name, got {:?}", other),
        }
        match map.get(&Text::from("version")) {
            Some(ConstValue::Int(i)) => assert_eq!(*i, 1),
            other => panic!("expected Int for version, got {:?}", other),
        }
        match map.get(&Text::from("stable")) {
            Some(ConstValue::Bool(b)) => assert!(*b),
            other => panic!("expected Bool for stable, got {:?}", other),
        }
        match map.get(&Text::from("ratio")) {
            Some(ConstValue::Float(f)) => assert!((*f - 0.75).abs() < 1e-9),
            other => panic!("expected Float for ratio, got {:?}", other),
        }
    }

    #[test]
    fn test_load_toml_nested_tables_become_nested_maps() {
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("nested.toml");
        std::fs::write(
            &path,
            "[package]\nname = \"foo\"\n[package.author]\nname = \"alice\"\n",
        )
        .unwrap();
        let result = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("nested.toml"))]),
        )
        .expect("load_toml should parse nested tables");
        let outer = match result {
            ConstValue::Map(m) => m,
            other => panic!("expected outer Map, got {:?}", other),
        };
        let pkg = match outer.get(&Text::from("package")) {
            Some(ConstValue::Map(m)) => m.clone(),
            other => panic!("expected nested Map for package, got {:?}", other),
        };
        match pkg.get(&Text::from("name")) {
            Some(ConstValue::Text(t)) => assert_eq!(t.as_str(), "foo"),
            other => panic!("expected Text, got {:?}", other),
        }
        let author = match pkg.get(&Text::from("author")) {
            Some(ConstValue::Map(m)) => m.clone(),
            other => panic!("expected nested Map for author, got {:?}", other),
        };
        match author.get(&Text::from("name")) {
            Some(ConstValue::Text(t)) => assert_eq!(t.as_str(), "alice"),
            other => panic!("expected Text, got {:?}", other),
        }
    }

    #[test]
    fn test_load_toml_arrays_become_arrays() {
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("arr.toml");
        std::fs::write(
            &path,
            "tags = [\"a\", \"b\", \"c\"]\nports = [80, 443, 8443]\n",
        )
        .unwrap();
        let result = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("arr.toml"))]),
        )
        .expect("load_toml should parse arrays");
        let map = match result {
            ConstValue::Map(m) => m,
            other => panic!("expected Map, got {:?}", other),
        };
        match map.get(&Text::from("tags")) {
            Some(ConstValue::Array(items)) => {
                assert_eq!(items.len(), 3);
                match &items[0] {
                    ConstValue::Text(t) => assert_eq!(t.as_str(), "a"),
                    other => panic!("expected Text, got {:?}", other),
                }
            }
            other => panic!("expected Array for tags, got {:?}", other),
        }
        match map.get(&Text::from("ports")) {
            Some(ConstValue::Array(items)) => {
                assert_eq!(items.len(), 3);
                match &items[2] {
                    ConstValue::Int(i) => assert_eq!(*i, 8443),
                    other => panic!("expected Int, got {:?}", other),
                }
            }
            other => panic!("expected Array for ports, got {:?}", other),
        }
    }

    #[test]
    fn test_load_toml_datetime_collapses_to_text() {
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("dt.toml");
        // RFC 3339 datetime — toml crate parses as Datetime which we
        // collapse to its Display form (RFC 3339 round-trip).
        std::fs::write(&path, "released = 2026-04-28T12:00:00Z\n").unwrap();
        let result = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("dt.toml"))]),
        )
        .expect("load_toml should accept datetimes");
        let map = match result {
            ConstValue::Map(m) => m,
            other => panic!("expected Map, got {:?}", other),
        };
        match map.get(&Text::from("released")) {
            Some(ConstValue::Text(t)) => assert!(t.as_str().starts_with("2026-04-28")),
            other => panic!("expected datetime collapsed to Text, got {:?}", other),
        }
    }

    #[test]
    fn test_load_toml_rejects_parse_errors() {
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("bad.toml");
        std::fs::write(&path, "name = \"unterminated\nport = 80\n").unwrap();
        let result = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("bad.toml"))]),
        );
        match result {
            Err(MetaError::Other(msg)) => {
                assert!(
                    msg.as_str().contains("TOML parse error"),
                    "expected parse-error diagnostic, got: {}",
                    msg
                );
            }
            other => panic!("expected parse error, got {:?}", other),
        }
    }

    #[test]
    fn test_load_toml_blocks_path_traversal() {
        let (mut ctx, _temp_dir) = create_test_context();
        let result = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("../etc/secret.toml"))]),
        );
        assert!(
            result.is_err(),
            "load_toml must inherit the same sandbox as load_text"
        );
    }

    #[test]
    fn test_load_toml_arity_check() {
        let (mut ctx, _temp_dir) = create_test_context();
        let result = meta_load_toml(&mut ctx, List::new());
        assert!(matches!(result, Err(MetaError::ArityMismatch { .. })));
    }

    // =====================================================================
    // #20 P7 — @codegen full attribute-form (single-arg + two-arg)
    // =====================================================================

    #[test]
    fn test_codegen_single_arg_delegates_to_load_toml() {
        // Single-arg `codegen("path")` must produce identical
        // output to `load_toml("path")` — the two-arg form is a
        // strict superset.
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("spec.toml");
        std::fs::write(&path, "name = \"verum\"\nversion = 1\n").unwrap();

        let direct = meta_load_toml(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("spec.toml"))]),
        )
        .expect("single-arg load_toml");
        let via_codegen = meta_codegen(
            &mut ctx,
            List::from(vec![ConstValue::Text(Text::from("spec.toml"))]),
        )
        .expect("single-arg codegen");
        assert_eq!(direct, via_codegen);
    }

    #[test]
    fn test_codegen_arity_zero_args() {
        let (mut ctx, _t) = create_test_context();
        let r = meta_codegen(&mut ctx, List::new());
        assert!(matches!(r, Err(MetaError::ArityMismatch { .. })));
    }

    #[test]
    fn test_codegen_arity_three_args() {
        let (mut ctx, _t) = create_test_context();
        let r = meta_codegen(
            &mut ctx,
            List::from(vec![
                ConstValue::Text(Text::from("a")),
                ConstValue::Text(Text::from("b")),
                ConstValue::Text(Text::from("c")),
            ]),
        );
        assert!(matches!(r, Err(MetaError::ArityMismatch { .. })));
    }

    #[test]
    fn test_codegen_first_arg_must_be_text() {
        let (mut ctx, _t) = create_test_context();
        let r = meta_codegen(
            &mut ctx,
            List::from(vec![ConstValue::Int(42)]),
        );
        assert!(matches!(r, Err(MetaError::TypeMismatch { .. })));
    }

    #[test]
    fn test_codegen_second_arg_must_be_text() {
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("spec.toml");
        std::fs::write(&path, "k = 1\n").unwrap();
        let r = meta_codegen(
            &mut ctx,
            List::from(vec![
                ConstValue::Text(Text::from("spec.toml")),
                ConstValue::Int(42),
            ]),
        );
        assert!(matches!(r, Err(MetaError::TypeMismatch { .. })));
    }

    #[test]
    fn test_codegen_two_arg_form_requires_registry() {
        // No registry wired → @codegen("path", "fn") errors with
        // a clear diagnostic instead of a generic NotFound.
        let (mut ctx, temp_dir) = create_test_context();
        let path = temp_dir.path().join("spec.toml");
        std::fs::write(&path, "k = 1\n").unwrap();
        // create_test_context doesn't wire a registry; verify
        // the typed error mentions the missing wiring.
        let r = meta_codegen(
            &mut ctx,
            List::from(vec![
                ConstValue::Text(Text::from("spec.toml")),
                ConstValue::Text(Text::from("build_users")),
            ]),
        );
        match r {
            Err(MetaError::Other(msg)) => {
                assert!(
                    msg.as_str().contains("registry not wired"),
                    "expected registry-not-wired diagnostic, got: {}",
                    msg
                );
            }
            other => panic!("expected Other registry-not-wired error, got {:?}", other),
        }
    }
}
