//! `verum hooks install` — git pre-commit hook installer.
//!
//! Industrial pattern: one command writes `.git/hooks/pre-commit`
//! that runs `verum lint --since HEAD --severity error` plus
//! `verum fmt --check` before each commit. Reduces *"new contributor
//! to the team must paste this snippet"* friction to zero.
//!
//! Safety: the hook script carries a header marker (`# Generated
//! by `verum hooks install`...`) so `uninstall` only touches files
//! we wrote — a hand-edited or third-party hook is never silently
//! removed. `install` refuses to overwrite an existing hook unless
//! `--force` is set.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use crate::error::{CliError, Result};
use crate::ui;

/// Marker injected into every hook script we write. `uninstall`
/// keys on this so we never remove a user's hand-written script.
pub const HOOK_MARKER: &str = "# Generated by `verum hooks install`";

/// Standard pre-commit script body. Wired on top of the marker
/// header. Runs lint on changed files at error severity, then
/// `verum fmt --check` so a misformatted file fails the commit.
pub fn pre_commit_script(version: &str) -> String {
    format!(
        "#!/usr/bin/env sh\n\
         {marker} v{version} — do not edit by hand.\n\
         # Re-run `verum hooks install --force` to regenerate.\n\
         set -e\n\
         \n\
         # Lint changed .vr files at error severity. The --since\n\
         # filter is HEAD so the hook only walks staged files.\n\
         verum lint --since HEAD --severity error\n\
         \n\
         # Refuse the commit if any file isn't canonically formatted.\n\
         verum fmt --check\n",
        marker = HOOK_MARKER,
        version = version,
    )
}

/// Find the project's `.git/hooks/` directory by walking up from
/// the current dir. Returns `None` when there's no enclosing git
/// repo — that's a hard error from the caller's perspective but we
/// surface it as a typed result.
fn find_hooks_dir(start: &Path) -> Option<PathBuf> {
    let mut cursor = Some(start.to_path_buf());
    while let Some(dir) = cursor {
        let git = dir.join(".git");
        if git.is_dir() {
            return Some(git.join("hooks"));
        }
        // git worktrees use a `.git` *file* pointing at the real
        // git dir. Worth supporting for monorepo / submodule users.
        if git.is_file() {
            if let Ok(content) = fs::read_to_string(&git) {
                if let Some(path) = content.lines().next().and_then(|l| l.strip_prefix("gitdir: "))
                {
                    let abs = if Path::new(path).is_absolute() {
                        PathBuf::from(path)
                    } else {
                        dir.join(path)
                    };
                    return Some(abs.join("hooks"));
                }
            }
        }
        cursor = dir.parent().map(|p| p.to_path_buf());
    }
    None
}

fn pre_commit_path(hooks_dir: &Path) -> PathBuf {
    hooks_dir.join("pre-commit")
}

/// `verum hooks install [--force]`.
pub fn install(force: bool) -> Result<()> {
    let cwd = std::env::current_dir()
        .map_err(|e| CliError::Custom(format!("read cwd: {e}")))?;
    let hooks_dir = find_hooks_dir(&cwd)
        .ok_or_else(|| CliError::Custom(
            "no enclosing git repository found — `verum hooks install` requires a `.git/` directory".into()
        ))?;
    fs::create_dir_all(&hooks_dir)
        .map_err(|e| CliError::Custom(format!("create {}: {e}", hooks_dir.display())))?;

    let target = pre_commit_path(&hooks_dir);
    if target.exists() && !force {
        // If the existing file carries our marker, treat as
        // "already installed" — exit 0 without rewriting. If it
        // doesn't, refuse to clobber a user-authored hook.
        let existing = fs::read_to_string(&target).unwrap_or_default();
        if existing.contains(HOOK_MARKER) {
            ui::note(&format!(
                "{} is already a verum-managed hook (use --force to regenerate)",
                target.display()
            ));
            return Ok(());
        }
        return Err(CliError::Custom(format!(
            "{} already exists and is NOT a verum-managed hook. \
             Pass --force to overwrite, or move it aside first.",
            target.display()
        )));
    }

    let script = pre_commit_script(env!("CARGO_PKG_VERSION"));
    fs::write(&target, script.as_bytes())
        .map_err(|e| CliError::Custom(format!("write {}: {e}", target.display())))?;
    let mut perms = fs::metadata(&target)
        .map_err(|e| CliError::Custom(format!("stat {}: {e}", target.display())))?
        .permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&target, perms)
        .map_err(|e| CliError::Custom(format!("chmod {}: {e}", target.display())))?;

    ui::success(&format!(
        "Installed pre-commit hook at {}",
        target.display()
    ));
    Ok(())
}

/// `verum hooks uninstall`.
pub fn uninstall() -> Result<()> {
    let cwd = std::env::current_dir()
        .map_err(|e| CliError::Custom(format!("read cwd: {e}")))?;
    let hooks_dir = find_hooks_dir(&cwd).ok_or_else(|| {
        CliError::Custom(
            "no enclosing git repository found — nothing to uninstall".into(),
        )
    })?;
    let target = pre_commit_path(&hooks_dir);
    if !target.exists() {
        ui::note(&format!("{}: nothing to uninstall", target.display()));
        return Ok(());
    }
    let content = fs::read_to_string(&target)
        .map_err(|e| CliError::Custom(format!("read {}: {e}", target.display())))?;
    if !content.contains(HOOK_MARKER) {
        return Err(CliError::Custom(format!(
            "{} is NOT a verum-managed hook (no header marker). \
             Refusing to remove a hand-authored or third-party script.",
            target.display()
        )));
    }
    fs::remove_file(&target)
        .map_err(|e| CliError::Custom(format!("remove {}: {e}", target.display())))?;
    ui::success(&format!("Removed {}", target.display()));
    Ok(())
}

/// `verum hooks status` — report whether the hook is installed and
/// whether it's verum-managed.
pub fn status() -> Result<()> {
    let cwd = std::env::current_dir()
        .map_err(|e| CliError::Custom(format!("read cwd: {e}")))?;
    let hooks_dir = match find_hooks_dir(&cwd) {
        Some(d) => d,
        None => {
            ui::info("not in a git repository");
            return Ok(());
        }
    };
    let target = pre_commit_path(&hooks_dir);
    if !target.exists() {
        ui::note(&format!("{}: not installed", target.display()));
        return Ok(());
    }
    let content = fs::read_to_string(&target).unwrap_or_default();
    if content.contains(HOOK_MARKER) {
        ui::success(&format!(
            "{}: installed (verum-managed)",
            target.display()
        ));
    } else {
        ui::note(&format!(
            "{}: present but NOT verum-managed (will be left alone by `uninstall`)",
            target.display()
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pre_commit_script_carries_marker() {
        let s = pre_commit_script("1.2.3");
        assert!(s.contains(HOOK_MARKER));
        assert!(s.contains("v1.2.3"));
        assert!(s.contains("verum lint"));
        assert!(s.contains("verum fmt --check"));
    }

    #[test]
    fn find_hooks_dir_walks_up() {
        let dir = tempfile::tempdir().unwrap();
        let nested = dir.path().join("a").join("b").join("c");
        std::fs::create_dir_all(&nested).unwrap();
        std::fs::create_dir_all(dir.path().join(".git").join("hooks")).unwrap();

        let hooks = find_hooks_dir(&nested).unwrap();
        let expected = dir.path().join(".git").join("hooks");
        assert_eq!(
            hooks.canonicalize().unwrap(),
            expected.canonicalize().unwrap()
        );
    }

    #[test]
    fn find_hooks_dir_none_outside_repo() {
        let dir = tempfile::tempdir().unwrap();
        assert!(find_hooks_dir(dir.path()).is_none());
    }
}
