//! DAP server transport layer.
//!
//! Implements the DAP message framing protocol (Content-Length headers + JSON body)
//! over stdio or TCP streams.

use std::io::{self, BufRead, BufReader, Write};
use std::net::TcpListener;

use crate::adapter::DebugAdapter;
use crate::types::{Event, Request, Response};

// ============================================================================
// Message IO
// ============================================================================

/// Reads a single DAP message from a reader.
///
/// DAP uses HTTP-like framing:
/// ```text
/// Content-Length: <length>\r\n
/// \r\n
/// <JSON body>
/// ```
fn read_message(reader: &mut impl BufRead) -> io::Result<Option<Request>> {
    // Read headers until we find Content-Length.
    let mut content_length: Option<usize> = None;

    loop {
        let mut header_line = String::new();
        let bytes_read = reader.read_line(&mut header_line)?;
        if bytes_read == 0 {
            // EOF — client disconnected.
            return Ok(None);
        }

        let trimmed = header_line.trim();
        if trimmed.is_empty() {
            // Empty line signals end of headers.
            break;
        }

        if let Some(len_str) = trimmed.strip_prefix("Content-Length:") {
            content_length = len_str.trim().parse::<usize>().ok();
        }
        // Ignore other headers (e.g., Content-Type).
    }

    let length = match content_length {
        Some(len) => len,
        None => {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "Missing Content-Length header",
            ));
        }
    };

    // Read the JSON body.
    let mut body = vec![0u8; length];
    reader.read_exact(&mut body)?;

    let body_str = String::from_utf8(body).map_err(|e| {
        io::Error::new(io::ErrorKind::InvalidData, format!("Invalid UTF-8: {}", e))
    })?;

    tracing::debug!("DAP recv: {}", body_str);

    let request: Request = serde_json::from_str(&body_str).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("Invalid JSON: {}", e),
        )
    })?;

    Ok(Some(request))
}

/// Writes a DAP message to a writer.
fn write_message(writer: &mut impl Write, message: &serde_json::Value) -> io::Result<()> {
    let body = serde_json::to_string(message).map_err(|e| {
        io::Error::new(
            io::ErrorKind::InvalidData,
            format!("JSON serialization error: {}", e),
        )
    })?;

    tracing::debug!("DAP send: {}", body);

    let header = format!("Content-Length: {}\r\n\r\n", body.len());
    writer.write_all(header.as_bytes())?;
    writer.write_all(body.as_bytes())?;
    writer.flush()?;

    Ok(())
}

/// Writes a Response as a DAP message.
fn write_response(writer: &mut impl Write, response: &Response) -> io::Result<()> {
    let mut value = serde_json::to_value(response).map_err(|e| {
        io::Error::new(io::ErrorKind::InvalidData, format!("Serialize error: {}", e))
    })?;
    // Inject the "type" field since Response doesn't have it as a struct field.
    if let serde_json::Value::Object(ref mut map) = value {
        map.insert("type".to_string(), serde_json::Value::String("response".to_string()));
    }
    write_message(writer, &value)
}

/// Writes an Event as a DAP message.
fn write_event(writer: &mut impl Write, event: &Event) -> io::Result<()> {
    let mut value = serde_json::to_value(event).map_err(|e| {
        io::Error::new(io::ErrorKind::InvalidData, format!("Serialize error: {}", e))
    })?;
    // Inject the "type" field.
    if let serde_json::Value::Object(ref mut map) = value {
        map.insert("type".to_string(), serde_json::Value::String("event".to_string()));
    }
    write_message(writer, &value)
}

// ============================================================================
// Server Event Loop
// ============================================================================

/// Runs the DAP event loop over a reader/writer pair.
fn run_event_loop(
    reader: &mut impl BufRead,
    writer: &mut impl Write,
) -> io::Result<()> {
    let mut adapter = DebugAdapter::new();

    loop {
        let request = match read_message(reader)? {
            Some(req) => req,
            None => {
                tracing::info!("DAP client disconnected");
                break;
            }
        };

        let is_disconnect = request.command == "disconnect";

        let (response, events) = adapter.handle_request(&request);

        // Send the response.
        write_response(writer, &response)?;

        // Send any events generated by the request.
        for event in &events {
            write_event(writer, event)?;
        }

        if is_disconnect {
            tracing::info!("DAP disconnect — shutting down");
            break;
        }
    }

    Ok(())
}

/// Runs the DAP server on stdio (stdin/stdout).
///
/// This is the standard transport for VS Code debug adapters.
pub fn run_stdio() -> io::Result<()> {
    tracing::info!("Starting Verum DAP server on stdio");

    let stdin = io::stdin();
    let stdout = io::stdout();

    let mut reader = BufReader::new(stdin.lock());
    let mut writer = stdout.lock();

    run_event_loop(&mut reader, &mut writer)
}

/// Runs the DAP server on a TCP socket.
///
/// Accepts a single connection and runs the event loop on it.
/// Useful for testing or when stdio is not available.
pub fn run_tcp(port: u16) -> io::Result<()> {
    let listener = TcpListener::bind(("127.0.0.1", port))?;
    tracing::info!("Verum DAP server listening on 127.0.0.1:{}", port);
    eprintln!("Verum DAP server listening on 127.0.0.1:{}", port);

    let (stream, addr) = listener.accept()?;
    tracing::info!("DAP client connected from {}", addr);

    let mut reader = BufReader::new(stream.try_clone()?);
    let mut writer = stream;

    run_event_loop(&mut reader, &mut writer)
}
