#![allow(
    dead_code,
    unused_imports,
    unused_variables,
    unused_mut,
    unused_must_use,
    unused_unsafe,
    deprecated,
    unexpected_cfgs,
    unused_comparisons,
    forgetting_copy_types,
    useless_ptr_null_checks,
    unused_assignments
)]
// Tests for smtlib_export module
// Migrated from src/smtlib_export.rs per CLAUDE.md standards
// FIXED (Session 23): Tests enabled
#![allow(unexpected_cfgs)]
// #![cfg(feature = "smtlib_export_tests_disabled")]

use verum_smt::smtlib_export::*;

use verum_ast::{BinOp, Expr, ExprKind, Ident, LiteralKind, Path, Span, Type, TypeKind};
use verum_common::Heap;

fn make_int_type() -> Type {
    Type {
        kind: TypeKind::Path(Path::from_ident(Ident::new("Int", Span::dummy()))),
        span: Span::dummy(),
    }
}

fn make_int_literal(value: i64) -> Expr {
    use verum_ast::literal::{IntLit, Literal};
    Expr::new(
        ExprKind::Literal(Literal {
            kind: LiteralKind::Int(IntLit {
                value: value as i128,
                suffix: None,
            }),
            span: Span::dummy(),
        }),
        Span::dummy(),
    )
}

fn make_var(name: &str) -> Expr {
    Expr::new(
        ExprKind::Path(Path::from_ident(Ident::new(name, Span::dummy()))),
        Span::dummy(),
    )
}

#[test]
fn test_exporter_creation() {
    let exporter = SmtLibExporter::new();
    assert!(exporter.var_decls.is_empty());
    assert!(exporter.assertions.is_empty());
}

#[test]
fn test_type_translation() {
    let exporter = SmtLibExporter::new();
    let int_type = make_int_type();
    let smt_type = exporter.type_to_smtlib(&int_type);
    assert_eq!(smt_type.as_str(), "Int");
}

#[test]
fn test_literal_translation() {
    let exporter = SmtLibExporter::new();
    let lit = make_int_literal(42);
    if let ExprKind::Literal(ref l) = lit.kind {
        let smt = exporter.literal_to_smtlib(l);
        assert_eq!(smt.as_str(), "42");
    }
}

#[test]
fn test_binary_op_translation() {
    let exporter = SmtLibExporter::new();

    // x + 5
    let x = make_var("x");
    let five = make_int_literal(5);
    let add_expr = Expr::new(
        ExprKind::Binary {
            op: BinOp::Add,
            left: Heap::new(x),
            right: Heap::new(five),
        },
        Span::dummy(),
    );

    let smt = exporter.expr_to_smtlib(&add_expr);
    assert_eq!(smt.as_str(), "(+ x 5)");
}

#[test]
fn test_simple_export() {
    let mut exporter = SmtLibExporter::new()
        .with_logic("QF_LIA")
        .with_check_mode(CheckMode::CheckSat);

    let int_type = make_int_type();
    exporter.declare_var("x", &int_type);

    // x > 0
    let x = make_var("x");
    let zero = make_int_literal(0);
    let gt_expr = Expr::new(
        ExprKind::Binary {
            op: BinOp::Gt,
            left: Heap::new(x),
            right: Heap::new(zero),
        },
        Span::dummy(),
    );

    exporter.assert(&gt_expr);

    let output = exporter.export();
    assert!(output.contains("(set-logic QF_LIA)"));
    assert!(output.contains("(declare-const x Int)"));
    assert!(output.contains("(assert (> x 0))"));
    assert!(output.contains("(check-sat)"));
    assert!(output.contains("(exit)"));
}

#[test]
fn test_export_verification_problem() {
    let int_type = make_int_type();

    // x > 0
    let x = make_var("x");
    let zero = make_int_literal(0);
    let predicate = Expr::new(
        ExprKind::Binary {
            op: BinOp::Gt,
            left: Heap::new(x),
            right: Heap::new(zero),
        },
        Span::dummy(),
    );

    let output = export_verification_problem(&predicate, "x", &int_type);
    assert!(output.contains("QF_LIA"));
    assert!(output.contains("(> x 0)"));
}

#[test]
fn test_benchmark_generator() {
    let mut exporter = SmtLibExporter::new().with_logic("QF_LIA");
    exporter.declare_var("x", &make_int_type());
    exporter.assert(&make_var("x"));

    let generator = BenchmarkGenerator::new("refinement-types")
        .with_difficulty(Difficulty::Medium)
        .with_description("Positive integer check");

    let benchmark = generator.generate(&exporter);
    assert!(benchmark.contains("Category: refinement-types"));
    assert!(benchmark.contains("Difficulty: Medium"));
    assert!(benchmark.contains("Generated by Verum"));
}
