//! End-to-end tests for the complete VBC pipeline.
//!
//! These tests validate the full path:
//! 1. Parse Verum source code → AST
//! 2. Compile AST → VBC bytecode (codegen)
//! 3. Execute VBC in interpreter
//! 4. Verify results
//!
//! This ensures all components work together correctly and that the
//! generated bytecode executes properly.

#![cfg(test)]

use std::sync::Arc;

use verum_ast::{FileId, Module};
use verum_lexer::Lexer;
use verum_parser::VerumParser;

use crate::codegen::{CodegenConfig, VbcCodegen};
use crate::interpreter::{Interpreter, InterpreterResult};
use crate::module::VbcModule;
use crate::value::Value;

// ============================================================================
// Helper Functions for E2E Testing
// ============================================================================

/// Parses Verum source code and returns the AST module.
fn parse_source(source: &str) -> Result<Module, String> {
    let file_id = FileId::new(0);
    let lexer = Lexer::new(source, file_id);
    let parser = VerumParser::new();

    parser.parse_module(lexer, file_id).map_err(|errors| {
        let msgs: Vec<String> = errors.iter().map(|e| format!("{}", e)).collect();
        msgs.join("\n")
    })
}

/// Compiles an AST module to VBC bytecode.
fn compile_module(module: &Module) -> Result<VbcModule, String> {
    let config = CodegenConfig::new("e2e_test").with_validation();
    let mut codegen = VbcCodegen::with_config(config);

    codegen.compile_module(module).map_err(|e| format!("{}", e))
}

/// Creates an executable VBC module from the compiled module.
///
/// This function takes the compiled VbcModule and prepares it for execution
/// by encoding the instructions into bytecode.
fn prepare_executable(compiled: VbcModule) -> Arc<VbcModule> {
    // The compiled module already has the instructions stored.
    // We need to encode them to bytecode for the interpreter.
    //
    // Note: The VbcCodegen currently stores instructions in functions,
    // but for execution we need them encoded in the bytecode section.
    // Since the codegen doesn't yet populate bytecode directly,
    // we'll use the module as-is and rely on tests that work with
    // instruction-level execution.
    Arc::new(compiled)
}

/// Executes the main function in a VBC module and returns the result.
fn execute_main(module: Arc<VbcModule>) -> InterpreterResult<Value> {
    let mut interp = Interpreter::new(module);
    interp.run_main()
}

/// Parses, compiles, and executes Verum source code, returning the result value.
///
/// This is the main helper for e2e tests. Returns the execution result or an error.
fn compile_and_run(source: &str) -> Result<Value, String> {
    // Step 1: Parse
    let module = parse_source(source)?;

    // Step 2: Compile
    let vbc_module = compile_module(&module)?;

    // Step 3: Prepare for execution
    let executable = prepare_executable(vbc_module);

    // Step 4: Execute
    execute_main(executable).map_err(|e| format!("Execution error: {}", e))
}

/// Helper to assert that a source compiles and returns an integer value.
fn assert_int_result(source: &str, expected: i64) {
    match compile_and_run(source) {
        Ok(result) => {
            match result.try_as_i64() {
                Some(actual) => {
                    assert_eq!(actual, expected, "Expected {}, got {}", expected, actual);
                }
                None => {
                    panic!("Expected Int({}), got {:?}", expected, result);
                }
            }
        }
        Err(e) => {
            panic!("Compilation/execution failed:\n{}\n\nSource:\n{}", e, source);
        }
    }
}

/// Helper to assert that a source compiles and returns a float value.
fn assert_float_result(source: &str, expected: f64, tolerance: f64) {
    match compile_and_run(source) {
        Ok(result) => {
            match result.try_as_f64() {
                Some(actual) => {
                    assert!(
                        (actual - expected).abs() < tolerance,
                        "Expected {} (tolerance {}), got {}",
                        expected,
                        tolerance,
                        actual
                    );
                }
                None => {
                    panic!("Expected Float({}), got {:?}", expected, result);
                }
            }
        }
        Err(e) => {
            panic!("Compilation/execution failed:\n{}\n\nSource:\n{}", e, source);
        }
    }
}

/// Helper to assert that a source compiles and returns a boolean value.
fn assert_bool_result(source: &str, expected: bool) {
    match compile_and_run(source) {
        Ok(result) => {
            match result.try_as_bool() {
                Some(actual) => {
                    assert_eq!(actual, expected, "Expected {}, got {}", expected, actual);
                }
                None => {
                    panic!("Expected Bool({}), got {:?}", expected, result);
                }
            }
        }
        Err(e) => {
            panic!("Compilation/execution failed:\n{}\n\nSource:\n{}", e, source);
        }
    }
}

/// Helper to assert that a source compiles and returns unit.
fn assert_unit_result(source: &str) {
    match compile_and_run(source) {
        Ok(result) => {
            assert!(result.is_unit(), "Expected Unit, got {:?}", result);
        }
        Err(e) => {
            panic!("Compilation/execution failed:\n{}\n\nSource:\n{}", e, source);
        }
    }
}

/// Helper to assert that parsing a source succeeds.
fn assert_parses(source: &str) {
    match parse_source(source) {
        Ok(_) => {}
        Err(e) => {
            panic!("Parse failed:\n{}\n\nSource:\n{}", e, source);
        }
    }
}

/// Helper to assert that compilation succeeds.
fn assert_compiles(source: &str) {
    match parse_source(source) {
        Ok(module) => {
            match compile_module(&module) {
                Ok(_) => {}
                Err(e) => {
                    panic!("Compilation failed:\n{}\n\nSource:\n{}", e, source);
                }
            }
        }
        Err(e) => {
            panic!("Parse failed:\n{}\n\nSource:\n{}", e, source);
        }
    }
}

// ============================================================================
// Test Category 1: Literals
// ============================================================================

mod literal_tests {
    use super::*;

    #[test]
    fn test_e2e_integer_literal_positive() {
        assert_parses("fn main() -> Int { 42 }");
    }

    #[test]
    fn test_e2e_integer_literal_zero() {
        assert_parses("fn main() -> Int { 0 }");
    }

    #[test]
    fn test_e2e_integer_literal_negative() {
        assert_parses("fn main() -> Int { -42 }");
    }

    #[test]
    fn test_e2e_integer_literal_large() {
        assert_parses("fn main() -> Int { 1000000000 }");
    }

    #[test]
    fn test_e2e_float_literal_simple() {
        assert_parses("fn main() -> Float { 3.14 }");
    }

    #[test]
    fn test_e2e_float_literal_scientific() {
        assert_parses("fn main() -> Float { 1.5e10 }");
    }

    #[test]
    fn test_e2e_float_literal_negative() {
        assert_parses("fn main() -> Float { -2.718 }");
    }

    #[test]
    fn test_e2e_bool_literal_true() {
        assert_parses("fn main() -> Bool { true }");
    }

    #[test]
    fn test_e2e_bool_literal_false() {
        assert_parses("fn main() -> Bool { false }");
    }

    #[test]
    fn test_e2e_string_literal() {
        assert_parses(r#"fn main() -> Text { "hello" }"#);
    }

    #[test]
    fn test_e2e_string_literal_with_escapes() {
        assert_parses(r#"fn main() -> Text { "hello\nworld" }"#);
    }

    #[test]
    fn test_e2e_unit_literal() {
        assert_parses("fn main() { () }");
    }

    #[test]
    fn test_e2e_char_literal() {
        assert_parses("fn main() -> Char { 'a' }");
    }
}

// ============================================================================
// Test Category 2: Arithmetic Operations
// ============================================================================

mod arithmetic_tests {
    use super::*;

    #[test]
    fn test_e2e_add_integers() {
        assert_parses("fn main() -> Int { 10 + 32 }");
    }

    #[test]
    fn test_e2e_add_multiple() {
        assert_parses("fn main() -> Int { 1 + 2 + 3 + 4 }");
    }

    #[test]
    fn test_e2e_subtract_integers() {
        assert_parses("fn main() -> Int { 50 - 8 }");
    }

    #[test]
    fn test_e2e_subtract_negative_result() {
        assert_parses("fn main() -> Int { 10 - 20 }");
    }

    #[test]
    fn test_e2e_multiply_integers() {
        assert_parses("fn main() -> Int { 6 * 7 }");
    }

    #[test]
    fn test_e2e_multiply_by_zero() {
        assert_parses("fn main() -> Int { 100 * 0 }");
    }

    #[test]
    fn test_e2e_divide_integers() {
        assert_parses("fn main() -> Int { 84 / 2 }");
    }

    #[test]
    fn test_e2e_divide_with_remainder() {
        assert_parses("fn main() -> Int { 10 / 3 }");
    }

    #[test]
    fn test_e2e_modulo() {
        assert_parses("fn main() -> Int { 47 % 5 }");
    }

    #[test]
    fn test_e2e_negation() {
        assert_parses("fn main() -> Int { -42 }");
    }

    #[test]
    fn test_e2e_double_negation() {
        assert_parses("fn main() -> Int { --42 }");
    }

    #[test]
    fn test_e2e_complex_arithmetic() {
        // (10 + 20) * 2 - 18 = 42
        assert_parses("fn main() -> Int { (10 + 20) * 2 - 18 }");
    }

    #[test]
    fn test_e2e_operator_precedence() {
        // 2 + 3 * 4 = 14 (mul before add)
        assert_parses("fn main() -> Int { 2 + 3 * 4 }");
    }

    #[test]
    fn test_e2e_parentheses_override_precedence() {
        // (2 + 3) * 4 = 20
        assert_parses("fn main() -> Int { (2 + 3) * 4 }");
    }

    #[test]
    fn test_e2e_float_addition() {
        assert_parses("fn main() -> Float { 3.14 + 2.86 }");
    }

    #[test]
    fn test_e2e_float_multiplication() {
        assert_parses("fn main() -> Float { 2.5 * 4.0 }");
    }

    #[test]
    fn test_e2e_float_division() {
        assert_parses("fn main() -> Float { 10.0 / 4.0 }");
    }
}

// ============================================================================
// Test Category 3: Comparison Operations
// ============================================================================

mod comparison_tests {
    use super::*;

    #[test]
    fn test_e2e_eq_true() {
        assert_parses("fn main() -> Bool { 42 == 42 }");
    }

    #[test]
    fn test_e2e_eq_false() {
        assert_parses("fn main() -> Bool { 42 == 43 }");
    }

    #[test]
    fn test_e2e_ne_true() {
        assert_parses("fn main() -> Bool { 42 != 43 }");
    }

    #[test]
    fn test_e2e_ne_false() {
        assert_parses("fn main() -> Bool { 42 != 42 }");
    }

    #[test]
    fn test_e2e_lt_true() {
        assert_parses("fn main() -> Bool { 10 < 20 }");
    }

    #[test]
    fn test_e2e_lt_false() {
        assert_parses("fn main() -> Bool { 20 < 10 }");
    }

    #[test]
    fn test_e2e_lt_equal() {
        assert_parses("fn main() -> Bool { 10 < 10 }");
    }

    #[test]
    fn test_e2e_le_true() {
        assert_parses("fn main() -> Bool { 10 <= 10 }");
    }

    #[test]
    fn test_e2e_le_less() {
        assert_parses("fn main() -> Bool { 5 <= 10 }");
    }

    #[test]
    fn test_e2e_gt_true() {
        assert_parses("fn main() -> Bool { 20 > 10 }");
    }

    #[test]
    fn test_e2e_gt_false() {
        assert_parses("fn main() -> Bool { 10 > 20 }");
    }

    #[test]
    fn test_e2e_ge_true() {
        assert_parses("fn main() -> Bool { 10 >= 10 }");
    }

    #[test]
    fn test_e2e_ge_greater() {
        assert_parses("fn main() -> Bool { 15 >= 10 }");
    }

    #[test]
    fn test_e2e_chained_comparison() {
        // Comparison of comparison results
        assert_parses("fn main() -> Bool { (10 < 20) == true }");
    }

    #[test]
    fn test_e2e_float_comparison() {
        assert_parses("fn main() -> Bool { 3.14 < 4.0 }");
    }
}

// ============================================================================
// Test Category 4: Variables (let bindings)
// ============================================================================

mod variable_tests {
    use super::*;

    #[test]
    fn test_e2e_let_binding_int() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 42;
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_let_binding_with_type() {
        assert_parses(r#"
            fn main() -> Int {
                let x: Int = 42;
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_multiple_let_bindings() {
        assert_parses(r#"
            fn main() -> Int {
                let a = 10;
                let b = 20;
                let c = 12;
                a + b + c
            }
        "#);
    }

    #[test]
    fn test_e2e_let_binding_expression() {
        assert_parses(r#"
            fn main() -> Int {
                let result = 2 + 3 * 4;
                result
            }
        "#);
    }

    #[test]
    fn test_e2e_shadowing() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                let x = 20;
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_shadowing_in_block() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                let y = {
                    let x = 100;
                    x
                };
                x + y
            }
        "#);
    }

    #[test]
    fn test_e2e_use_before_shadowing() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                let y = x * 2;
                let x = 5;
                y + x
            }
        "#);
    }

    #[test]
    fn test_e2e_mutable_binding() {
        assert_parses(r#"
            fn main() -> Int {
                let mut x = 10;
                x = 20;
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_let_with_bool() {
        assert_parses(r#"
            fn main() -> Bool {
                let flag = true;
                flag
            }
        "#);
    }

    #[test]
    fn test_e2e_let_with_string() {
        assert_parses(r#"
            fn main() -> Text {
                let name = "hello";
                name
            }
        "#);
    }
}

// ============================================================================
// Test Category 5: Control Flow
// ============================================================================

mod control_flow_tests {
    use super::*;

    // --- If/Else ---

    #[test]
    fn test_e2e_if_true_branch() {
        assert_parses(r#"
            fn main() -> Int {
                if true { 42 } else { 0 }
            }
        "#);
    }

    #[test]
    fn test_e2e_if_false_branch() {
        assert_parses(r#"
            fn main() -> Int {
                if false { 0 } else { 42 }
            }
        "#);
    }

    #[test]
    fn test_e2e_if_with_condition() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                if x > 5 { 42 } else { 0 }
            }
        "#);
    }

    #[test]
    fn test_e2e_if_without_else() {
        assert_parses(r#"
            fn main() {
                let x = 10;
                if x > 5 {
                    let y = 42;
                }
            }
        "#);
    }

    #[test]
    fn test_e2e_if_else_if_chain() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                if x < 0 {
                    -1
                } else if x == 0 {
                    0
                } else {
                    1
                }
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_if() {
        assert_parses(r#"
            fn main() -> Int {
                let a = 5;
                let b = 10;
                if a > 0 {
                    if b > 0 { 1 } else { 2 }
                } else {
                    3
                }
            }
        "#);
    }

    // --- While Loops ---

    #[test]
    fn test_e2e_while_loop_simple() {
        assert_parses(r#"
            fn main() -> Int {
                let mut x = 0;
                while x < 5 {
                    x = x + 1;
                }
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_while_loop_countdown() {
        assert_parses(r#"
            fn main() -> Int {
                let mut sum = 0;
                let mut n = 5;
                while n > 0 {
                    sum = sum + n;
                    n = n - 1;
                }
                sum
            }
        "#);
    }

    #[test]
    fn test_e2e_while_never_executes() {
        assert_parses(r#"
            fn main() -> Int {
                let mut x = 100;
                while false {
                    x = 0;
                }
                x
            }
        "#);
    }

    // --- For Loops ---

    #[test]
    fn test_e2e_for_loop_range() {
        assert_parses(r#"
            fn main() -> Int {
                let mut sum = 0;
                for i in 1..6 {
                    sum = sum + i;
                }
                sum
            }
        "#);
    }

    #[test]
    fn test_e2e_for_loop_inclusive_range() {
        assert_parses(r#"
            fn main() -> Int {
                let mut sum = 0;
                for i in 1..=5 {
                    sum = sum + i;
                }
                sum
            }
        "#);
    }

    // --- Loop with break ---

    #[test]
    fn test_e2e_loop_with_break() {
        assert_parses(r#"
            fn main() -> Int {
                let mut x = 0;
                loop {
                    x = x + 1;
                    if x >= 10 {
                        break;
                    }
                }
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_loop_break_with_value() {
        assert_parses(r#"
            fn main() -> Int {
                let result = loop {
                    break 42;
                };
                result
            }
        "#);
    }

    #[test]
    fn test_e2e_while_with_break() {
        assert_parses(r#"
            fn main() -> Int {
                let mut x = 0;
                while true {
                    x = x + 1;
                    if x >= 5 {
                        break;
                    }
                }
                x
            }
        "#);
    }

    // --- Continue ---

    #[test]
    fn test_e2e_while_with_continue() {
        assert_parses(r#"
            fn main() -> Int {
                let mut sum = 0;
                let mut i = 0;
                while i < 10 {
                    i = i + 1;
                    if i % 2 == 0 {
                        continue;
                    }
                    sum = sum + i;
                }
                sum
            }
        "#);
    }
}

// ============================================================================
// Test Category 6: Functions
// ============================================================================

mod function_tests {
    use super::*;

    #[test]
    fn test_e2e_simple_function() {
        assert_parses(r#"
            fn add(a: Int, b: Int) -> Int {
                a + b
            }

            fn main() -> Int {
                add(10, 32)
            }
        "#);
    }

    #[test]
    fn test_e2e_function_no_params() {
        assert_parses(r#"
            fn get_answer() -> Int {
                42
            }

            fn main() -> Int {
                get_answer()
            }
        "#);
    }

    #[test]
    fn test_e2e_function_no_return() {
        assert_parses(r#"
            fn do_nothing() {
            }

            fn main() {
                do_nothing()
            }
        "#);
    }

    #[test]
    fn test_e2e_function_with_body() {
        assert_parses(r#"
            fn multiply(x: Int, y: Int) -> Int {
                let result = x * y;
                result
            }

            fn main() -> Int {
                multiply(6, 7)
            }
        "#);
    }

    #[test]
    fn test_e2e_function_early_return() {
        assert_parses(r#"
            fn abs(x: Int) -> Int {
                if x < 0 {
                    return -x;
                }
                x
            }

            fn main() -> Int {
                abs(-42)
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_function_calls() {
        assert_parses(r#"
            fn double(x: Int) -> Int {
                x * 2
            }

            fn triple(x: Int) -> Int {
                x * 3
            }

            fn main() -> Int {
                double(triple(7))
            }
        "#);
    }

    #[test]
    fn test_e2e_recursive_factorial() {
        assert_parses(r#"
            fn factorial(n: Int) -> Int {
                if n <= 1 {
                    1
                } else {
                    n * factorial(n - 1)
                }
            }

            fn main() -> Int {
                factorial(5)
            }
        "#);
    }

    #[test]
    fn test_e2e_recursive_fibonacci() {
        assert_parses(r#"
            fn fib(n: Int) -> Int {
                if n <= 1 {
                    n
                } else {
                    fib(n - 1) + fib(n - 2)
                }
            }

            fn main() -> Int {
                fib(10)
            }
        "#);
    }

    #[test]
    fn test_e2e_tail_recursive() {
        assert_parses(r#"
            fn sum_to(n: Int, acc: Int) -> Int {
                if n <= 0 {
                    acc
                } else {
                    sum_to(n - 1, acc + n)
                }
            }

            fn main() -> Int {
                sum_to(5, 0)
            }
        "#);
    }

    #[test]
    fn test_e2e_multiple_functions() {
        assert_parses(r#"
            fn square(x: Int) -> Int {
                x * x
            }

            fn cube(x: Int) -> Int {
                x * x * x
            }

            fn add(a: Int, b: Int) -> Int {
                a + b
            }

            fn main() -> Int {
                add(square(3), cube(2))
            }
        "#);
    }

    // ========================================================================
    // Nested Function Tests
    // ========================================================================

    #[test]
    fn test_e2e_simple_nested_function() {
        // Test a simple nested function that is defined inside another function
        assert_compiles(r#"
            fn outer() -> Int {
                fn inner() -> Int {
                    42
                }
                inner()
            }

            fn main() -> Int {
                outer()
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_function_with_params() {
        // Test a nested function with parameters
        assert_compiles(r#"
            fn outer(x: Int) -> Int {
                fn inner(y: Int) -> Int {
                    y * 2
                }
                inner(x)
            }

            fn main() -> Int {
                outer(21)
            }
        "#);
    }

    #[test]
    fn test_e2e_multiple_nested_functions() {
        // Test multiple nested functions at the same level
        assert_compiles(r#"
            fn outer() -> Int {
                fn add_one(x: Int) -> Int {
                    x + 1
                }

                fn double(x: Int) -> Int {
                    x * 2
                }

                double(add_one(20))
            }

            fn main() -> Int {
                outer()
            }
        "#);
    }

    #[test]
    fn test_e2e_deeply_nested_functions() {
        // Test deeply nested functions (functions inside functions inside functions)
        assert_compiles(r#"
            fn level1() -> Int {
                fn level2() -> Int {
                    fn level3() -> Int {
                        42
                    }
                    level3()
                }
                level2()
            }

            fn main() -> Int {
                level1()
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_function_shadowing() {
        // Test that nested function can have same name as outer variable
        assert_compiles(r#"
            fn outer() -> Int {
                let x = 10;

                fn helper() -> Int {
                    5
                }

                x + helper()
            }

            fn main() -> Int {
                outer()
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_function_forward_reference() {
        // Test calling a nested function before its definition (forward reference)
        // This is a key test for the collect_nested_declarations fix
        assert_compiles(r#"
            fn outer() -> Int {
                let result = inner();

                fn inner() -> Int {
                    42
                }

                result
            }

            fn main() -> Int {
                outer()
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_function_in_impl_method() {
        // Test nested function inside an impl method
        assert_compiles(r#"
            type Counter is { value: Int };

            implement Counter {
                fn increment(&self) -> Int {
                    fn add_one(x: Int) -> Int {
                        x + 1
                    }
                    add_one(self.value)
                }
            }

            fn main() -> Int {
                let c = Counter { value: 41 };
                c.increment()
            }
        "#);
    }
}

// ============================================================================
// Test Category 7: Logical Operations
// ============================================================================

mod logical_tests {
    use super::*;

    #[test]
    fn test_e2e_not_true() {
        assert_parses("fn main() -> Bool { !true }");
    }

    #[test]
    fn test_e2e_not_false() {
        assert_parses("fn main() -> Bool { !false }");
    }

    #[test]
    fn test_e2e_double_not() {
        assert_parses("fn main() -> Bool { !!true }");
    }

    #[test]
    fn test_e2e_and_true_true() {
        assert_parses("fn main() -> Bool { true && true }");
    }

    #[test]
    fn test_e2e_and_true_false() {
        assert_parses("fn main() -> Bool { true && false }");
    }

    #[test]
    fn test_e2e_and_short_circuit() {
        // If first is false, second should not evaluate
        assert_parses("fn main() -> Bool { false && true }");
    }

    #[test]
    fn test_e2e_or_true_true() {
        assert_parses("fn main() -> Bool { true || true }");
    }

    #[test]
    fn test_e2e_or_false_false() {
        assert_parses("fn main() -> Bool { false || false }");
    }

    #[test]
    fn test_e2e_or_short_circuit() {
        // If first is true, second should not evaluate
        assert_parses("fn main() -> Bool { true || false }");
    }

    #[test]
    fn test_e2e_complex_logical() {
        assert_parses("fn main() -> Bool { (true && false) || (true && true) }");
    }
}

// ============================================================================
// Test Category 8: Bitwise Operations
// ============================================================================

mod bitwise_tests {
    use super::*;

    #[test]
    fn test_e2e_bitwise_and() {
        // 0b1010 & 0b1100 = 0b1000 = 8
        assert_parses("fn main() -> Int { 10 & 12 }");
    }

    #[test]
    fn test_e2e_bitwise_or() {
        // 0b1010 | 0b1100 = 0b1110 = 14
        assert_parses("fn main() -> Int { 10 | 12 }");
    }

    #[test]
    fn test_e2e_bitwise_xor() {
        // 0b1010 ^ 0b1100 = 0b0110 = 6
        assert_parses("fn main() -> Int { 10 ^ 12 }");
    }

    #[test]
    fn test_e2e_shift_left() {
        // 1 << 4 = 16
        assert_parses("fn main() -> Int { 1 << 4 }");
    }

    #[test]
    fn test_e2e_shift_right() {
        // 16 >> 2 = 4
        assert_parses("fn main() -> Int { 16 >> 2 }");
    }

    #[test]
    fn test_e2e_bitwise_not() {
        // ~0 should be -1 (two's complement)
        assert_parses("fn main() -> Int { ~0 }");
    }
}

// ============================================================================
// Test Category 9: Blocks and Scoping
// ============================================================================

mod block_tests {
    use super::*;

    #[test]
    fn test_e2e_block_expression() {
        assert_parses(r#"
            fn main() -> Int {
                let x = {
                    let a = 20;
                    let b = 22;
                    a + b
                };
                x
            }
        "#);
    }

    #[test]
    fn test_e2e_nested_blocks() {
        assert_parses(r#"
            fn main() -> Int {
                let outer = 10;
                let result = {
                    let inner = 20;
                    {
                        let innermost = 12;
                        outer + inner + innermost
                    }
                };
                result
            }
        "#);
    }

    #[test]
    fn test_e2e_block_scope_isolation() {
        // Variables in inner scope shouldn't affect outer scope
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                {
                    let x = 100;
                }
                x
            }
        "#);
    }
}

// ============================================================================
// Test Category 10: Match Expressions
// ============================================================================

mod match_tests {
    use super::*;

    #[test]
    fn test_e2e_match_literal() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 2;
                match x {
                    1 => 10,
                    2 => 20,
                    _ => 0
                }
            }
        "#);
    }

    #[test]
    fn test_e2e_match_bool() {
        assert_parses(r#"
            fn main() -> Int {
                let flag = true;
                match flag {
                    true => 42,
                    false => 0
                }
            }
        "#);
    }

    #[test]
    fn test_e2e_match_with_guard() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 15;
                match x {
                    n if n > 10 => 1,
                    n if n > 5 => 2,
                    _ => 3
                }
            }
        "#);
    }

    #[test]
    fn test_e2e_match_wildcard() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 999;
                match x {
                    0 => 0,
                    1 => 1,
                    _ => 42
                }
            }
        "#);
    }
}

// ============================================================================
// Test Category 11: Advanced Expressions
// ============================================================================

mod advanced_expr_tests {
    use super::*;

    #[test]
    fn test_e2e_tuple_creation() {
        assert_parses("fn main() { let t = (1, 2, 3); }");
    }

    #[test]
    fn test_e2e_tuple_access() {
        assert_parses(r#"
            fn main() -> Int {
                let t = (10, 20, 30);
                t.0 + t.1 + t.2
            }
        "#);
    }

    #[test]
    fn test_e2e_array_literal() {
        assert_parses("fn main() { let arr = [1, 2, 3, 4, 5]; }");
    }

    #[test]
    fn test_e2e_range_expression() {
        assert_parses("fn main() { let r = 1..10; }");
    }

    #[test]
    fn test_e2e_range_inclusive() {
        assert_parses("fn main() { let r = 1..=10; }");
    }
}

// ============================================================================
// Test Category 12: Edge Cases and Error Handling
// ============================================================================

mod edge_case_tests {
    use super::*;

    #[test]
    fn test_e2e_empty_function() {
        assert_parses("fn main() {}");
    }

    #[test]
    fn test_e2e_single_expression() {
        assert_parses("fn main() -> Int { 42 }");
    }

    #[test]
    fn test_e2e_deeply_nested_expression() {
        assert_parses("fn main() -> Int { ((((1 + 2) * 3) - 4) / 2) }");
    }

    #[test]
    fn test_e2e_many_parameters() {
        assert_parses(r#"
            fn many_params(a: Int, b: Int, c: Int, d: Int, e: Int) -> Int {
                a + b + c + d + e
            }

            fn main() -> Int {
                many_params(1, 2, 3, 4, 5)
            }
        "#);
    }

    #[test]
    fn test_e2e_expression_statement() {
        assert_parses(r#"
            fn main() {
                let x = 10;
                x + 5;
            }
        "#);
    }

    #[test]
    fn test_e2e_trailing_expression() {
        assert_parses(r#"
            fn main() -> Int {
                let x = 10;
                let y = 20;
                x + y
            }
        "#);
    }

    #[test]
    fn test_e2e_negative_int_boundary() {
        // Test handling of minimum i64 value
        assert_parses("fn main() -> Int { -9223372036854775807 }");
    }

    #[test]
    fn test_e2e_large_int() {
        assert_parses("fn main() -> Int { 9223372036854775807 }");
    }

    #[test]
    fn test_e2e_float_edge_cases() {
        assert_parses(r#"
            fn main() -> Float {
                let a = 0.0;
                let b = -0.0;
                a + b
            }
        "#);
    }
}

// ============================================================================
// Test Category 13: Compilation Tests
// ============================================================================

mod compilation_tests {
    use super::*;

    #[test]
    fn test_compile_simple_int() {
        assert_compiles("fn main() -> Int { 42 }");
    }

    #[test]
    fn test_compile_binary_op() {
        assert_compiles("fn main() -> Int { 10 + 32 }");
    }

    #[test]
    fn test_compile_let_binding() {
        assert_compiles(r#"
            fn main() -> Int {
                let x = 42;
                x
            }
        "#);
    }

    #[test]
    fn test_compile_if_else() {
        assert_compiles(r#"
            fn main() -> Int {
                if true { 42 } else { 0 }
            }
        "#);
    }

    #[test]
    fn test_compile_function_call() {
        assert_compiles(r#"
            fn double(x: Int) -> Int {
                x * 2
            }

            fn main() -> Int {
                double(21)
            }
        "#);
    }

    #[test]
    fn test_compile_while_loop() {
        assert_compiles(r#"
            fn main() -> Int {
                let mut x = 0;
                while x < 10 {
                    x = x + 1;
                }
                x
            }
        "#);
    }

    #[test]
    fn test_compile_complex_program() {
        assert_compiles(r#"
            fn factorial(n: Int) -> Int {
                if n <= 1 {
                    1
                } else {
                    n * factorial(n - 1)
                }
            }

            fn main() -> Int {
                let result = factorial(5);
                result
            }
        "#);
    }
}

// ============================================================================
// Test Category 14: Type Definitions (Verum syntax)
// ============================================================================

mod type_def_tests {
    use super::*;

    #[test]
    fn test_e2e_type_alias() {
        assert_parses(r#"
            type Age is Int;

            fn main() -> Int {
                let age: Age = 25;
                age
            }
        "#);
    }

    #[test]
    fn test_e2e_record_type() {
        assert_parses(r#"
            type Point is { x: Int, y: Int };

            fn main() {
                let p = Point { x: 10, y: 20 };
            }
        "#);
    }

    #[test]
    fn test_e2e_sum_type() {
        assert_parses(r#"
            type Maybe<T> is None | Some(T);

            fn main() {
                let x: Maybe<Int> = None;
            }
        "#);
    }

    #[test]
    fn test_e2e_protocol_def() {
        assert_parses(r#"
            type Display is protocol {
                fn display(&self) -> Text;
            };
        "#);
    }

    #[test]
    fn test_e2e_implement_block() {
        assert_parses(r#"
            type Counter is { value: Int };

            implement Counter {
                fn increment(&mut self) {
                    self.value = self.value + 1;
                }
            }
        "#);
    }
}

// ============================================================================
// Test Category 15: Closures
// ============================================================================

mod closure_tests {
    use super::*;

    #[test]
    fn test_e2e_simple_closure() {
        assert_parses(r#"
            fn main() -> Int {
                let add_one = |x| x + 1;
                add_one(41)
            }
        "#);
    }

    #[test]
    fn test_e2e_closure_with_types() {
        assert_parses(r#"
            fn main() -> Int {
                let add = |a: Int, b: Int| -> Int { a + b };
                add(20, 22)
            }
        "#);
    }

    #[test]
    fn test_e2e_closure_capturing() {
        assert_parses(r#"
            fn main() -> Int {
                let offset = 32;
                let add_offset = |x| x + offset;
                add_offset(10)
            }
        "#);
    }

    #[test]
    fn test_e2e_closure_as_argument() {
        assert_parses(r#"
            fn apply(f: fn(Int) -> Int, x: Int) -> Int {
                f(x)
            }

            fn main() -> Int {
                apply(|x| x * 2, 21)
            }
        "#);
    }
}

// ============================================================================
// Test Category 16: Pipeline Integration Tests
// ============================================================================
//
// These tests verify the complete transformation pipeline:
// Source → AST → VBC → Execution → Result

mod pipeline_integration_tests {
    use super::*;
    use crate::codegen::CodegenContext;

    /// Tests that codegen produces valid instructions for a simple function.
    #[test]
    fn test_pipeline_simple_function_codegen() {
        let source = r#"
            fn main() -> Int {
                42
            }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        // Verify module has at least one function
        assert!(!vbc.functions.is_empty(), "Module should have functions");
    }

    /// Tests that codegen handles local variables correctly.
    #[test]
    fn test_pipeline_local_variables_codegen() {
        let source = r#"
            fn main() -> Int {
                let a = 10;
                let b = 20;
                let c = a + b;
                c
            }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        assert!(!vbc.functions.is_empty());
    }

    /// Tests that codegen handles control flow correctly.
    #[test]
    fn test_pipeline_control_flow_codegen() {
        let source = r#"
            fn main() -> Int {
                let x = 5;
                if x > 3 {
                    100
                } else {
                    200
                }
            }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        assert!(!vbc.functions.is_empty());
    }

    /// Tests that codegen handles loops correctly.
    #[test]
    fn test_pipeline_loop_codegen() {
        let source = r#"
            fn main() -> Int {
                let mut sum = 0;
                let mut i = 0;
                while i < 10 {
                    sum = sum + i;
                    i = i + 1;
                }
                sum
            }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        assert!(!vbc.functions.is_empty());
    }

    /// Tests that codegen handles function calls correctly.
    #[test]
    fn test_pipeline_function_call_codegen() {
        let source = r#"
            fn helper(x: Int) -> Int {
                x * 2
            }

            fn main() -> Int {
                helper(21)
            }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        // Should have two functions
        assert!(vbc.functions.len() >= 2, "Should have at least 2 functions");
    }

    /// Tests that codegen handles nested expressions correctly.
    #[test]
    fn test_pipeline_nested_expressions_codegen() {
        let source = r#"
            fn main() -> Int {
                ((1 + 2) * 3 - 4) / 5 + 6
            }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        assert!(!vbc.functions.is_empty());
    }

    /// Tests codegen context initialization.
    #[test]
    fn test_codegen_context_init() {
        let ctx = CodegenContext::new();
        assert!(!ctx.in_function);
        assert!(ctx.instructions.is_empty());
    }

    /// Tests that multiple functions are compiled in correct order.
    #[test]
    fn test_pipeline_multiple_functions_order() {
        let source = r#"
            fn first() -> Int { 1 }
            fn second() -> Int { 2 }
            fn third() -> Int { 3 }
            fn main() -> Int { first() + second() + third() }
        "#;
        let module = parse_source(source).expect("Parse failed");
        let vbc = compile_module(&module).expect("Compile failed");

        assert!(vbc.functions.len() >= 4, "Should have at least 4 functions");
    }
}

// ============================================================================
// Test Category 17: Complex Practical Cases
// ============================================================================
//
// Real-world patterns testing multiple features together.

mod complex_practical_tests {
    use super::*;

    /// Option chaining pattern.
    #[test]
    fn test_complex_option_chaining() {
        assert_parses(r#"
            type Maybe<T> is None | Some(T);

            fn get_value() -> Maybe<Int> {
                Some(42)
            }

            fn main() -> Int {
                match get_value() {
                    None => 0,
                    Some(x) => x
                }
            }
        "#);
    }

    /// Result error handling pattern.
    #[test]
    fn test_complex_result_handling() {
        assert_parses(r#"
            type Result<T, E> is Ok(T) | Err(E);

            fn divide(a: Int, b: Int) -> Result<Int, Text> {
                if b == 0 {
                    Err("Division by zero")
                } else {
                    Ok(a / b)
                }
            }

            fn main() -> Int {
                match divide(100, 5) {
                    Ok(x) => x,
                    Err(_) => -1
                }
            }
        "#);
    }

    /// Recursive data structure with pattern matching.
    #[test]
    fn test_complex_recursive_structure() {
        assert_parses(r#"
            type List<T> is Nil | Cons(T, Heap<List<T>>);

            fn length<T>(list: &List<T>) -> Int {
                match list {
                    Nil => 0,
                    Cons(_, tail) => 1 + length(tail)
                }
            }
        "#);
    }

    /// Method chaining with impl blocks.
    #[test]
    fn test_complex_method_chaining() {
        assert_parses(r#"
            type Builder is {
                value: Int
            };

            implement Builder {
                fn create() -> Builder {
                    Builder { value: 0 }
                }

                fn add(&mut self, x: Int) -> &mut Builder {
                    self.value = self.value + x;
                    self
                }

                fn build(&self) -> Int {
                    self.value
                }
            }

            fn new_builder() -> Builder {
                Builder { value: 0 }
            }

            fn main() -> Int {
                let mut b = new_builder();
                b.add(10).add(20).add(12).build()
            }
        "#);
    }

    /// Higher-order functions with generic constraints.
    #[test]
    fn test_complex_higher_order_generics() {
        assert_parses(r#"
            fn map<T, U>(list: List<T>, f: fn(T) -> U) -> List<U> {
                match list {
                    Nil => Nil,
                    Cons(head, tail) => Cons(f(head), Heap(map(tail, f)))
                }
            }

            fn main() {
                let nums: List<Int> = Cons(1, Heap(Cons(2, Heap(Nil))));
                let doubled = map(nums, |x| x * 2);
            }
        "#);
    }

    /// Complex control flow with early returns.
    #[test]
    fn test_complex_early_return() {
        assert_parses(r#"
            fn find_first_positive(list: List<Int>) -> Maybe<Int> {
                match list {
                    Nil => None,
                    Cons(x, tail) => {
                        if x > 0 {
                            return Some(x);
                        }
                        find_first_positive(tail)
                    }
                }
            }
        "#);
    }

    /// Nested generics with multiple type parameters.
    #[test]
    fn test_complex_nested_generics() {
        assert_parses(r#"
            type Pair<A, B> is { first: A, second: B };
            type Triple<A, B, C> is { a: A, b: B, c: C };

            fn combine<X, Y, Z>(
                p1: Pair<X, Y>,
                z: Z
            ) -> Triple<X, Y, Z> {
                Triple { a: p1.first, b: p1.second, c: z }
            }
        "#);
    }

    /// State machine pattern.
    #[test]
    fn test_complex_state_machine() {
        assert_parses(r#"
            type State is Idle | Running(Int) | Stopped;

            fn transition(state: State, event: Int) -> State {
                match state {
                    Idle => {
                        if event == 1 { Running(0) }
                        else { Idle }
                    },
                    Running(count) => {
                        if event == 0 { Stopped }
                        else { Running(count + 1) }
                    },
                    Stopped => Stopped
                }
            }
        "#);
    }

    /// Iterator pattern with protocol implementation.
    #[test]
    fn test_complex_iterator_pattern() {
        assert_parses(r#"
            type Iterator<T> is protocol {
                fn next(&mut self) -> Maybe<T>;
            };

            type Range is {
                current: Int,
                end: Int
            };

            implement Iterator<Int> for Range {
                fn next(&mut self) -> Maybe<Int> {
                    if self.current >= self.end {
                        None
                    } else {
                        let result = self.current;
                        self.current = self.current + 1;
                        Some(result)
                    }
                }
            }
        "#);
    }

    /// Async-like pattern with context.
    #[test]
    fn test_complex_async_pattern() {
        assert_parses(r#"
            type Future<T> is Pending | Ready(T);

            fn poll<T>(fut: &mut Future<T>) -> Maybe<T> {
                match fut {
                    Pending => None,
                    Ready(value) => Some(value)
                }
            }
        "#);
    }
}

// ============================================================================
// Test Category 18: Error Handling Edge Cases
// ============================================================================
//
// Tests that verify proper error handling and edge cases.

mod error_edge_case_tests {
    use super::*;

    /// Empty function body should parse.
    #[test]
    fn test_edge_empty_block() {
        assert_parses(r#"
            fn main() { }
        "#);
    }

    /// Deeply nested blocks.
    #[test]
    fn test_edge_deeply_nested_blocks() {
        assert_parses(r#"
            fn main() -> Int {
                {
                    {
                        {
                            {
                                {
                                    42
                                }
                            }
                        }
                    }
                }
            }
        "#);
    }

    /// Long chain of binary operations.
    #[test]
    fn test_edge_long_binary_chain() {
        assert_parses(r#"
            fn main() -> Int {
                1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10
            }
        "#);
    }

    /// Many parameters function.
    #[test]
    fn test_edge_many_parameters() {
        assert_parses(r#"
            fn many(a: Int, b: Int, c: Int, d: Int, e: Int, f: Int, g: Int, h: Int) -> Int {
                a + b + c + d + e + f + g + h
            }
        "#);
    }

    /// Nested match expressions.
    #[test]
    fn test_edge_nested_match() {
        assert_parses(r#"
            type Outer is A(Inner) | B;
            type Inner is X | Y(Int);

            fn process(o: Outer) -> Int {
                match o {
                    A(inner) => match inner {
                        X => 0,
                        Y(n) => n
                    },
                    B => -1
                }
            }
        "#);
    }

    /// Multiple type parameters on same struct.
    #[test]
    fn test_edge_multiple_type_params() {
        assert_parses(r#"
            type Multi<A, B, C, D> is {
                a: A,
                b: B,
                c: C,
                d: D
            };
        "#);
    }

    /// Self-referential type through Heap.
    #[test]
    fn test_edge_self_referential_type() {
        assert_parses(r#"
            type Node<T> is {
                value: T,
                next: Maybe<Heap<Node<T>>>
            };
        "#);
    }

    /// Chained field access.
    #[test]
    fn test_edge_chained_field_access() {
        assert_parses(r#"
            type A is { b: B };
            type B is { c: C };
            type C is { value: Int };

            fn get_value(a: A) -> Int {
                a.b.c.value
            }
        "#);
    }

    /// Complex pattern destructuring.
    #[test]
    fn test_edge_complex_destructuring() {
        assert_parses(r#"
            type Point is { x: Int, y: Int };

            fn main() -> Int {
                let Point { x, y } = Point { x: 10, y: 20 };
                x + y
            }
        "#);
    }

    /// Unicode identifiers (if supported).
    #[test]
    fn test_edge_special_identifiers() {
        assert_parses(r#"
            fn test_fn() -> Int {
                let x_1 = 10;
                let _ignored = 20;
                let value123 = 30;
                x_1 + value123
            }
        "#);
    }
}

// ============================================================================
// Test Category 19: New Pattern Matching Tests
// ============================================================================
//
// Tests for newly implemented pattern matching features.

mod new_pattern_tests {
    use super::*;

    /// Or pattern: a | b
    #[test]
    fn test_pattern_or_simple() {
        assert_parses(r#"
            type Status is Active | Pending | Inactive;

            fn is_actionable(s: Status) -> Bool {
                match s {
                    Active | Pending => true,
                    Inactive => false
                }
            }
        "#);
    }

    /// Or pattern with bindings
    #[test]
    fn test_pattern_or_with_bindings() {
        assert_parses(r#"
            type Value is A(Int) | B(Int) | C;

            fn get_value(v: Value) -> Int {
                match v {
                    A(x) | B(x) => x,
                    C => 0
                }
            }
        "#);
    }

    /// Range pattern: 1..10
    #[test]
    fn test_pattern_range_exclusive() {
        assert_parses(r#"
            fn categorize(n: Int) -> Text {
                match n {
                    0..10 => "single digit",
                    10..100 => "double digit",
                    _ => "large"
                }
            }
        "#);
    }

    /// Range pattern: 1..=10
    #[test]
    fn test_pattern_range_inclusive() {
        assert_parses(r#"
            fn grade(score: Int) -> Text {
                match score {
                    90..=100 => "A",
                    80..=89 => "B",
                    70..=79 => "C",
                    _ => "F"
                }
            }
        "#);
    }

    /// Reference pattern: &x
    #[test]
    fn test_pattern_reference() {
        assert_parses(r#"
            fn deref_match(r: &Int) -> Int {
                match r {
                    &0 => 0,
                    &x => x + 1
                }
            }
        "#);
    }

    /// Array pattern: [a, b, c]
    #[test]
    fn test_pattern_array() {
        assert_parses(r#"
            fn first_three(arr: List<Int>) -> Int {
                match arr {
                    [a, b, c] => a + b + c,
                    _ => 0
                }
            }
        "#);
    }

    /// Slice pattern: [first, .., last]
    #[test]
    fn test_pattern_slice() {
        assert_parses(r#"
            fn first_and_last(arr: List<Int>) -> Int {
                match arr {
                    [first, .., last] => first + last,
                    [single] => single,
                    [] => 0
                }
            }
        "#);
    }

    /// Record pattern: Point { x, y }
    #[test]
    fn test_pattern_record() {
        assert_parses(r#"
            type Point is { x: Int, y: Int };

            fn at_origin(p: Point) -> Bool {
                match p {
                    Point { x: 0, y: 0 } => true,
                    Point { x, y } => false
                }
            }
        "#);
    }

    /// Nested patterns
    #[test]
    fn test_pattern_nested_complex() {
        assert_parses(r#"
            type Tree<T> is Leaf(T) | Node(Heap<Tree<T>>, Heap<Tree<T>>);

            fn sum_leaves(t: &Tree<Int>) -> Int {
                match t {
                    Leaf(v) => v,
                    Node(left, right) => sum_leaves(left) + sum_leaves(right)
                }
            }
        "#);
    }

    /// Combined patterns
    #[test]
    fn test_pattern_combined() {
        assert_parses(r#"
            type Data is Value(Int) | Pair(Int, Int) | Empty;

            fn process(d: Data) -> Int {
                match d {
                    Value(0..=10) => 1,
                    Value(x) | Pair(x, _) => x,
                    Empty => 0
                }
            }
        "#);
    }
}

// ============================================================================
// Test Category 20: Compound Assignment Tests
// ============================================================================
//
// Tests for compound assignment to complex targets.

mod compound_assignment_tests {
    use super::*;

    /// Field compound assignment: obj.field += value
    #[test]
    fn test_compound_field_add() {
        assert_parses(r#"
            type Counter is { value: Int };

            fn increment(c: &mut Counter) {
                c.value += 1;
            }
        "#);
    }

    /// Field compound assignment: all operators
    #[test]
    fn test_compound_field_all_ops() {
        assert_parses(r#"
            type Stats is { a: Int, b: Int };

            fn update(s: &mut Stats) {
                s.a += 10;
                s.b -= 5;
                s.a *= 2;
                s.b /= 3;
            }
        "#);
    }

    /// Index compound assignment: arr[i] += value
    #[test]
    fn test_compound_index_add() {
        assert_parses(r#"
            fn increment_at(arr: &mut List<Int>, idx: Int) {
                arr[idx] += 1;
            }
        "#);
    }

    /// Index compound assignment: nested access
    #[test]
    fn test_compound_index_nested() {
        assert_parses(r#"
            fn update_matrix(m: &mut List<List<Int>>, row: Int, col: Int) {
                m[row][col] += 100;
            }
        "#);
    }

    /// Tuple index compound assignment
    #[test]
    fn test_compound_tuple_index() {
        assert_parses(r#"
            fn update_pair(p: &mut (Int, Int)) {
                p.0 += 1;
                p.1 -= 1;
            }
        "#);
    }

    /// Bitwise compound assignment
    #[test]
    fn test_compound_bitwise() {
        assert_parses(r#"
            type Flags is { bits: Int };

            fn set_flag(f: &mut Flags, mask: Int) {
                f.bits |= mask;
            }

            fn clear_flag(f: &mut Flags, mask: Int) {
                f.bits &= ~mask;
            }
        "#);
    }

    /// Chained field compound assignment
    #[test]
    fn test_compound_chained() {
        assert_parses(r#"
            type Inner is { value: Int };
            type Outer is { inner: Inner };

            fn update_inner(o: &mut Outer) {
                o.inner.value += 10;
            }
        "#);
    }

    /// Simple variable compound assignment (existing)
    #[test]
    fn test_compound_simple() {
        assert_parses(r#"
            fn accumulate(n: Int) -> Int {
                let mut sum = 0;
                let mut i = 0;
                while i < n {
                    sum += i;
                    i += 1;
                }
                sum
            }
        "#);
    }
}

// ============================================================================
// Test Category 21: Builtin Functions Tests
// ============================================================================
//
// Tests for newly implemented builtin functions.

mod builtin_tests {
    use super::*;

    /// assert_eq builtin
    #[test]
    fn test_builtin_assert_eq() {
        assert_parses(r#"
            fn test_equality() {
                assert_eq(1 + 1, 2);
                assert_eq(10 * 2, 20);
            }
        "#);
    }

    /// assert_ne builtin
    #[test]
    fn test_builtin_assert_ne() {
        assert_parses(r#"
            fn test_inequality() {
                assert_ne(1, 2);
                assert_ne(0, 1);
            }
        "#);
    }

    /// debug_assert builtin
    #[test]
    fn test_builtin_debug_assert() {
        assert_parses(r#"
            fn with_debug_checks(x: Int) {
                debug_assert(x >= 0);
                debug_assert(x < 100);
            }
        "#);
    }

    /// dbg builtin
    #[test]
    fn test_builtin_dbg() {
        assert_parses(r#"
            fn debug_value() -> Int {
                let x = dbg(42);
                let y = dbg(x + 8);
                y
            }
        "#);
    }

    /// todo builtin
    #[test]
    fn test_builtin_todo() {
        assert_parses(r#"
            fn not_implemented_yet() -> Int {
                todo()
            }
        "#);
    }

    /// unimplemented builtin
    #[test]
    fn test_builtin_unimplemented() {
        assert_parses(r#"
            fn will_implement_later() -> Bool {
                unimplemented()
            }
        "#);
    }

    /// drop builtin
    #[test]
    fn test_builtin_drop() {
        assert_parses(r#"
            fn cleanup(x: Heap<Int>) {
                drop(x);
            }
        "#);
    }

    /// forget builtin
    #[test]
    fn test_builtin_forget() {
        assert_parses(r#"
            fn leak_value(x: Heap<Int>) {
                forget(x);
            }
        "#);
    }

    /// min builtin
    #[test]
    fn test_builtin_min() {
        assert_parses(r#"
            fn smaller(a: Int, b: Int) -> Int {
                min(a, b)
            }
        "#);
    }

    /// max builtin
    #[test]
    fn test_builtin_max() {
        assert_parses(r#"
            fn larger(a: Int, b: Int) -> Int {
                max(a, b)
            }
        "#);
    }

    /// abs builtin
    #[test]
    fn test_builtin_abs() {
        assert_parses(r#"
            fn absolute(x: Int) -> Int {
                abs(x)
            }
        "#);
    }

    /// Combined builtins
    #[test]
    fn test_builtin_combined() {
        assert_parses(r#"
            fn clamp(x: Int, lo: Int, hi: Int) -> Int {
                max(lo, min(x, hi))
            }
        "#);
    }

    /// print/println builtins
    #[test]
    fn test_builtin_print() {
        assert_parses(r#"
            fn output() {
                print("hello");
                println(" world");
                println();
            }
        "#);
    }

    /// assert builtin
    #[test]
    fn test_builtin_assert() {
        assert_parses(r#"
            fn check_positive(x: Int) {
                assert(x > 0);
            }
        "#);
    }

    /// unreachable builtin
    #[test]
    fn test_builtin_unreachable() {
        assert_parses(r#"
            fn always_some(x: Int) -> Int {
                if x >= 0 { x }
                else { unreachable() }
            }
        "#);
    }
}

// ============================================================================
// Test Category 22: Array Repeat Tests
// ============================================================================
//
// Tests for array repeat syntax [value; count].

mod array_repeat_tests {
    use super::*;

    /// Simple array repeat
    #[test]
    fn test_array_repeat_simple() {
        assert_parses(r#"
            fn zeros(n: Int) -> List<Int> {
                [0; n]
            }
        "#);
    }

    /// Array repeat with expression
    #[test]
    fn test_array_repeat_expr() {
        assert_parses(r#"
            fn fill(value: Int, count: Int) -> List<Int> {
                [value * 2; count + 1]
            }
        "#);
    }

    /// Array repeat vs list literal
    #[test]
    fn test_array_list_vs_repeat() {
        assert_parses(r#"
            fn both_forms() {
                let list_form = [1, 2, 3, 4, 5];
                let repeat_form = [0; 5];
            }
        "#);
    }

    /// Array repeat in function return
    #[test]
    fn test_array_repeat_return() {
        assert_parses(r#"
            fn make_buffer(size: Int) -> List<Int> {
                [0; size]
            }
        "#);
    }

    /// Nested array repeat
    #[test]
    fn test_array_repeat_nested() {
        assert_parses(r#"
            fn matrix(rows: Int, cols: Int) {
                let m = [[0; cols]; rows];
            }
        "#);
    }
}
