#!/bin/sh
# check_core_compiles.sh — do the standard library's own files still compile?
#
# WHY THIS EXISTS.  On 2026-08-15 a change to `core/mod.vr` removed three
# names from the prelude.  The stdlib re-baked green, `hello.vr` ran, every
# comprehension probe ran — and fifteen files IN core/ had stopped
# compiling:
#
#     error<E401>: cannot find `List` in module `core.prelude`
#       --> core/architecture/types.vr:123:39
#
# The bake had not noticed, and that is not a bug in the bake: baking
# produces the archive, it does not ask whether a library file passes the
# path a USER's compile takes.  `verum check` does, and nothing was running
# it over core/.
#
# So: bake + hello answers "did the archive build".  This answers "is the
# library intact", which is a different question and the one that was
# unasked.
#
# RATCHET, NOT GATE.  Some core/ files fail for reasons that predate this
# script; the known set is recorded and only NEW failures fail the run.
# Same discipline as the attestation ratchet — stop the growth first, drain
# the backlog after.
#
# Usage:
#   check_core_compiles.sh [N] [verum]   # check N files (default 200, 0 = all)
#   check_core_compiles.sh --write-baseline [N] [verum]
#
# Sampling is deterministic — every Nth file across a sorted list, not a
# random draw — so two runs on one tree check the same files and a
# difference means the tree changed, not the dice.
set -u

WRITE_BASELINE=0
if [ "${1:-}" = "--write-baseline" ]; then
  WRITE_BASELINE=1
  shift
fi
SAMPLE="${1:-200}"
VERUM="${2:-target/release/verum}"

REPO=$(cd "$(dirname "$0")/../.." && pwd -P)
KNOWN="$REPO/scripts/ci/core_compile_known_failures.txt"

[ -x "$VERUM" ] || { printf 'check_core_compiles: no verum binary at %s\n' "$VERUM" >&2; exit 2; }
VERUM=$(cd "$(dirname "$VERUM")" && pwd -P)/$(basename "$VERUM")

all=$(cd "$REPO" && find core -name '*.vr' | sort)
total=$(printf '%s\n' "$all" | wc -l | tr -d ' ')

if [ "$SAMPLE" -eq 0 ] 2>/dev/null || [ "$SAMPLE" -ge "$total" ] 2>/dev/null; then
  files="$all"
else
  step=$(( total / SAMPLE ))
  [ "$step" -lt 1 ] && step=1
  files=$(printf '%s\n' "$all" | awk -v s="$step" 'NR % s == 1')
fi
count=$(printf '%s\n' "$files" | wc -l | tr -d ' ')

failed=""
for f in $files; do
  if ! (cd "$REPO" && timeout 120 "$VERUM" check "$f" >/dev/null 2>&1); then
    failed="$failed$f
"
  fi
done
failed=$(printf '%s' "$failed" | sed '/^$/d')
nfailed=$(printf '%s' "$failed" | grep -c . || true)

if [ "$WRITE_BASELINE" -eq 1 ]; then
  {
    printf '# core/ files that do not pass `verum check` — the KNOWN set.\n'
    printf '#\n'
    printf '# Recorded so that NEW breakage fails the run while the existing\n'
    printf '# backlog does not.  A line removed is a file repaired; a line added\n'
    printf '# is a decision to ship the library with one more file that does not\n'
    printf '# compile, and belongs in a commit message that says so.\n'
    printf '#\n'
    printf '# Generated by: scripts/ci/check_core_compiles.sh --write-baseline 0\n'
    printf '%s\n' "$failed"
  } > "$KNOWN"
  printf '[ok] baseline written: %s failing of %s checked\n' "$nfailed" "$count"
  exit 0
fi

known=$( [ -f "$KNOWN" ] && grep -v '^#' "$KNOWN" | sed '/^$/d' || true )
new=$(printf '%s\n' "$failed" | grep -vxF "$known" 2>/dev/null | sed '/^$/d' || printf '%s' "$failed")

if [ -n "$new" ]; then
  printf '[fail] %s core/ file(s) newly fail `verum check`:\n' "$(printf '%s' "$new" | grep -c .)"
  printf '%s\n' "$new" | sed 's/^/    /'
  printf '\nThe bake can be green while these are broken — it builds the archive,\n'
  printf 'it does not compile the library the way a user does.\n'
  exit 1
fi

printf '[ok] core compiles: %s of %s file(s) checked, %s known failure(s), none new\n' \
  "$count" "$total" "$nfailed"
exit 0
