#!/bin/sh
# check_core_compiles.sh — do the standard library's own files still compile?
#
# WHY THIS EXISTS.  On 2026-08-15 a change to `core/mod.vr` removed three
# names from the prelude.  The stdlib re-baked green, `hello.vr` ran, every
# comprehension probe ran — and fifteen files IN core/ had stopped
# compiling:
#
#     error<E401>: cannot find `List` in module `core.prelude`
#       --> core/architecture/types.vr:123:39
#
# The bake had not noticed, and that is not a bug in the bake: baking
# produces the archive, it does not ask whether a library file passes the
# path a USER's compile takes.  `verum check` does, and nothing was running
# it over core/.
#
# So: bake + hello answers "did the archive build".  This answers "is the
# library intact", which is a different question and the one that was
# unasked.
#
# RATCHET, NOT GATE.  Some core/ files fail for reasons that predate this
# script; the known set is recorded and only NEW failures fail the run.
# Same discipline as the attestation ratchet — stop the growth first, drain
# the backlog after.
#
# Usage:
#   check_core_compiles.sh [N] [verum]   # check N files (default 200, 0 = all)
#   check_core_compiles.sh --write-baseline [N] [verum]
#
# Sampling is deterministic — every Nth file across a sorted list, not a
# random draw — so two runs on one tree check the same files and a
# difference means the tree changed, not the dice.
set -u

WRITE_BASELINE=0
if [ "${1:-}" = "--write-baseline" ]; then
  WRITE_BASELINE=1
  shift
fi
SAMPLE="${1:-200}"
VERUM="${2:-target/release/verum}"

REPO=$(cd "$(dirname "$0")/../.." && pwd -P)
KNOWN="$REPO/scripts/ci/core_compile_known_failures.txt"

[ -x "$VERUM" ] || { printf 'check_core_compiles: no verum binary at %s\n' "$VERUM" >&2; exit 2; }
VERUM=$(cd "$(dirname "$VERUM")" && pwd -P)/$(basename "$VERUM")

all=$(cd "$REPO" && find core -name '*.vr' | sort)
total=$(printf '%s\n' "$all" | wc -l | tr -d ' ')

if [ "$SAMPLE" -eq 0 ] 2>/dev/null || [ "$SAMPLE" -ge "$total" ] 2>/dev/null; then
  files="$all"
else
  step=$(( total / SAMPLE ))
  [ "$step" -lt 1 ] && step=1
  # ROTATING OFFSET.  The stride used to be `NR % s == 1`, which picks the
  # SAME files every run: with 2561 files and a 200 sample the other ~92%
  # of the tree was never checked, not rarely — never.  A fixed-stride
  # sample has a PERMANENT blind spot, which is worse than a random one
  # because nothing ever wanders into it.
  #
  # The offset walks by day-of-year, so consecutive runs take different
  # slices and the whole tree is covered every `step` days.  Override with
  # CORE_COMPILE_OFFSET to reproduce a specific run's sample exactly.
  offset="${CORE_COMPILE_OFFSET:-$(date +%j)}"
  pick=$(( offset % step + 1 ))
  files=$(printf '%s\n' "$all" | awk -v s="$step" -v p="$pick" 'NR % s == p % s')
fi
count=$(printf '%s\n' "$files" | wc -l | tr -d ' ')

failed=""
mute=""
for f in $files; do
  out=$(cd "$REPO" && timeout 120 "$VERUM" check "$f" 2>&1) && rc=0 || rc=$?
  # A THIRD OUTCOME: the checker did not run. Distinguishing it from "ran
  # and found errors" is not pedantry — measured 2026-08-31, when the disk
  # hit 100% `verum check` printed NOTHING and exited non-zero, so every
  # remaining file read as a plain failure and a sweep that counted output
  # lines instead read them as PASSES. Either way the run stops answering
  # its question, and it must say so rather than produce a number.
  if ! printf '%s' "$out" | grep -q 'Checking\|Finished\|error'; then
    mute="$mute$f
"
  elif [ "$rc" -ne 0 ]; then
    failed="$failed$f
"
  fi
done
failed=$(printf '%s' "$failed" | sed '/^$/d')
nfailed=$(printf '%s' "$failed" | grep -c . || true)
mute=$(printf '%s' "$mute" | sed '/^$/d')
nmute=$(printf '%s' "$mute" | grep -c . || true)

if [ "$nmute" -gt 0 ]; then
  printf '[fail] %s file(s) produced NO output at all — the checker did not run.\n' "$nmute" >&2
  printf '%s\n' "$mute" | head -5 | sed 's/^/         /' >&2
  printf '       Check `df -h` and `sysctl vm.swapusage` FIRST: a full disk and\n' >&2
  printf '       an exhausted swap both kill this binary without a message, and\n' >&2
  printf '       the resulting run reports a number that means nothing.\n' >&2
  exit 1
fi

if [ "$WRITE_BASELINE" -eq 1 ]; then
  {
    printf '# core/ files that do not pass `verum check` — the KNOWN set.\n'
    printf '#\n'
    printf '# Recorded so that NEW breakage fails the run while the existing\n'
    printf '# backlog does not.  A line removed is a file repaired; a line added\n'
    printf '# is a decision to ship the library with one more file that does not\n'
    printf '# compile, and belongs in a commit message that says so.\n'
    printf '#\n'
    printf '# Generated by: scripts/ci/check_core_compiles.sh --write-baseline 0\n'
    # Keep whatever history the previous file recorded: those comments carry
    # the WHY of past jumps (T0777's 478->495, T0755's 463->372), and a
    # regenerate that drops them turns a documented series into a bare list.
    if [ -f "$KNOWN" ]; then
      grep '^#' "$KNOWN" | grep -vE 'Generated by:|^# core/ files that do not pass|^# Recorded so that|^# backlog does not|^# is a decision to ship|^# compile, and belongs|^#$' || true
    fi
    printf '%s\n' "$failed"
  } > "$KNOWN"
  printf '[ok] baseline written: %s failing of %s checked\n' "$nfailed" "$count"
  exit 0
fi

known=$( [ -f "$KNOWN" ] && grep -v '^#' "$KNOWN" | sed '/^$/d' || true )
new=$(printf '%s\n' "$failed" | grep -vxF "$known" 2>/dev/null | sed '/^$/d' || printf '%s' "$failed")

if [ -n "$new" ]; then
  printf '[fail] %s core/ file(s) newly fail `verum check`:\n' "$(printf '%s' "$new" | grep -c .)"
  printf '%s\n' "$new" | sed 's/^/    /'
  printf '\nThe bake can be green while these are broken — it builds the archive,\n'
  printf 'it does not compile the library the way a user does.\n'
  exit 1
fi

# The other side of the ratchet (T0755).  Reporting only NEW failures made
# this gate blind in the direction it drifts: on 2026-08-31 the list held
# 463 entries and 91 of them PASSED — a fifth of it stale, accumulated over
# two weeks, with nothing able to notice because a green run said nothing
# about repairs.  `check_barename_collisions` states the rule this violates:
# a baseline that drifts above reality stops measuring.
#
# Sampling-safe by construction: only files this run actually CHECKED are
# considered, so a partial run cannot report an unchecked entry as repaired.
repaired=$(printf '%s\n' "$files" | grep -xF "$known" 2>/dev/null | grep -vxF "$failed" 2>/dev/null | sed '/^$/d' || true)
nrepaired=$(printf '%s' "$repaired" | grep -c . || true)
if [ "$nrepaired" -gt 0 ]; then
  printf '[fail] %s known-failing core/ file(s) now PASS — the baseline is stale:\n' "$nrepaired"
  printf '%s\n' "$repaired" | sed 's/^/    /'
  printf '\nRemove them from %s in a commit that says which change repaired\n' "$KNOWN"
  printf 'them, or that they were already stale.  A backlog list left above\n'
  printf 'reality stops being a measurement.\n'
  exit 1
fi

printf '[ok] core compiles: %s of %s file(s) checked, %s known failure(s), none new\n' \
  "$count" "$total" "$nfailed"
exit 0
