//! Embed the by-example chapters (T0858 slice 6): the guided tours
//! LIVE in `docs/by-example/` — one truth of the examples — and the
//! binary carries them via `include_str!` generated HERE from the
//! directory listing, so a new chapter is embedded by existing, never
//! by someone remembering to hand-list it. Builtin copies of teaching
//! content next to the docs are forbidden by the accepted design.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let by_example = Path::new(&manifest).join("../../docs/by-example");
    println!("cargo:rerun-if-changed={}", by_example.display());

    let mut chapters: Vec<String> = std::fs::read_dir(&by_example)
        .expect("docs/by-example readable")
        .filter_map(|e| {
            let e = e.ok()?;
            let name = e.file_name().into_string().ok()?;
            let is_chapter = e.file_type().ok()?.is_dir()
                && name.chars().next().is_some_and(|c| c.is_ascii_digit());
            (is_chapter
                && e.path().join("main.vr").exists()
                && e.path().join("notes.md").exists())
            .then_some(name)
        })
        .collect();
    chapters.sort();
    assert!(
        !chapters.is_empty(),
        "docs/by-example holds no complete chapters — the tours would ship empty"
    );

    let mut out = String::new();
    let _ = writeln!(
        out,
        "/// (slug, notes.md, main.vr) per complete by-example chapter,\n\
         /// in order. Generated by build.rs from docs/by-example — the\n\
         /// one truth of the examples.\n\
         pub const BY_EXAMPLE_CHAPTERS: &[(&str, &str, &str)] = &["
    );
    for slug in &chapters {
        let _ = writeln!(
            out,
            "    (\n        {slug:?},\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../docs/by-example/{slug}/notes.md\")),\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/../../docs/by-example/{slug}/main.vr\")),\n    ),"
        );
    }
    let _ = writeln!(out, "];");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR"))
        .join("by_example_chapters.rs");
    std::fs::write(&dest, out).expect("write generated chapters");
}
