//! Corpus management for fuzz testing
//!
//! This module provides corpus management for storing, loading, and selecting
//! test cases. The corpus evolves over time as new interesting inputs are found.
//!
//! # Features
//!
//! - **Persistent Storage**: Save and load corpus from disk
//! - **Coverage Tracking**: Track which inputs provide unique coverage
//! - **Prioritization**: Select high-value inputs for mutation
//! - **Deduplication**: Avoid storing duplicate inputs

use rand::prelude::*;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::time::SystemTime;

/// A single entry in the corpus
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorpusEntry {
    /// Unique identifier (hash of content)
    pub id: String,
    /// The input content
    pub content: String,
    /// When this entry was added
    pub added_at: u64,
    /// Coverage information (if available)
    pub coverage: Option<CoverageInfo>,
    /// Number of times this entry has been selected
    pub selection_count: usize,
    /// Number of new inputs found from mutating this entry
    pub children_found: usize,
    /// Size in bytes
    pub size: usize,
    /// Source of this entry
    pub source: EntrySource,
    /// Priority score for selection
    pub priority: f64,
}

/// Source of a corpus entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EntrySource {
    /// Loaded from seed corpus
    Seed,
    /// Generated by generator
    Generated,
    /// Created by mutating another entry
    Mutation(String),
    /// Imported from external source
    Imported,
    /// Found during crash investigation
    CrashMinimization,
}

/// Coverage information for an entry
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CoverageInfo {
    /// Set of covered edges (as hashes)
    pub edges: HashSet<u64>,
    /// Number of unique edges
    pub edge_count: usize,
    /// Whether this entry provides unique coverage
    pub is_unique: bool,
    /// Percentage of total coverage
    pub coverage_pct: f64,
}

/// The main corpus
#[derive(Debug, Default)]
pub struct Corpus {
    /// All entries by ID
    entries: HashMap<String, CorpusEntry>,
    /// Content hashes for deduplication
    content_hashes: HashSet<String>,
    /// Global coverage tracking
    global_coverage: HashSet<u64>,
    /// Entries sorted by priority for efficient selection
    priority_order: Vec<String>,
}

impl Corpus {
    /// Create a new empty corpus
    pub fn new() -> Self {
        Self::default()
    }

    /// Add an entry to the corpus
    pub fn add(&mut self, content: &str, coverage: Option<CoverageInfo>) -> Option<String> {
        // Compute content hash
        let hash = self.hash_content(content);

        // Check for duplicates
        if self.content_hashes.contains(&hash) {
            return None;
        }

        // Create entry
        let entry = CorpusEntry {
            id: hash.clone(),
            content: content.to_string(),
            added_at: SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .unwrap()
                .as_secs(),
            coverage: coverage.clone(),
            selection_count: 0,
            children_found: 0,
            size: content.len(),
            source: EntrySource::Generated,
            priority: self.compute_priority(content, &coverage),
        };

        // Update global coverage
        if let Some(ref cov) = coverage {
            for edge in &cov.edges {
                self.global_coverage.insert(*edge);
            }
        }

        self.content_hashes.insert(hash.clone());
        self.entries.insert(hash.clone(), entry);
        self.update_priority_order();

        Some(hash)
    }

    /// Add a seed entry
    pub fn add_seed(&mut self, content: &str) -> Option<String> {
        if let Some(id) = self.add(content, None) {
            if let Some(entry) = self.entries.get_mut(&id) {
                entry.source = EntrySource::Seed;
                entry.priority *= 1.5; // Boost seed priority
            }
            Some(id)
        } else {
            None
        }
    }

    /// Get an entry by ID
    pub fn get(&self, id: &str) -> Option<&CorpusEntry> {
        self.entries.get(id)
    }

    /// Pick a random entry for mutation (weighted by priority)
    pub fn pick<R: Rng>(&self, rng: &mut R) -> String {
        if self.entries.is_empty() {
            return String::new();
        }

        // Weighted selection based on priority
        let total_priority: f64 = self.entries.values().map(|e| e.priority).sum();

        if total_priority <= 0.0 {
            // Uniform random if no priorities
            let keys: Vec<_> = self.entries.keys().collect();
            return keys[rng.random_range(0..keys.len())].clone();
        }

        let mut choice = rng.random::<f64>() * total_priority;
        for entry in self.entries.values() {
            choice -= entry.priority;
            if choice <= 0.0 {
                return entry.content.clone();
            }
        }

        // Fallback
        self.entries
            .values()
            .next()
            .map(|e| e.content.clone())
            .unwrap_or_default()
    }

    /// Pick multiple entries for batch processing
    pub fn pick_batch<R: Rng>(&self, count: usize, rng: &mut R) -> Vec<String> {
        (0..count).map(|_| self.pick(rng)).collect()
    }

    /// Update entry after it was used for mutation
    pub fn mark_selected(&mut self, id: &str) {
        if let Some(entry) = self.entries.get_mut(id) {
            entry.selection_count += 1;
            // Decrease priority slightly to encourage exploration
            entry.priority *= 0.99;
        }
    }

    /// Update entry when a new input was found from it
    pub fn mark_productive(&mut self, id: &str) {
        if let Some(entry) = self.entries.get_mut(id) {
            entry.children_found += 1;
            // Increase priority for productive entries
            entry.priority *= 1.1;
        }
        self.update_priority_order();
    }

    /// Remove an entry
    pub fn remove(&mut self, id: &str) -> Option<CorpusEntry> {
        if let Some(entry) = self.entries.remove(id) {
            self.content_hashes
                .remove(&self.hash_content(&entry.content));
            self.priority_order.retain(|x| x != id);
            Some(entry)
        } else {
            None
        }
    }

    /// Get the number of entries
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Check if the corpus is empty
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Get all entry IDs
    pub fn ids(&self) -> Vec<String> {
        self.entries.keys().cloned().collect()
    }

    /// Get statistics about the corpus
    pub fn stats(&self) -> CorpusStats {
        let total_size: usize = self.entries.values().map(|e| e.size).sum();
        let avg_size = if self.entries.is_empty() {
            0.0
        } else {
            total_size as f64 / self.entries.len() as f64
        };

        let seeds = self
            .entries
            .values()
            .filter(|e| matches!(e.source, EntrySource::Seed))
            .count();

        let mutations = self
            .entries
            .values()
            .filter(|e| matches!(e.source, EntrySource::Mutation(_)))
            .count();

        CorpusStats {
            total_entries: self.entries.len(),
            total_size,
            average_size: avg_size,
            seed_entries: seeds,
            mutation_entries: mutations,
            unique_coverage: self.global_coverage.len(),
        }
    }

    /// Compute priority for an entry
    fn compute_priority(&self, content: &str, coverage: &Option<CoverageInfo>) -> f64 {
        let mut priority = 1.0;

        // Prefer smaller inputs
        priority += 10.0 / (content.len() as f64 + 1.0);

        // Prefer inputs with unique coverage
        if let Some(cov) = coverage {
            if cov.is_unique {
                priority *= 2.0;
            }
            priority += cov.edge_count as f64 * 0.1;
        }

        priority
    }

    /// Hash content for deduplication
    fn hash_content(&self, content: &str) -> String {
        let mut hasher = Sha256::new();
        hasher.update(content.as_bytes());
        let hash = hasher.finalize();
        hex::encode(&hash[..16])
    }

    /// Update the priority order
    fn update_priority_order(&mut self) {
        let mut entries: Vec<_> = self.entries.iter().collect();
        entries.sort_by(|a, b| {
            b.1.priority
                .partial_cmp(&a.1.priority)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        self.priority_order = entries.into_iter().map(|(k, _)| k.clone()).collect();
    }

    /// Cull low-priority entries to keep corpus size manageable
    pub fn cull(&mut self, max_size: usize) {
        if self.entries.len() <= max_size {
            return;
        }

        self.update_priority_order();

        // Keep the top entries by priority, but always keep seeds
        let to_remove: Vec<_> = self
            .priority_order
            .iter()
            .skip(max_size)
            .filter(|id| {
                self.entries
                    .get(*id)
                    .map(|e| !matches!(e.source, EntrySource::Seed))
                    .unwrap_or(false)
            })
            .cloned()
            .collect();

        for id in to_remove {
            self.remove(&id);
        }

        // Rebuild global_coverage from remaining entries to prevent memory leak
        // This ensures we don't keep coverage info for removed entries
        self.rebuild_global_coverage();
    }

    /// Rebuild global_coverage from remaining entries
    /// Call this after removing entries to prevent unbounded memory growth
    fn rebuild_global_coverage(&mut self) {
        self.global_coverage.clear();
        for entry in self.entries.values() {
            if let Some(ref cov) = entry.coverage {
                for edge in &cov.edges {
                    self.global_coverage.insert(*edge);
                }
            }
        }
    }

    /// Reset all corpus state
    pub fn reset(&mut self) {
        self.entries.clear();
        self.content_hashes.clear();
        self.global_coverage.clear();
        self.priority_order.clear();
    }
}

/// Corpus manager for persistent storage
pub struct CorpusManager {
    /// The in-memory corpus
    corpus: Corpus,
    /// Directory for persistence
    directory: PathBuf,
    /// Auto-save enabled
    auto_save: bool,
}

impl CorpusManager {
    /// Create a new corpus manager
    pub fn new<P: AsRef<Path>>(directory: P) -> std::io::Result<Self> {
        let directory = directory.as_ref().to_path_buf();
        std::fs::create_dir_all(&directory)?;

        let mut manager = Self {
            corpus: Corpus::new(),
            directory,
            auto_save: true,
        };

        // Load existing corpus
        manager.load()?;

        Ok(manager)
    }

    /// Add an entry to the corpus
    pub fn add(&mut self, content: &str, coverage: Option<CoverageInfo>) -> Option<String> {
        let id = self.corpus.add(content, coverage)?;

        if self.auto_save {
            let _ = self.save_entry(&id);
        }

        Some(id)
    }

    /// Add a seed entry
    pub fn add_seed(&mut self, content: &str) -> Option<String> {
        let id = self.corpus.add_seed(content)?;

        if self.auto_save {
            let _ = self.save_entry(&id);
        }

        Some(id)
    }

    /// Pick a random entry
    pub fn pick<R: Rng>(&self, rng: &mut R) -> String {
        self.corpus.pick(rng)
    }

    /// Get the number of entries
    pub fn len(&self) -> usize {
        self.corpus.len()
    }

    /// Check if empty
    pub fn is_empty(&self) -> bool {
        self.corpus.is_empty()
    }

    /// Get corpus statistics
    pub fn stats(&self) -> CorpusStats {
        self.corpus.stats()
    }

    /// Save the entire corpus to disk
    pub fn save(&self) -> std::io::Result<()> {
        for (id, entry) in &self.corpus.entries {
            self.save_entry_internal(id, entry)?;
        }
        Ok(())
    }

    /// Save a single entry
    fn save_entry(&self, id: &str) -> std::io::Result<()> {
        if let Some(entry) = self.corpus.get(id) {
            self.save_entry_internal(id, entry)
        } else {
            Ok(())
        }
    }

    /// Internal save implementation
    fn save_entry_internal(&self, id: &str, entry: &CorpusEntry) -> std::io::Result<()> {
        // Save the content
        let content_path = self.directory.join(format!("{}.vr", id));
        std::fs::write(&content_path, &entry.content)?;

        // Save the metadata
        let meta_path = self.directory.join(format!("{}.json", id));
        let meta = serde_json::json!({
            "id": entry.id,
            "added_at": entry.added_at,
            "selection_count": entry.selection_count,
            "children_found": entry.children_found,
            "size": entry.size,
            "priority": entry.priority,
        });
        std::fs::write(&meta_path, serde_json::to_string_pretty(&meta)?)?;

        Ok(())
    }

    /// Load the corpus from disk
    pub fn load(&mut self) -> std::io::Result<()> {
        if !self.directory.exists() {
            return Ok(());
        }

        for entry in std::fs::read_dir(&self.directory)? {
            let entry = entry?;
            let path = entry.path();

            if path.extension().map_or(false, |ext| ext == "vr") {
                let content = std::fs::read_to_string(&path)?;
                self.corpus.add(&content, None);
            }
        }

        Ok(())
    }

    /// Load seeds from a directory
    pub fn load_seeds<P: AsRef<Path>>(&mut self, dir: P) -> std::io::Result<usize> {
        let dir = dir.as_ref();
        if !dir.exists() {
            return Ok(0);
        }

        let mut count = 0;
        for entry in walkdir::WalkDir::new(dir)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            let path = entry.path();
            if path.extension().map_or(false, |ext| ext == "vr") {
                let content = std::fs::read_to_string(path)?;
                if self.add_seed(&content).is_some() {
                    count += 1;
                }
            }
        }

        Ok(count)
    }

    /// Cull the corpus to a maximum size
    pub fn cull(&mut self, max_size: usize) {
        self.corpus.cull(max_size);
    }

    /// Get the underlying corpus
    pub fn corpus(&self) -> &Corpus {
        &self.corpus
    }

    /// Get mutable access to the corpus
    pub fn corpus_mut(&mut self) -> &mut Corpus {
        &mut self.corpus
    }

    /// Mark an entry as selected
    pub fn mark_selected(&mut self, id: &str) {
        self.corpus.mark_selected(id);
    }

    /// Mark an entry as productive
    pub fn mark_productive(&mut self, id: &str) {
        self.corpus.mark_productive(id);
    }
}

/// Statistics about the corpus
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct CorpusStats {
    /// Total number of entries
    pub total_entries: usize,
    /// Total size in bytes
    pub total_size: usize,
    /// Average entry size
    pub average_size: f64,
    /// Number of seed entries
    pub seed_entries: usize,
    /// Number of mutation-derived entries
    pub mutation_entries: usize,
    /// Number of unique coverage edges
    pub unique_coverage: usize,
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;
    use rand_chacha::ChaCha8Rng;
    use tempfile::tempdir;

    #[test]
    fn test_corpus_creation() {
        let corpus = Corpus::new();
        assert!(corpus.is_empty());
    }

    #[test]
    fn test_corpus_add() {
        let mut corpus = Corpus::new();
        let id = corpus.add("fn main() {}", None);
        assert!(id.is_some());
        assert_eq!(corpus.len(), 1);
    }

    #[test]
    fn test_corpus_deduplication() {
        let mut corpus = Corpus::new();
        let id1 = corpus.add("fn main() {}", None);
        let id2 = corpus.add("fn main() {}", None);
        assert!(id1.is_some());
        assert!(id2.is_none());
        assert_eq!(corpus.len(), 1);
    }

    #[test]
    fn test_corpus_pick() {
        let mut corpus = Corpus::new();
        corpus.add("fn main() { 1 }", None);
        corpus.add("fn main() { 2 }", None);
        corpus.add("fn main() { 3 }", None);

        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let picked = corpus.pick(&mut rng);
        assert!(!picked.is_empty());
    }

    #[test]
    fn test_corpus_stats() {
        let mut corpus = Corpus::new();
        corpus.add_seed("fn main() {}");
        corpus.add("fn other() {}", None);

        let stats = corpus.stats();
        assert_eq!(stats.total_entries, 2);
        assert_eq!(stats.seed_entries, 1);
    }

    #[test]
    fn test_corpus_cull() {
        let mut corpus = Corpus::new();
        for i in 0..10 {
            corpus.add(&format!("fn main() {{ {} }}", i), None);
        }

        assert_eq!(corpus.len(), 10);
        corpus.cull(5);
        assert_eq!(corpus.len(), 5);
    }

    #[test]
    fn test_corpus_manager() {
        let dir = tempdir().unwrap();
        let mut manager = CorpusManager::new(dir.path()).unwrap();

        manager.add("fn main() {}", None);
        assert_eq!(manager.len(), 1);

        // Check that file was created
        let files: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .collect();
        assert!(!files.is_empty());
    }

    #[test]
    fn test_corpus_manager_persistence() {
        let dir = tempdir().unwrap();

        {
            let mut manager = CorpusManager::new(dir.path()).unwrap();
            manager.add("fn main() { 1 }", None);
            manager.add("fn main() { 2 }", None);
        }

        // Reload
        let manager = CorpusManager::new(dir.path()).unwrap();
        assert_eq!(manager.len(), 2);
    }

    #[test]
    fn test_coverage_info() {
        let mut corpus = Corpus::new();

        let coverage = CoverageInfo {
            edges: vec![1, 2, 3].into_iter().collect(),
            edge_count: 3,
            is_unique: true,
            coverage_pct: 10.0,
        };

        let id = corpus.add("fn main() {}", Some(coverage));
        assert!(id.is_some());

        let entry = corpus.get(&id.unwrap()).unwrap();
        assert!(entry.coverage.is_some());
    }
}
