//! Unified `VerificationGoal` type — the single verification surface.
//!
//! # The unification
//!
//! Verum has three notions of "the thing we verify":
//!
//!   1. **Function contracts** — `fn f(x: T) requires P ensures Q`
//!      produces an obligation that the SMT-dispatch path discharges.
//!   2. **Theorem propositions** — `theorem T(...) ensures Q { proof }`
//!      produces an obligation discharged by the kernel +
//!      tactic_elaborator.
//!   3. **Refinement-type predicates** — `let x: Int{>= 0} = expr`
//!      produces an obligation checked at type-application time.
//!
//! Without a shared representation, "what is Verum proving about
//! this program?" has three different answers depending on the
//! source, and the audit gate cannot enumerate the trust extension
//! uniformly.  This module supplies the shared representation:
//! every source produces a `VerificationGoal { hypotheses,
//! conclusion, source }`, and every dispatcher consumes one.
//!
//! # Architectural alignment with Verum philosophy
//!
//! - **Semantic honesty**: a goal IS what we're proving — not "the
//!   thing the SMT layer wants" or "the thing the kernel checks".
//!   One concept, one type.
//! - **No magic**: every goal has explicit `hypotheses`,
//!   `conclusion`, `source`.  Nothing implicit.
//! - **Foundation-neutral**: hypotheses + conclusion are kernel
//!   `Term` values — they live in the same trust base as
//!   `proof_checker`.
//!
//! # Surface
//!
//!   - [`VerificationGoal`] + [`GoalSource`].
//!   - [`from_theorem_decl`] / [`from_fn_decl`] / [`from_refinement`]
//!     — AST-to-goal converters for the three sources.
//!   - [`VerificationGoal::to_term`] — encode as a closed
//!     `Pi(H_1, Pi(H_2, ..., Pi(H_n, C)))` for direct kernel use.
//!   - [`VerificationGoal::audit_metadata`] — JSON-ready projection
//!     for audit-gate dashboards.
//!
//! The SMT dispatch and refinement-check pathways still own their
//! own internal pipelines; routing them through `VerificationGoal`
//! is a separate migration.  This module establishes the target
//! shape so that migration can land incrementally.

use std::collections::BTreeMap;

use crate::proof_checker::Term;
use crate::tactic_elaborator::{
    expr_to_term, proposition_to_term, ElabContext, ElabError,
};

// =============================================================================
// VerificationGoal
// =============================================================================

/// A unified verification goal.  Every source of "what to prove" in
/// Verum produces a value of this type; every dispatcher (SMT,
/// kernel, refinement-check) consumes one.
///
/// **Logical reading**: `H_1 ∧ H_2 ∧ ... ∧ H_n ⇒ C`.
///
/// **Kernel-Term reading**: as a closed Pi-chain
/// `Pi(H_1, Pi(H_2, ..., Pi(H_n, C)))` (see [`VerificationGoal::to_term`]).
#[derive(Debug, Clone, PartialEq)]
pub struct VerificationGoal {
    /// Translated `requires` clauses (or refinement-base preconditions).
    /// Logically conjoined as the antecedent.
    pub hypotheses: Vec<Term>,
    /// Translated `ensures` clause (or refinement predicate, or
    /// theorem proposition).  The consequent.
    pub conclusion: Term,
    /// Where this goal came from.  Diagnostic + audit-gate metadata.
    pub source: GoalSource,
}

/// The pipeline source that produced a [`VerificationGoal`].
///
/// **Architectural significance**: this enum makes the verification
/// surface explicit.  An audit gate that sees only `Theorem` sources
/// is reviewing the proof corpus; one that sees only `FnContract` is
/// reviewing implementation contracts; one that sees mixes can
/// answer "what's the trust extension across the entire program?"
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum GoalSource {
    /// `theorem name(...) ensures Q { proof { ... } }`.
    Theorem {
        /// Theorem name as written in source.
        name: String,
    },
    /// `lemma name(...) ensures Q { proof { ... } }`.  Identical
    /// shape to `Theorem` semantically; preserved as a separate
    /// source for diagnostic clarity.
    Lemma {
        /// Lemma name.
        name: String,
    },
    /// `corollary name(...) ensures Q { proof { ... } }`.
    Corollary {
        /// Corollary name.
        name: String,
    },
    /// `fn f(x: T) requires P ensures Q`.  The fn-contract pathway.
    FnContract {
        /// Function name.
        fn_name: String,
    },
    /// Subgoal generated by a tactic step.  E.g., `apply lemma; ...`
    /// produces subgoals for each unmatched premise.  The `parent`
    /// names the enclosing theorem; `depth` records the nesting
    /// level so reviewers can reconstruct the proof tree.
    TacticSubgoal {
        /// Enclosing theorem / lemma name.
        parent: String,
        /// Nesting depth (0 = direct subgoal of the proof body).
        depth: usize,
    },
    /// Refinement-type predicate obligation: `let x: T{P(x)} = expr`
    /// generates the obligation `P(expr)`.  The `ty_name` is the
    /// declared refinement type name (e.g. `"NonNegInt"` for
    /// `Int{>= 0}` if a name is available; else the auto-generated tag).
    Refinement {
        /// Refinement-type name or anonymous tag.
        ty_name: String,
    },
}

impl GoalSource {
    /// Diagnostic label for the source kind — used by error messages
    /// and JSON audit reports.
    pub fn kind_tag(&self) -> &'static str {
        match self {
            GoalSource::Theorem { .. } => "theorem",
            GoalSource::Lemma { .. } => "lemma",
            GoalSource::Corollary { .. } => "corollary",
            GoalSource::FnContract { .. } => "fn_contract",
            GoalSource::TacticSubgoal { .. } => "tactic_subgoal",
            GoalSource::Refinement { .. } => "refinement",
        }
    }

    /// Identifier for the source.  Theorem / fn / etc. name.
    pub fn name(&self) -> &str {
        match self {
            GoalSource::Theorem { name } => name,
            GoalSource::Lemma { name } => name,
            GoalSource::Corollary { name } => name,
            GoalSource::FnContract { fn_name } => fn_name,
            GoalSource::TacticSubgoal { parent, .. } => parent,
            GoalSource::Refinement { ty_name } => ty_name,
        }
    }
}

impl VerificationGoal {
    /// **Build a goal explicitly** from translated hypotheses and
    /// conclusion.  Lower-level constructor; prefer the
    /// `from_*` helpers when starting from AST.
    pub fn new(hypotheses: Vec<Term>, conclusion: Term, source: GoalSource) -> Self {
        Self {
            hypotheses,
            conclusion,
            source,
        }
    }

    /// **Encode the goal as a single closed kernel `Term`.**
    ///
    /// The result is `Pi(H_1, Pi(H_2, ..., Pi(H_n, C)))`.  This is the
    /// type a proof certificate must inhabit — the de Bruijn criterion
    /// reads off this term.
    ///
    /// **Closure invariant**: caller must ensure all hypotheses and
    /// the conclusion are closed.  No checking here; the kernel will
    /// reject if they aren't.
    pub fn to_term(&self) -> Term {
        let mut acc = self.conclusion.clone();
        // Wrap from innermost (last hypothesis) outwards.  Each
        // wrapping adds one Pi-binder; the body's de-Bruijn indices
        // shift up by one — but since we don't re-construct the
        // hypotheses' references here, callers must build hypotheses
        // that reference outer binders correctly when using nested
        // hypotheses.
        for hyp in self.hypotheses.iter().rev() {
            acc = Term::Pi(Box::new(hyp.clone()), Box::new(acc));
        }
        acc
    }

    /// Whether this is a goal with no hypotheses (the conclusion alone).
    pub fn is_unconditional(&self) -> bool {
        self.hypotheses.is_empty()
    }

    /// Number of hypotheses.
    pub fn hypothesis_count(&self) -> usize {
        self.hypotheses.len()
    }

    /// **Project metadata** for audit-gate JSON emission.
    ///
    /// Returns a `BTreeMap` with stable string keys: `kind`, `name`,
    /// `hypothesis_count`.  Suitable for direct serde-JSON emission.
    pub fn audit_metadata(&self) -> BTreeMap<String, String> {
        let mut m = BTreeMap::new();
        m.insert("kind".to_string(), self.source.kind_tag().to_string());
        m.insert("name".to_string(), self.source.name().to_string());
        m.insert(
            "hypothesis_count".to_string(),
            self.hypothesis_count().to_string(),
        );
        if let GoalSource::TacticSubgoal { depth, .. } = &self.source {
            m.insert("depth".to_string(), depth.to_string());
        }
        m
    }
}

// =============================================================================
// Converters from AST forms
// =============================================================================

use verum_ast::decl::{FunctionDecl, TheoremDecl};
use verum_ast::expr::Expr;

/// **Convert a theorem (or lemma / corollary) declaration to a
/// VerificationGoal.**
///
/// - Hypotheses: the theorem's `requires` clauses, each translated
///   via [`proposition_to_term`].
/// - Conclusion: the theorem's `proposition` (synthesised from
///   `ensures` clauses), translated via [`proposition_to_term`].
/// - Source: `GoalSource::Theorem` / `Lemma` / `Corollary` per
///   `kind` selector — caller picks the correct discriminant.
pub fn from_theorem_decl(
    theorem: &TheoremDecl,
    source_kind: TheoremKind,
    ctx: &ElabContext,
) -> Result<VerificationGoal, ElabError> {
    let hypotheses = translate_clauses(theorem.requires.iter(), ctx)?;
    let conclusion = proposition_to_term(theorem.proposition.as_ref(), ctx)?;
    let name = theorem.name.name.to_string();
    let source = match source_kind {
        TheoremKind::Theorem => GoalSource::Theorem { name },
        TheoremKind::Lemma => GoalSource::Lemma { name },
        TheoremKind::Corollary => GoalSource::Corollary { name },
    };
    Ok(VerificationGoal::new(hypotheses, conclusion, source))
}

/// Discriminator for `from_theorem_decl` — picks which
/// [`GoalSource`] variant to attach.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TheoremKind {
    /// `theorem` declaration.
    Theorem,
    /// `lemma` declaration.
    Lemma,
    /// `corollary` declaration.
    Corollary,
}

/// **Convert a function declaration to a VerificationGoal.**
///
/// - Hypotheses: the function's `requires` clauses translated via
///   [`proposition_to_term`].
/// - Conclusion: synthesised from the function's `ensures` clauses
///   conjunctively.  When `ensures` is empty, the conclusion is
///   `Universe(0)` (vacuously true).
/// - Source: `GoalSource::FnContract { fn_name }`.
///
/// **Limitation**: the function body's verification (showing the
/// implementation actually satisfies `ensures` under `requires`) is
/// the SMT-layer's job.  This converter produces the *contract*
/// goal; the obligation against the body is a separate pipeline.
pub fn from_fn_decl(
    fn_decl: &FunctionDecl,
    ctx: &ElabContext,
) -> Result<VerificationGoal, ElabError> {
    let hypotheses = translate_clauses(fn_decl.requires.iter(), ctx)?;
    let conclusion = if fn_decl.ensures.is_empty() {
        Term::Universe(0)
    } else if fn_decl.ensures.len() == 1 {
        proposition_to_term(fn_decl.ensures.iter().next().unwrap(), ctx)?
    } else {
        // Multiple ensures — wrap them in the And connective axiom
        // (registered via tactic_elaborator::register_propositional_connectives).
        let head = match ctx.get_axiom("__verum_kernel_And") {
            Some(_) => crate::tactic_elaborator::resolve_apply_target(
                ctx,
                "__verum_kernel_And",
            )?,
            None => {
                return Err(ElabError::UnsupportedExpression(
                    "fn with multiple ensures clauses requires \
                     register_propositional_connectives(&mut ctx) first"
                        .into(),
                ));
            }
        };
        let mut iter = fn_decl.ensures.iter();
        let mut acc = proposition_to_term(iter.next().unwrap(), ctx)?;
        for clause in iter {
            let next = proposition_to_term(clause, ctx)?;
            acc = Term::App(
                Box::new(Term::App(
                    Box::new(head.clone()),
                    Box::new(acc),
                )),
                Box::new(next),
            );
        }
        acc
    };
    Ok(VerificationGoal::new(
        hypotheses,
        conclusion,
        GoalSource::FnContract {
            fn_name: fn_decl.name.name.to_string(),
        },
    ))
}

/// **Convert a refinement-type obligation to a VerificationGoal.**
///
/// `let x: Int{P(x)} = expr` generates the obligation `P(expr)`.
/// The base type is encoded in `hypotheses` (a single hypothesis
/// representing `x : T`); the predicate's translation is the
/// conclusion.
///
/// - `base_type_term`: the kernel-Term encoding of the refinement's
///   base type (e.g. `Universe(0)` for the simplest case).
/// - `predicate`: the predicate Expr that must hold.
/// - `ty_name`: a human-readable refinement-type tag.
pub fn from_refinement(
    base_type_term: Term,
    predicate: &Expr,
    ty_name: &str,
    ctx: &ElabContext,
) -> Result<VerificationGoal, ElabError> {
    let conclusion = proposition_to_term(predicate, ctx)?;
    Ok(VerificationGoal::new(
        vec![base_type_term],
        conclusion,
        GoalSource::Refinement {
            ty_name: ty_name.to_string(),
        },
    ))
}

/// Translate a sequence of clauses (`requires` or `ensures` Expr
/// list) to a `Vec<Term>`, propagating the first translation error.
fn translate_clauses<'a>(
    clauses: impl Iterator<Item = &'a Expr>,
    ctx: &ElabContext,
) -> Result<Vec<Term>, ElabError> {
    let mut out = Vec::new();
    for c in clauses {
        out.push(proposition_to_term(c, ctx)?);
    }
    Ok(out)
}

// =============================================================================
// Tests — contract pins for the verification-goal surface
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn term_universe(n: u32) -> Term {
        Term::Universe(n)
    }

    #[test]
    fn empty_goal_is_unconditional() {
        let g = VerificationGoal::new(
            vec![],
            term_universe(0),
            GoalSource::Theorem {
                name: "trivial".into(),
            },
        );
        assert!(g.is_unconditional());
        assert_eq!(g.hypothesis_count(), 0);
        assert_eq!(g.to_term(), Term::Universe(0));
    }

    #[test]
    fn goal_with_one_hypothesis_wraps_in_pi() {
        let g = VerificationGoal::new(
            vec![term_universe(0)],
            term_universe(0),
            GoalSource::FnContract {
                fn_name: "f".into(),
            },
        );
        assert!(!g.is_unconditional());
        assert_eq!(
            g.to_term(),
            Term::Pi(
                Box::new(Term::Universe(0)),
                Box::new(Term::Universe(0)),
            ),
        );
    }

    #[test]
    fn goal_with_three_hypotheses_wraps_left_to_right() {
        // Hypotheses [H1, H2, H3], conclusion C.
        // to_term() should produce Pi(H1, Pi(H2, Pi(H3, C))).
        let g = VerificationGoal::new(
            vec![term_universe(0), term_universe(1), term_universe(2)],
            Term::Var(0),
            GoalSource::Theorem {
                name: "test".into(),
            },
        );
        let t = g.to_term();
        assert_eq!(
            t,
            Term::Pi(
                Box::new(Term::Universe(0)),
                Box::new(Term::Pi(
                    Box::new(Term::Universe(1)),
                    Box::new(Term::Pi(
                        Box::new(Term::Universe(2)),
                        Box::new(Term::Var(0)),
                    )),
                )),
            ),
        );
    }

    #[test]
    fn audit_metadata_includes_kind_name_count() {
        let g = VerificationGoal::new(
            vec![term_universe(0), term_universe(0)],
            term_universe(0),
            GoalSource::Theorem {
                name: "my_thm".into(),
            },
        );
        let m = g.audit_metadata();
        assert_eq!(m.get("kind").map(|s| s.as_str()), Some("theorem"));
        assert_eq!(m.get("name").map(|s| s.as_str()), Some("my_thm"));
        assert_eq!(m.get("hypothesis_count").map(|s| s.as_str()), Some("2"));
    }

    #[test]
    fn audit_metadata_for_subgoal_includes_depth() {
        let g = VerificationGoal::new(
            vec![],
            term_universe(0),
            GoalSource::TacticSubgoal {
                parent: "parent_thm".into(),
                depth: 3,
            },
        );
        let m = g.audit_metadata();
        assert_eq!(m.get("kind").map(|s| s.as_str()), Some("tactic_subgoal"));
        assert_eq!(m.get("name").map(|s| s.as_str()), Some("parent_thm"));
        assert_eq!(m.get("depth").map(|s| s.as_str()), Some("3"));
    }

    #[test]
    fn goal_source_kind_tags_are_distinct() {
        let tags: Vec<&'static str> = vec![
            GoalSource::Theorem { name: String::new() }.kind_tag(),
            GoalSource::Lemma { name: String::new() }.kind_tag(),
            GoalSource::Corollary { name: String::new() }.kind_tag(),
            GoalSource::FnContract {
                fn_name: String::new(),
            }
            .kind_tag(),
            GoalSource::TacticSubgoal {
                parent: String::new(),
                depth: 0,
            }
            .kind_tag(),
            GoalSource::Refinement {
                ty_name: String::new(),
            }
            .kind_tag(),
        ];
        let unique: std::collections::BTreeSet<&'static str> = tags.iter().copied().collect();
        assert_eq!(unique.len(), tags.len(), "kind_tag must be distinct per variant");
    }

    // ----- AST converter tests -----

    use verum_ast::decl::TheoremDecl;
    use verum_ast::expr::ExprKind;
    use verum_ast::ty::{Ident, Path, PathSegment};
    use verum_ast::Literal;
    use verum_common::List;
    use verum_common::Span;

    fn path_expr(name: &str) -> Expr {
        let span = Span::dummy();
        let mut list = List::new();
        list.push(PathSegment::Name(Ident {
            name: name.into(),
            span,
        }));
        let path = Path::new(list, span);
        Expr::new(ExprKind::Path(path), span)
    }

    fn bool_true_expr() -> Expr {
        let span = Span::dummy();
        Expr::new(ExprKind::Literal(Literal::bool(true, span)), span)
    }

    #[test]
    fn from_theorem_decl_with_true_proposition() {
        let span = Span::dummy();
        let theorem = TheoremDecl::new(
            Ident { name: "trivial".into(), span },
            bool_true_expr(),
            span,
        );
        let ctx = ElabContext::new();
        let goal = from_theorem_decl(&theorem, TheoremKind::Theorem, &ctx).unwrap();
        assert_eq!(goal.conclusion, Term::Universe(0));
        assert_eq!(goal.hypothesis_count(), 0);
        assert!(matches!(goal.source, GoalSource::Theorem { ref name } if name == "trivial"));
    }

    #[test]
    fn from_theorem_decl_lemma_kind_marks_source() {
        let span = Span::dummy();
        let theorem = TheoremDecl::new(
            Ident { name: "helper".into(), span },
            bool_true_expr(),
            span,
        );
        let ctx = ElabContext::new();
        let goal = from_theorem_decl(&theorem, TheoremKind::Lemma, &ctx).unwrap();
        assert!(matches!(goal.source, GoalSource::Lemma { ref name } if name == "helper"));
    }

    #[test]
    fn from_theorem_decl_with_path_proposition_resolves_axiom() {
        let span = Span::dummy();
        let theorem = TheoremDecl::new(
            Ident { name: "predicate_thm".into(), span },
            path_expr("my_pred"),
            span,
        );
        let mut ctx = ElabContext::new();
        ctx.register_axiom("my_pred", Term::Universe(0));
        let goal = from_theorem_decl(&theorem, TheoremKind::Theorem, &ctx).unwrap();
        assert_eq!(goal.conclusion, Term::Var(0));
    }

    #[test]
    fn from_refinement_produces_predicate_obligation() {
        let mut ctx = ElabContext::new();
        ctx.register_axiom("is_positive", Term::Universe(0));
        let pred = path_expr("is_positive");
        let goal = from_refinement(Term::Universe(0), &pred, "PosInt", &ctx).unwrap();
        assert_eq!(goal.hypothesis_count(), 1, "base type is hypothesis");
        assert_eq!(goal.conclusion, Term::Var(0));
        assert!(matches!(goal.source, GoalSource::Refinement { ref ty_name } if ty_name == "PosInt"));
    }

    #[test]
    fn translate_clauses_handles_empty_list() {
        let ctx = ElabContext::new();
        let clauses: Vec<Expr> = vec![];
        let result = translate_clauses(clauses.iter(), &ctx).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn translate_clauses_propagates_first_error() {
        let ctx = ElabContext::new();
        // path "undeclared" is not a registered axiom.
        let clauses: Vec<Expr> = vec![bool_true_expr(), path_expr("undeclared")];
        match translate_clauses(clauses.iter(), &ctx) {
            Err(ElabError::UndeclaredApplyTarget(name)) => assert_eq!(name, "undeclared"),
            other => panic!("expected UndeclaredApplyTarget, got {:?}", other),
        }
    }

    // FunctionDecl tests deferred to integration suite — the type
    // has 30+ fields without a `new()` constructor, and the from_fn_decl
    // converter is exercised end-to-end by the corpus walker.  The
    // unit tests above pin the converter's algorithm via the
    // smaller TheoremDecl + Refinement entry points which share the
    // same translate_clauses + proposition_to_term helpers.
}
