//! Unique Identifier Generation (Gensym)
//!
//! Generates unique identifiers for hygienic macro expansion.
//!
//! Verum unified meta-system: all compile-time computation uses `meta` (meta fn,
//! @tagged_literal, @derive, @interpolation_handler). Multi-pass architecture:
//! Pass 1 parses and registers meta handlers, Pass 2 expands using complete
//! registry, Pass 3+ performs semantic analysis. Sandboxed execution (no I/O).

use std::sync::atomic::{AtomicU64, Ordering};

use verum_ast::Span;
use verum_common::Text;

use super::scope::{HygienicIdent, ScopeSet};

/// Generator for unique (gensym) identifiers
#[derive(Debug)]
pub struct GensymGenerator {
    /// Counter for generating unique IDs
    counter: AtomicU64,
    /// Prefix for generated symbols
    prefix: Text,
}

impl GensymGenerator {
    /// Create a new gensym generator
    pub fn new() -> Self {
        Self {
            counter: AtomicU64::new(0),
            prefix: Text::from("#gensym#"),
        }
    }

    /// Create a generator with a custom prefix
    pub fn with_prefix(prefix: &str) -> Self {
        Self {
            counter: AtomicU64::new(0),
            prefix: Text::from(prefix),
        }
    }

    /// Generate a new unique identifier
    ///
    /// The generated identifier is guaranteed to never conflict with
    /// user-written code.
    pub fn gensym(&self, base: &str) -> Text {
        let id = self.counter.fetch_add(1, Ordering::SeqCst);
        Text::from(format!("{}{}{}", base, self.prefix.as_str(), id).as_str())
    }

    /// Generate a new hygienic identifier with scope information
    pub fn gensym_hygienic(&self, base: &str, scopes: ScopeSet, span: Span) -> HygienicIdent {
        let name = self.gensym(base);
        HygienicIdent::new(name, scopes, span)
    }

    /// Generate a unique temporary variable name
    pub fn temp_var(&self) -> Text {
        self.gensym("_tmp")
    }

    /// Generate a unique label name
    pub fn temp_label(&self) -> Text {
        self.gensym("_label")
    }

    /// Check if an identifier was generated by gensym
    pub fn is_gensym(name: &str) -> bool {
        name.contains("#gensym#")
    }

    /// Extract the base name from a gensym identifier
    pub fn base_name(name: &str) -> Option<Text> {
        if let Some(pos) = name.find("#gensym#") {
            Some(Text::from(&name[..pos]))
        } else {
            None
        }
    }

    /// Get the current counter value (for debugging)
    pub fn current_count(&self) -> u64 {
        self.counter.load(Ordering::Relaxed)
    }

    /// Reset the counter (for testing)
    #[cfg(test)]
    pub fn reset(&self) {
        self.counter.store(0, Ordering::SeqCst);
    }
}

impl Default for GensymGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Clone for GensymGenerator {
    fn clone(&self) -> Self {
        Self {
            counter: AtomicU64::new(self.counter.load(Ordering::Relaxed)),
            prefix: self.prefix.clone(),
        }
    }
}

/// Suffix-based hygiene generator (legacy, for backward compatibility)
///
/// This generates identifiers using the simpler `name__id` format
/// used by the original HygieneContext.
#[derive(Debug)]
pub struct SuffixHygieneGenerator {
    /// Counter for generating unique IDs
    counter: AtomicU64,
}

impl SuffixHygieneGenerator {
    /// Create a new suffix hygiene generator
    pub fn new() -> Self {
        Self {
            counter: AtomicU64::new(0),
        }
    }

    /// Generate a hygienic identifier using suffix format
    pub fn generate(&self, base_name: &str) -> Text {
        let id = self.counter.fetch_add(1, Ordering::SeqCst);
        Text::from(format!("{}__{}", base_name, id).as_str())
    }

    /// Check if an identifier uses suffix hygiene format
    pub fn is_hygienic(name: &str) -> bool {
        name.contains("__")
            && name
                .split("__")
                .nth(1)
                .map_or(false, |s| s.parse::<u64>().is_ok())
    }

    /// Extract the base name from a suffix-hygienic identifier
    pub fn base_name(name: &str) -> Text {
        if let Some(base) = name.split("__").next() {
            Text::from(base)
        } else {
            Text::from(name)
        }
    }
}

impl Default for SuffixHygieneGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Clone for SuffixHygieneGenerator {
    fn clone(&self) -> Self {
        Self {
            counter: AtomicU64::new(self.counter.load(Ordering::Relaxed)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gensym() {
        let generator = GensymGenerator::new();

        let id1 = generator.gensym("x");
        let id2 = generator.gensym("x");

        assert_ne!(id1, id2);
        assert!(GensymGenerator::is_gensym(id1.as_str()));
        assert!(GensymGenerator::is_gensym(id2.as_str()));
    }

    #[test]
    fn test_gensym_base_name() {
        let generator = GensymGenerator::new();
        let id = generator.gensym("variable");

        let base = GensymGenerator::base_name(id.as_str());
        assert_eq!(base, Some(Text::from("variable")));
    }

    #[test]
    fn test_suffix_hygiene() {
        let generator = SuffixHygieneGenerator::new();

        let id = generator.generate("foo");
        assert!(SuffixHygieneGenerator::is_hygienic(id.as_str()));
        assert_eq!(SuffixHygieneGenerator::base_name(id.as_str()).as_str(), "foo");
    }

    #[test]
    fn test_temp_var() {
        let generator = GensymGenerator::new();

        let tmp1 = generator.temp_var();
        let tmp2 = generator.temp_var();

        assert!(tmp1.as_str().starts_with("_tmp"));
        assert!(tmp2.as_str().starts_with("_tmp"));
        assert_ne!(tmp1, tmp2);
    }
}
